---
permalink: api-automation/concept_um_apis_list_intro.html 
sidebar: sidebar 
keywords: unified, manager, rest, api 
summary: In questa sezione sono elencate le API REST per Active IQ Unified Manager , in base alle rispettive categorie. 
---
= API REST di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In questa sezione sono elencate le API REST per Active IQ Unified Manager , in base alle rispettive categorie.

È possibile visualizzare la pagina della documentazione online dalla propria istanza di Unified Manager, che include i dettagli di ogni chiamata API REST.  Il presente documento non ripete i dettagli della documentazione online.  Ogni chiamata API elencata o descritta in questo documento include solo le informazioni necessarie per individuare la chiamata nella pagina della documentazione.  Dopo aver individuato una chiamata API specifica, è possibile esaminarne i dettagli completi, inclusi i parametri di input, i formati di output, i codici di stato HTTP e il tipo di elaborazione della richiesta.

Per ogni chiamata API all'interno di un flusso di lavoro sono incluse le seguenti informazioni, che aiutano a individuare la chiamata nella pagina della documentazione:

* Categoria
+
Le chiamate API sono organizzate nella pagina della documentazione in aree o categorie correlate dal punto di vista funzionale.  Per individuare una chiamata API specifica, scorrere fino alla fine della pagina, quindi fare clic sulla categoria API applicabile.

* Verbo HTTP (chiamata)
+
Il verbo HTTP identifica l'azione eseguita su una risorsa. Ogni chiamata API viene eseguita tramite un singolo verbo HTTP.

* Sentiero
+
Il percorso determina la risorsa specifica che l'azione utilizza come parte dell'esecuzione di una chiamata. La stringa del percorso viene aggiunta all'URL principale per formare l'URL completo che identifica la risorsa.


