---
permalink: api-automation/concept_view_workloads.html 
sidebar: sidebar 
keywords: view, storage, workloads 
summary: 'Le API elencate qui consentono di visualizzare un elenco consolidato dei carichi di lavoro di archiviazione per tutti i cluster ONTAP nel data center.  Le API forniscono anche una vista riepilogativa del numero di carichi di lavoro di archiviazione forniti nell"ambiente Active IQ Unified Manager e delle relative statistiche di capacità e prestazioni (IOPS).' 
---
= Visualizza i carichi di lavoro di archiviazione tramite API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le API elencate qui consentono di visualizzare un elenco consolidato dei carichi di lavoro di archiviazione per tutti i cluster ONTAP nel data center.  Le API forniscono anche una vista riepilogativa del numero di carichi di lavoro di archiviazione forniti nell'ambiente Active IQ Unified Manager e delle relative statistiche di capacità e prestazioni (IOPS).



== Visualizza i carichi di lavoro di archiviazione

È possibile utilizzare il metodo seguente per visualizzare tutti i carichi di lavoro di archiviazione in tutti i cluster del data center.  Per informazioni sul filtraggio della risposta in base a colonne specifiche, consulta la documentazione di riferimento API disponibile nella tua istanza di Unified Manager.

[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/workloads`

|===


== Visualizza il riepilogo dei carichi di lavoro di archiviazione

È possibile utilizzare il seguente metodo per valutare la capacità utilizzata, la capacità disponibile, gli IOPS utilizzati, gli IOPS disponibili e il numero di carichi di lavoro di archiviazione gestiti da ciascun livello di servizio delle prestazioni.  I carichi di lavoro di archiviazione visualizzati possono riguardare qualsiasi LUN, condivisione file NFS o condivisione CIFS.  L'API fornisce una panoramica dei carichi di lavoro di storage, una panoramica dei carichi di lavoro di storage forniti da Unified Manager, una panoramica del data center, una panoramica dello spazio totale, utilizzato e disponibile e degli IOPS nel data center, in termini di livelli di servizio delle prestazioni assegnati.  Le informazioni ricevute in risposta a questa API vengono utilizzate per popolare la dashboard nell'interfaccia utente di Unified Manager.

[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/workloads-summary`

|===