---
permalink: api-automation/concept_api_url_and_categories.html 
sidebar: sidebar 
keywords: active iq, unified manager, api, access, categories 
summary: 'Le API di Active IQ Unified Manager consentono di gestire e fornire oggetti di archiviazione nel proprio ambiente.  È anche possibile accedere all"interfaccia utente Web di Unified Manager per eseguire alcune di queste funzioni.' 
---
= Accesso e categorie API Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Le API di Active IQ Unified Manager consentono di gestire e fornire oggetti di archiviazione nel proprio ambiente.  È anche possibile accedere all'interfaccia utente Web di Unified Manager per eseguire alcune di queste funzioni.



== Crea un URL per accedere direttamente alle API REST

È possibile accedere alle API REST direttamente tramite un linguaggio di programmazione, come Python, C#, C{pp}, JavaScript e così via.  Inserisci il nome host o l'indirizzo IP e l'URL per accedere alle API REST nel formato

+https://<nomehost>/api+

[NOTE]
====
La porta predefinita è 443. È possibile configurare la porta in base alle esigenze del proprio ambiente.

====


== Accedi alla pagina della documentazione API online

È possibile accedere alla pagina di riferimento _Documentazione API_ fornita insieme al prodotto per visualizzare la documentazione API, nonché per emettere manualmente una chiamata API (sull'interfaccia, ad esempio, Swagger).  È possibile accedere a questa documentazione cliccando sulla *Barra dei menu* > *Pulsante Aiuto* > *Documentazione API*

In alternativa, immettere il nome host o l'indirizzo IP e l'URL per accedere alla pagina REST API nel formato

+https://<nomehost>/docs/api/+



== Categorie

Le chiamate API sono organizzate funzionalmente in base alle aree o alle categorie.  Per individuare un'API specifica, fare clic sulla categoria API applicabile.

Le API REST fornite con Unified Manager ti aiutano a svolgere funzioni amministrative, di monitoraggio e di provisioning.  Le API sono raggruppate nelle seguenti categorie.

* *centro dati*
+
Questa categoria contiene le API che ti aiutano nella gestione e nell'analisi dello storage del data center utilizzando strumenti come Work Flow Automation e Ansible.  Le API REST in questa categoria forniscono informazioni su cluster, nodi, aggregati, volumi, LUN, condivisioni file, namespace e altri elementi nel data center.

* *server di gestione*
+
Le API nella categoria *management-server* contengono `jobs, system,` E `events` API.  I job sono operazioni pianificate per l'esecuzione asincrona relative alla gestione di oggetti di archiviazione o carichi di lavoro su Unified Manager.  IL `events` L'API restituisce eventi nel tuo data center e `system` L'API restituisce i dettagli dell'istanza di Unified Manager.

* *fornitore di storage*
+
Questa categoria contiene tutte le API di provisioning necessarie per la gestione e il provisioning di condivisioni file, LUN, livelli di servizio delle prestazioni e policy di efficienza dell'archiviazione.  Le API consentono inoltre di configurare endpoint di accesso, Active Directory, nonché di assegnare livelli di servizio delle prestazioni e criteri di efficienza dell'archiviazione sui carichi di lavoro di archiviazione.

* *amministrazione*
+
Questa categoria contiene le API utilizzate per eseguire attività amministrative, come la gestione delle impostazioni di backup, la visualizzazione dei certificati di trust store per le origini dati di Unified Manager e la gestione dei cluster ONTAP come origini dati per Unified Manager.

* *portale*
+
Unified Manager consente di richiamare le API REST ONTAP tramite le API nella categoria gateway e di gestire gli oggetti di archiviazione nel data center.

* *sicurezza*
+
Questa categoria contiene le API per la gestione degli utenti di Unified Manager.


