---
permalink: api-automation/concept_async_run.html 
sidebar: sidebar 
keywords: job, objects, asynchronous, processes 
summary: 'Active IQ Unified Manager fornisce l"API Jobs che recupera informazioni sui Jobs eseguiti durante l"esecuzione di altre API. È necessario sapere come funziona l"elaborazione asincrona utilizzando l"oggetto Job.' 
---
= Processi asincroni degli oggetti di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager fornisce `jobs` API che recupera informazioni sui lavori eseguiti durante l'esecuzione di altre API. È necessario sapere come funziona l'elaborazione asincrona utilizzando l'oggetto Job.

Alcune chiamate API, in particolare quelle utilizzate per aggiungere o modificare risorse, possono richiedere più tempo per essere completate rispetto ad altre chiamate.  Unified Manager elabora queste richieste di lunga durata in modo asincrono.



== Richieste asincrone descritte utilizzando l'oggetto Job

Dopo aver effettuato una chiamata API eseguita in modo asincrono, il codice di risposta HTTP 202 indica che la richiesta è stata convalidata e accettata correttamente, ma non è ancora stata completata. La richiesta viene elaborata come un'attività in background che continua a essere eseguita dopo la risposta HTTP iniziale al client. La risposta include l'oggetto Job che ancora la richiesta, incluso il suo identificatore univoco.



== Interroga l'oggetto Job associato a una richiesta API

L'oggetto Job restituito nella risposta HTTP contiene diverse proprietà. È possibile interrogare la proprietà di stato per determinare se la richiesta è stata completata correttamente. Un oggetto Job può trovarsi in uno dei seguenti stati:

* `NORMAL`
* `WARNING`
* `PARTIAL_FAILURES`
* `ERROR`


Esistono due tecniche che è possibile utilizzare quando si interroga un oggetto Job per rilevare uno stato terminale per l'attività, ovvero successo o fallimento:

* Richiesta di polling standard: lo stato corrente del Job viene restituito immediatamente.
* Richiesta di polling lungo: quando lo stato del lavoro passa a `NORMAL, ERROR,` O `PARTIAL_FAILURES.`




== Fasi di una richiesta asincrona

Per completare una chiamata API asincrona, è possibile utilizzare la seguente procedura di alto livello:

. Emettere la chiamata API asincrona.
. Ricevere una risposta HTTP 202 che indica l'accettazione corretta della richiesta.
. Estrarre l'identificatore per l'oggetto Job dal corpo della risposta.
. All'interno di un ciclo, attendi che l'oggetto Job raggiunga lo stato terminale `NORMAL, ERROR,` O `PARTIAL_FAILURES.`
. Verificare lo stato terminale del Job e recuperare il risultato del Job.

