---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: 'È possibile utilizzare l"API /storage-provider/file-shares per visualizzare, aggiungere, modificare ed eliminare i volumi di condivisione file CIFS e NFS nell"ambiente del data center.' 
---
= Gestisci le condivisioni di file tramite API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `/storage-provider/file-shares` API per visualizzare, aggiungere, modificare ed eliminare i volumi di condivisione file CIFS e NFS nell'ambiente del data center.

Prima di effettuare il provisioning dei volumi di condivisione file, assicurarsi che l'SVM sia stato creato e predisposto con i protocolli supportati.  Se si assegnano livelli di servizio delle prestazioni (PSL) o criteri di efficienza dell'archiviazione (SEP), durante il provisioning, i PSL o gli SEP devono essere creati prima di creare le condivisioni file.



== Visualizza le condivisioni di file

È possibile utilizzare il metodo seguente per visualizzare i volumi di condivisione file disponibili nell'ambiente Unified Manager.  Dopo aver aggiunto un cluster ONTAP come origine dati su Active IQ Unified Manager, i carichi di lavoro di archiviazione per tali cluster vengono aggiunti automaticamente all'istanza di Unified Manager.  Questa API recupera automaticamente e manualmente le condivisioni file aggiunte alla tua istanza di Unified Manager.  È possibile visualizzare i dettagli di una specifica condivisione file eseguendo questa API con la chiave di condivisione file.

[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/file-shares`

`/storage-provider/file-shares/\{key}`

|===


== Aggiungi condivisioni di file

È possibile utilizzare il seguente metodo per aggiungere condivisioni file CIFS e NFS nella propria SVM.  È necessario immettere i dettagli della condivisione file che si desidera creare come parametri di input.  Non è possibile utilizzare questa API per aggiungere volumi FlexGroup .

[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
INVIARE
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
A seconda che vengano forniti i parametri dell'elenco di controllo di accesso (ACL) o i parametri della policy di esportazione, vengono create condivisioni CIFS o condivisioni file NFS.  Se non si specificano i valori per i parametri ACL, le condivisioni CIFS non vengono create e per impostazione predefinita vengono create le condivisioni NFS, consentendo l'accesso a tutti.

====
*Creazione di volumi di protezione dati*: quando si aggiungono condivisioni file al proprio SVM, il tipo di volume montato, per impostazione predefinita, è `rw` (lettura-scrittura).  Per creare volumi di protezione dei dati (DP), specificare `dp` come valore per il `type` parametro.



== Elimina le condivisioni di file

Per eliminare una condivisione file specifica, è possibile utilizzare il seguente metodo.  Per eliminare una determinata condivisione file, è necessario immettere la chiave di condivisione file come parametro di input.

[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
ELIMINARE
 a| 
`/storage-provider/file-shares/\{key}`

|===


== Modificare le condivisioni di file

È possibile utilizzare il seguente metodo per modificare una condivisione file e aggiornarne le proprietà.

Per modificare una determinata condivisione file è necessario fornire la chiave di condivisione file.  Inoltre, è necessario inserire la proprietà che si desidera aggiornare, insieme al suo valore.

[NOTE]
====
Tieni presente che puoi aggiornare solo una proprietà in una singola invocazione di questa API.  Per effettuare più aggiornamenti, è necessario eseguire questa API tante volte.

====
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
TOPPA
 a| 
`/storage-provider/file-shares/\{key}`

|===