---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: 'I flussi di lavoro comuni forniscono agli sviluppatori di applicazioni client esempi di come le API di Active IQ Unified Manager possono essere richiamate da un"applicazione client per eseguire funzioni comuni di gestione dell"archiviazione.  Questa sezione contiene alcuni di questi flussi di lavoro di esempio.' 
---
= Flussi di lavoro API comuni per la gestione dell'archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I flussi di lavoro comuni forniscono agli sviluppatori di applicazioni client esempi di come le API di Active IQ Unified Manager possono essere richiamate da un'applicazione client per eseguire funzioni comuni di gestione dell'archiviazione.  Questa sezione contiene alcuni di questi flussi di lavoro di esempio.

I flussi di lavoro descrivono alcuni dei casi d'uso più comuni per la gestione dell'archiviazione, insieme a codici di esempio da utilizzare.  Ciascuna attività viene descritta mediante un processo di flusso di lavoro costituito da una o più chiamate API.



== Comprendere le chiamate API utilizzate nei flussi di lavoro

È possibile visualizzare la pagina della documentazione online dalla propria istanza di Unified Manager, che include i dettagli di ogni chiamata API REST.  Il presente documento non ripete i dettagli della documentazione online.  Ogni chiamata API utilizzata negli esempi di flusso di lavoro in questo documento include solo le informazioni necessarie per individuare la chiamata nella pagina della documentazione. Dopo aver individuato una specifica chiamata API, è possibile esaminarne i dettagli completi, inclusi i parametri di input, i formati di output, i codici di stato HTTP e il tipo di elaborazione della richiesta.

Per ogni chiamata API all'interno di un flusso di lavoro sono incluse le seguenti informazioni, che aiutano a individuare la chiamata nella pagina della documentazione:

* Categoria: le chiamate API sono organizzate nella pagina della documentazione in aree o categorie funzionalmente correlate. Per individuare una chiamata API specifica, scorrere fino alla fine della pagina e fare clic sulla categoria API applicabile.
* Verbo HTTP (chiamata): il verbo HTTP identifica l'azione eseguita su una risorsa. Ogni chiamata API viene eseguita tramite un singolo verbo HTTP.
* Percorso: il percorso determina la risorsa specifica a cui si applica l'azione come parte dell'esecuzione di una chiamata. La stringa del percorso viene aggiunta all'URL principale per formare l'URL completo che identifica la risorsa.

