---
permalink: api-automation/concept_modify_workloads_workflow.html 
sidebar: sidebar 
keywords: modify, storage, workloads 
summary: 'La modifica dei carichi di lavoro di archiviazione consiste nell"aggiornare le LUN o le condivisioni file con parametri mancanti oppure nel modificare i parametri esistenti.' 
---
= Modificare i carichi di lavoro di archiviazione utilizzando le API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modifica dei carichi di lavoro di archiviazione consiste nell'aggiornare le LUN o le condivisioni file con parametri mancanti oppure nel modificare i parametri esistenti.

Questo flusso di lavoro prende come esempio l'aggiornamento dei livelli di servizio delle prestazioni per LUN e condivisioni di file.

[NOTE]
====
Il flusso di lavoro presuppone che la LUN o la condivisione file siano state dotate di livelli di servizio di prestazioni.

====


== Modificare le condivisioni di file

Durante la modifica di una condivisione file, è possibile aggiornare i seguenti parametri:

* Capacità o dimensione.
* Impostazione online o offline.
* Politica di efficienza di archiviazione.
* Livello di servizio prestazionale.
* Impostazioni dell'elenco di controllo degli accessi (ACL).
* Esporta le impostazioni dei criteri.  È anche possibile eliminare i parametri dei criteri di esportazione e ripristinare le regole predefinite (vuote) dei criteri di esportazione sulla condivisione file.


[NOTE]
====
Durante una singola esecuzione dell'API, è possibile aggiornare solo un parametro.

====
Questa procedura descrive come aggiungere un livello di servizio delle prestazioni a una condivisione file.  È possibile utilizzare la stessa procedura per aggiornare qualsiasi altra proprietà di condivisione file.

. Ottieni la chiave di condivisione CIFS o di condivisione file NFS della condivisione file che desideri aggiornare.  Questa API interroga tutte le condivisioni file sul tuo data center.  Salta questo passaggio se conosci già la chiave di condivisione file.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/file-shares`

|===
. Visualizza i dettagli della condivisione file eseguendo la seguente API con la chiave di condivisione file ottenuta.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
Visualizza i dettagli della condivisione file nell'output.

+
[listing]
----
"assigned_performance_service_level": {
        "key": null,
        "name": "Unassigned",
        "peak_iops": null,
        "expected_iops": null,
        "_links": {}
      },
----
. Ottieni la chiave per il livello di servizio delle prestazioni che desideri assegnare a questa condivisione file.  Attualmente non gli è assegnata alcuna policy.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Livelli di servizio prestazionali
 a| 
OTTENERE
 a| 
`/storage-provider/performance-service-levels`

|===
+
[NOTE]
====
È possibile recuperare i dettagli dei livelli di servizio delle prestazioni definiti dal sistema impostando `system_defined` parametro di input a `true` .  Dall'output, ottenere la chiave del Performance Service Level che si desidera applicare alla condivisione file.

====
. Applicare il livello di servizio delle prestazioni alla condivisione file.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Fornitore di archiviazione
 a| 
TOPPA
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
Nell'input è necessario specificare solo il parametro che si desidera aggiornare, insieme alla chiave di condivisione file.  In questo caso, è la chiave del Performance Service Level.

+
*Esempio di cURL*

+
[listing]
----
curl -X POST "https://<hostname>/api/storage-provider/file-shares"`-H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" -d
"{
\"performance_service_level\": { \"key\": \"1251e51b-069f-11ea-980d-fa163e82bbf2\" },
}"
----
+
L'output JSON visualizza un oggetto Job che è possibile utilizzare per verificare se gli endpoint di accesso sui nodi home e partner sono stati creati correttamente.

. Verificare se il livello di servizio delle prestazioni è stato aggiunto alla condivisione file utilizzando la chiave dell'oggetto Job visualizzata nell'output.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Server di gestione
 a| 
OTTENERE
 a| 
`/management-server/jobs/\{key}`

|===
+
Se si esegue una query tramite l'ID dell'oggetto Job, è possibile verificare se la condivisione file è stata aggiornata correttamente.  In caso di errore, risolvere il problema ed eseguire nuovamente l'API.  Una volta completata la creazione, interroga la condivisione file per visualizzare l'oggetto modificato:

+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
Visualizza i dettagli della condivisione file nell'output.

+
[listing]
----
"assigned_performance_service_level": {
        "key": "1251e51b-069f-11ea-980d-fa163e82bbf2",
        "name": "Value",
        "peak_iops": 75,
        "expected_iops": 75,
        "_links": {
            "self": {
                "href": "/api/storage-provider/performance-service-levels/1251e51b-069f-11ea-980d-fa163e82bbf2"
            }
        }
----




== Aggiorna LUN

Durante l'aggiornamento di una LUN, è possibile modificare i seguenti parametri:

* Capacità o dimensione
* Impostazione online o offline
* Politica di efficienza di archiviazione
* Livello di servizio delle prestazioni
* Mappa LUN


[NOTE]
====
Durante una singola esecuzione dell'API, è possibile aggiornare solo un parametro.

====
Questa procedura descrive come aggiungere un livello di servizio delle prestazioni a una LUN.  È possibile utilizzare la stessa procedura per aggiornare qualsiasi altra proprietà LUN.

. Ottieni la chiave LUN della LUN che vuoi aggiornare.  Questa API restituisce i dettagli di tutti i LUN nel tuo data center.  Saltare questo passaggio se si conosce già la chiave LUN.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Fornitore di archiviazione
 a| 
OTTENERE
 a| 
`/storage-provider/luns`

|===
. Visualizza i dettagli del LUN eseguendo la seguente API con la chiave LUN ottenuta.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Fornitore di archiviazione
 a| 
OTTENERE
 a| 
`/storage-provider/luns/\{key}`

|===
+
Visualizza i dettagli del LUN nell'output.  Come puoi vedere, a questo LUN non è assegnato alcun livello di servizio delle prestazioni.

+
*Esempio di output JSON*

+
[listing]
----

  "assigned_performance_service_level": {
        "key": null,
        "name": "Unassigned",
        "peak_iops": null,
        "expected_iops": null,
        "_links": {}
      },
----
. Ottenere la chiave per il Performance Service Level che si desidera assegnare al LUN.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Livelli di servizio prestazionali
 a| 
OTTENERE
 a| 
`/storage-provider/performance-service-levels`

|===
+
[NOTE]
====
È possibile recuperare i dettagli dei livelli di servizio delle prestazioni definiti dal sistema impostando `system_defined` parametro di input a `true` .  Dall'output, ottenere la chiave del Performance Service Level che si desidera applicare alla LUN.

====
. Applicare il livello di servizio delle prestazioni sulla LUN.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Fornitore di archiviazione
 a| 
TOPPA
 a| 
`/storage-provider/lun/\{key}`

|===
+
Nell'input è necessario specificare solo il parametro che si desidera aggiornare, insieme alla chiave LUN.  In questo caso è la chiave del Performance Service Level.

+
*Esempio di cURL*

+
[listing]
----
curl -X PATCH "https://<hostname>/api/storage-provider/luns/7d5a59b3-953a-11e8-8857-00a098dcc959" -H "accept: application/json" -H "Content-Type: application/json" H "Authorization: Basic <Base64EncodedCredentials>" -d
"{ \"performance_service_level\": { \"key\": \"1251e51b-069f-11ea-980d-fa163e82bbf2\" }"
----
+
L'output JSON visualizza una chiave dell'oggetto Job che puoi utilizzare per verificare il LUN che hai aggiornato.

. Visualizza i dettagli del LUN eseguendo la seguente API con la chiave LUN ottenuta.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
Fornitore di archiviazione
 a| 
OTTENERE
 a| 
`/storage-provider/luns/\{key}`

|===
+
Visualizza i dettagli del LUN nell'output.  È possibile vedere che a questo LUN è assegnato il Performance Service Level.

+
*Esempio di output JSON*

+
[listing]
----

     "assigned_performance_service_level": {
        "key": "1251e51b-069f-11ea-980d-fa163e82bbf2",
        "name": "Value",
        "peak_iops": 75,
        "expected_iops": 75,
        "_links": {
            "self": {
                "href": "/api/storage-provider/performance-service-levels/1251e51b-069f-11ea-980d-fa163e82bbf2"
            }
----

