---
permalink: api-automation/concept_rest_services_offered_in_unified_manager_apis.html 
sidebar: sidebar 
keywords: rest, services, offer, active iq, unified, manager 
summary: Prima di iniziare a utilizzare le API di Active IQ Unified Manager , è necessario conoscere i servizi e le operazioni REST offerti. 
---
= Servizi REST offerti in Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di iniziare a utilizzare le API di Active IQ Unified Manager , è necessario conoscere i servizi e le operazioni REST offerti.

Le API di provisioning e amministrative utilizzate per configurare il server API supportano le operazioni di lettura (GET) o scrittura (POST, PATCH, DELETE).  Di seguito sono riportati alcuni esempi delle operazioni GET, PATCH, POST e DELETE supportate dalle API:

* Esempio per GET: `GET /datacenter/cluster/clusters` recupera i dettagli del cluster nel tuo data center.  Il numero massimo di record restituiti da `GET` l'operazione è 1000.
+
[NOTE]
====
Le API consentono di filtrare, ordinare e classificare i record in base agli attributi supportati.

====
* Esempio per POST: `POST /datacenter/svm/svms` crea una macchina virtuale di archiviazione (SVM) personalizzata.
* Esempio per PATCH: `PATCH /datacenter/svm/svms/{key}` modifica le proprietà di una SVM, utilizzando la sua chiave univoca.
* Esempio per DELETE: `DELETE /storage-provider/access-endpoints/{key}` elimina un endpoint di accesso da una LUN, SVM o condivisione file utilizzando la sua chiave univoca.


Le operazioni REST che possono essere eseguite tramite le API dipendono dal ruolo dell'utente Operatore, Amministratore di archiviazione o Amministratore applicazione.

[cols="2*"]
|===
| Ruolo utente | Metodo REST supportato 


 a| 
Operatore
 a| 
Accesso ai dati in sola lettura.  Gli utenti con questo ruolo possono eseguire tutte le richieste GET.



 a| 
Amministratore di archiviazione
 a| 
Accesso in lettura a tutti i dati.  Gli utenti con questo ruolo possono eseguire tutte le richieste GET.

Inoltre, dispongono di accesso in scrittura (per eseguire richieste PATCH, POST e DELETE) per svolgere attività specifiche, come la gestione di oggetti di servizi di archiviazione e opzioni di gestione dell'archiviazione.



 a| 
Amministratore dell'applicazione
 a| 
Accesso in lettura e scrittura a tutti i dati.  Gli utenti con questo ruolo possono eseguire richieste GET, PATCH, POST e DELETE per tutte le funzioni.

|===
Per maggiori informazioni su tutte le operazioni REST, consultare la _documentazione API online_.
