---
permalink: api-automation/concept_provision_workflow.html 
sidebar: sidebar 
keywords: workflow, workload, management 
summary: 'Utilizzando Active IQ Unified Manager, è possibile effettuare il provisioning e modificare i carichi di lavoro di archiviazione (LUN, condivisioni file NFS e condivisioni CIFS).  Il provisioning è costituito da più passaggi, dalla creazione della Storage Virtual Machine (SVM) all"applicazione dei criteri di efficienza dello storage e del livello di servizio delle prestazioni sui carichi di lavoro di storage.  La modifica dei carichi di lavoro consiste nei passaggi per modificare parametri specifici e abilitare funzionalità aggiuntive su di essi.' 
---
= Flussi di lavoro API per la gestione del carico di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando Active IQ Unified Manager, è possibile effettuare il provisioning e modificare i carichi di lavoro di archiviazione (LUN, condivisioni file NFS e condivisioni CIFS).  Il provisioning è costituito da più passaggi, dalla creazione della Storage Virtual Machine (SVM) all'applicazione dei criteri di efficienza dello storage e del livello di servizio delle prestazioni sui carichi di lavoro di storage.  La modifica dei carichi di lavoro consiste nei passaggi per modificare parametri specifici e abilitare funzionalità aggiuntive su di essi.

Vengono descritti i seguenti flussi di lavoro:

* Flusso di lavoro per il provisioning di macchine virtuali di archiviazione (SVM) su Unified Manager.
+
[NOTE]
====
questo flusso di lavoro deve essere eseguito prima di effettuare il provisioning di LUN o condivisioni file su Unified Manager.

====
* Provisioning delle condivisioni di file.
* Provisioning delle LUN.
* Modifica di LUN e condivisioni file (utilizzando l'esempio per aggiornare il parametro Performance Service Level per i carichi di lavoro di archiviazione).
* Modifica di una condivisione file NFS per supportare il protocollo CIFS
* Modifica dei carichi di lavoro per aggiornare QoS ad AQoS


[NOTE]
====
Per ogni flusso di lavoro di provisioning (LUN e condivisioni file), assicurati di aver completato il flusso di lavoro per la verifica delle SVM sui cluster.

====
È inoltre necessario leggere le raccomandazioni e le limitazioni prima di utilizzare ciascuna API nei flussi di lavoro.  I dettagli rilevanti delle API sono disponibili nelle singole sezioni elencate nei concetti e nei riferimenti correlati.
