---
permalink: api-automation/concept_get_started_with_um_apis.html 
sidebar: sidebar 
keywords: active iq, unified manager 
summary: 'Active IQ Unified Manager fornisce un set di API per gestire le risorse di archiviazione sui sistemi di archiviazione supportati tramite un"interfaccia di servizio Web RESTful per qualsiasi integrazione di terze parti.' 
---
= Inizia con le API REST Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager fornisce un set di API per gestire le risorse di archiviazione sui sistemi di archiviazione supportati tramite un'interfaccia di servizio Web RESTful per qualsiasi integrazione di terze parti.

In questi argomenti troverai informazioni sulle API di Unified Manager, esempi di flussi di lavoro per risolvere problemi specifici e alcuni codici di esempio.  Utilizzando queste informazioni, è possibile creare client RESTful delle soluzioni software NetApp Manageability per la gestione dei sistemi NetApp .  Le API si basano sullo stile architettonico Representational State Transfer (REST).  Sono supportate tutte e quattro le operazioni REST: Crea, Leggi, Aggiorna ed Elimina (note anche come CRUD).

Vederelink:https://docs.netapp.com/us-en/netapp-automation/api/aiqum.html["Active IQ Unified Manager"^] per risorse aggiuntive e dettagli sui vantaggi dell'API REST Active IQ Unified Manager .
