---
permalink: api-automation/reference_authentication_errors.html 
sidebar: sidebar 
keywords: http, status, code, active iq, unified manager 
summary: 'Durante l"esecuzione delle API o la risoluzione dei problemi, è necessario conoscere i vari codici di stato HTTP e i codici di errore utilizzati dalle API di Active IQ Unified Manager .' 
---
= Codici di stato HTTP utilizzati in Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante l'esecuzione delle API o la risoluzione dei problemi, è necessario conoscere i vari codici di stato HTTP e i codici di errore utilizzati dalle API di Active IQ Unified Manager .

Nella tabella seguente sono elencati i codici di errore relativi all'autenticazione:

[cols="3*"]
|===
| Codice di stato HTTP | Titolo del codice di stato | Descrizione 


 a| 
200
 a| 
OK
 a| 
Restituito in caso di esecuzione corretta delle chiamate API sincrone.



 a| 
201
 a| 
Creato
 a| 
Creazione di nuove risorse tramite chiamate sincrone, come la configurazione di Active Directory.



 a| 
202
 a| 
Accettato
 a| 
Restituito in caso di esecuzione corretta di chiamate asincrone per funzioni di provisioning, come la creazione di LUN e condivisioni di file.



 a| 
400
 a| 
Richiesta non valida
 a| 
Indica un errore nella convalida dell'input.  L'utente deve correggere gli input, ad esempio le chiavi valide nel corpo di una richiesta.



 a| 
401
 a| 
Richiesta non autorizzata
 a| 
Non sei autorizzato a visualizzare la risorsa/Non autorizzato.



 a| 
403
 a| 
Richiesta proibita
 a| 
L'accesso alla risorsa che stavi cercando di raggiungere è vietato.



 a| 
404
 a| 
Risorsa non trovata
 a| 
La risorsa che stavi cercando di raggiungere non è stata trovata.



 a| 
405
 a| 
Metodo non consentito
 a| 
Metodo non consentito.



 a| 
429
 a| 
Troppe richieste
 a| 
Restituito quando l'utente invia troppe richieste entro un tempo specifico.



 a| 
500
 a| 
Errore interno del server
 a| 
Errore interno del server.  Impossibile ottenere la risposta dal server.  Questo errore interno del server potrebbe essere permanente o meno.  Ad esempio, se esegui un `GET` O `GET ALL` operazione e si riceve questo errore, si consiglia di ripetere l'operazione per almeno cinque tentativi.  Se si tratta di un errore permanente, il codice di stato restituito continua a essere 500.  Se l'operazione riesce, il codice di stato restituito è 200.

|===