---
permalink: api-automation/task_modify_fileshare_to_include_cifs_and_nfs.html 
sidebar: sidebar 
keywords: modify, nfs, file, share, support, cifs 
summary: 'È possibile modificare una condivisione file NFS per supportare il protocollo CIFS.  Durante la creazione della condivisione file, è possibile specificare sia i parametri dell"elenco di controllo degli accessi (ACL) sia le regole dei criteri di esportazione per la stessa condivisione file.  Tuttavia, se si desidera abilitare CIFS sullo stesso volume in cui è stata creata una condivisione file NFS, è possibile aggiornare i parametri ACL su tale condivisione file per supportare CIFS.' 
---
= Modificare una condivisione file NFS utilizzando le API per supportare CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare una condivisione file NFS per supportare il protocollo CIFS.  Durante la creazione della condivisione file, è possibile specificare sia i parametri dell'elenco di controllo degli accessi (ACL) sia le regole dei criteri di esportazione per la stessa condivisione file.  Tuttavia, se si desidera abilitare CIFS sullo stesso volume in cui è stata creata una condivisione file NFS, è possibile aggiornare i parametri ACL su tale condivisione file per supportare CIFS.

.Prima di iniziare
. Deve essere stata creata una condivisione file NFS con solo i dettagli della policy di esportazione.  Per informazioni, vedere _Gestione delle condivisioni file_ e _Modifica dei carichi di lavoro di archiviazione_.
. Per eseguire questa operazione è necessario disporre della chiave di condivisione file.  Per informazioni sulla visualizzazione dei dettagli della condivisione file e sul recupero della chiave di condivisione file tramite l'ID processo, vedere _Provisioning di condivisioni file CIFS e NFS_.


Ciò è applicabile a una condivisione file NFS creata aggiungendo solo regole di policy di esportazione e non parametri ACL.  Modificare la condivisione file NFS per includere i parametri ACL.

.Passi
. Sulla condivisione file NFS, eseguire un `PATCH` operazione con i dettagli ACL per consentire l'accesso CIFS.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
TOPPA
 a| 
`/storage-provider/file-shares`

|===
+
*Esempio di cURL*

+
In base ai privilegi di accesso assegnati al gruppo utenti, come mostrato nell'esempio seguente, viene creato un ACL e assegnato alla condivisione file.

+
[listing]
----
{
  "access_control": {
    "acl": [
      {
        "permission": "read",
        "user_or_group": "everyone"
      }
    ],
    "active_directory_mapping": {
      "key": "3b648c1b-d965-03b7-20da-61b791a6263c"
    }
----
+
*Esempio di output JSON*

+
L'operazione restituisce l'ID del job che esegue l'aggiornamento.

. Verificare se i parametri sono stati aggiunti correttamente interrogando i dettagli della condivisione file per la stessa condivisione file.
+
[cols="3*"]
|===
| Categoria | Verbo HTTP | Sentiero 


 a| 
fornitore di storage
 a| 
OTTENERE
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
*Esempio di output JSON*

+
[listing]
----
"access_control": {
        "acl": [
            {
                "user_or_group": "everyone",
                "permission": "read"
            }
        ],
        "export_policy": {
            "id": 1460288880641,
            "key": "7d5a59b3-953a-11e8-8857-00a098dcc959:type=export_policy,uuid=1460288880641",
            "name": "default",
            "rules": [
                {
                    "anonymous_user": "65534",
                    "clients": [
                        {
                            "match": "0.0.0.0/0"
                        }
                    ],
                    "index": 1,
                    "protocols": [
                        "nfs3",
                        "nfs4"
                    ],
                    "ro_rule": [
                        "sys"
                    ],
                    "rw_rule": [
                        "sys"
                    ],
                    "superuser": [
                        "none"
                    ]
                },
                {
                    "anonymous_user": "65534",
                    "clients": [
                        {
                            "match": "0.0.0.0/0"
                        }
                    ],
                    "index": 2,
                    "protocols": [
                        "cifs"
                    ],
                    "ro_rule": [
                        "ntlm"
                    ],
                    "rw_rule": [
                        "ntlm"
                    ],
                    "superuser": [
                        "none"
                    ]
                }
            ],
            "_links": {
                "self": {
                    "href": "/api/datacenter/protocols/nfs/export-policies/7d5a59b3-953a-11e8-8857-00a098dcc959:type=export_policy,uuid=1460288880641"
                }
            }
        }
    },
    "_links": {
        "self": {
            "href": "/api/storage-provider/file-shares/7d5a59b3-953a-11e8-8857-00a098dcc959:type=volume,uuid=e581c23a-1037-11ea-ac5a-00a098dcc6b6"
        }
    }
----
+
È possibile visualizzare l'ACL assegnato insieme alla policy di esportazione sulla stessa condivisione file.


