---
permalink: reporting/concept_understand_reports.html 
sidebar: sidebar 
keywords: understanding, reports 
summary: I report mostrano informazioni dettagliate su storage, rete, qualità del servizio e relazioni di protezione, aiutandoti a identificare e risolvere potenziali problemi prima che si verifichino. 
---
= Comprendere i report
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I report mostrano informazioni dettagliate su storage, rete, qualità del servizio e relazioni di protezione, aiutandoti a identificare e risolvere potenziali problemi prima che si verifichino.

Quando personalizzi una vista, puoi salvarla con un nome univoco per un utilizzo futuro.  È possibile pianificare l'esecuzione regolare di un report basato su tale visualizzazione e condividerlo con altri.  È anche possibile scaricare la visualizzazione in Excel per personalizzarla utilizzando le funzionalità avanzate di Excel, quindi caricare nuovamente il file in Unified Manager.  Se pianifichi un report utilizzando quella vista, verrà utilizzato il file Excel caricato per creare report efficaci che potrai condividere.

È possibile gestire tutti i report pianificati dalla pagina Pianificazioni report.

[NOTE]
====
Per gestire i report è necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

====
È possibile scaricare i report come file CSV (valori separati da virgole), Excel o PDF.
