---
permalink: performance-checker/concept_cluster_configuration_and_performance_data_collection_activity.html 
sidebar: sidebar 
keywords: cluster, configuration, performance, data, collection, activity 
summary: 'L"intervallo di raccolta per i dati di configurazione del cluster è di 15 minuti.  Ad esempio, dopo aver aggiunto un cluster, ci vogliono 15 minuti per visualizzare i dettagli del cluster nell"interfaccia utente di Unified Manager.  Questo intervallo si applica anche quando si apportano modifiche a un cluster.' 
---
= Attività di raccolta dati sulla configurazione e sulle prestazioni del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'intervallo di raccolta per i _dati di configurazione del cluster_ è di 15 minuti.  Ad esempio, dopo aver aggiunto un cluster, ci vogliono 15 minuti per visualizzare i dettagli del cluster nell'interfaccia utente di Unified Manager.  Questo intervallo si applica anche quando si apportano modifiche a un cluster.

Ad esempio, se si aggiungono due nuovi volumi a una SVM in un cluster, i nuovi oggetti verranno visualizzati nell'interfaccia utente dopo il successivo intervallo di polling, che potrebbe durare fino a 15 minuti.

Unified Manager raccoglie le statistiche sulle prestazioni correnti da tutti i cluster monitorati ogni cinque minuti.  Analizza questi dati per identificare eventi prestazionali e potenziali problemi.  Conserva 30 giorni di dati storici sulle prestazioni di cinque minuti e 180 giorni di dati storici sulle prestazioni di un'ora.  Ciò consente di visualizzare dettagli molto granulari sulle prestazioni per il mese corrente e tendenze generali delle prestazioni fino a un anno.

I sondaggi di raccolta vengono sfalsati di alcuni minuti in modo che i dati di ogni cluster non vengano inviati contemporaneamente, il che potrebbe influire sulle prestazioni.

Nella tabella seguente vengono descritte le attività di raccolta eseguite da Unified Manager:

|===
| Attività | Intervallo di tempo | Descrizione 


 a| 
Sondaggio sulle statistiche delle prestazioni
 a| 
Ogni 5 minuti
 a| 
Raccoglie dati sulle prestazioni in tempo reale da ciascun cluster.



 a| 
Analisi statistica
 a| 
Ogni 5 minuti
 a| 
Dopo ogni sondaggio statistico, Unified Manager confronta i dati raccolti con soglie definite dall'utente, definite dal sistema e dinamiche.

Se vengono superate le soglie di prestazione, Unified Manager genera eventi e invia e-mail agli utenti specificati, se configurato per farlo.



 a| 
Sondaggio di configurazione
 a| 
Ogni 15 minuti
 a| 
Raccoglie informazioni di inventario dettagliate da ciascun cluster per identificare tutti gli oggetti di archiviazione (nodi, SVM, volumi e così via).



 a| 
Riassunto
 a| 
Ogni ora
 a| 
Riassume le ultime 12 raccolte di dati sulle prestazioni di cinque minuti in medie orarie.

I valori medi orari vengono utilizzati in alcune pagine dell'interfaccia utente e conservati per 180 giorni.



 a| 
Analisi delle previsioni e potatura dei dati
 a| 
Ogni giorno dopo mezzanotte
 a| 
Analizza i dati del cluster per stabilire soglie dinamiche per la latenza del volume e gli IOPS per le successive 24 ore.

Elimina dal database tutti i dati sulle prestazioni di cinque minuti più vecchi di 30 giorni.



 a| 
Potatura dei dati
 a| 
Ogni giorno dopo le 2 del mattino
 a| 
Elimina dal database tutti gli eventi più vecchi di 180 giorni e le soglie dinamiche più vecchie di 180 giorni.



 a| 
Potatura dei dati
 a| 
Tutti i giorni dopo le 3:30 del mattino
 a| 
Elimina dal database tutti i dati sulle prestazioni orarie più vecchi di 180 giorni.

|===