---
permalink: performance-checker/concept_move_logical_interfaces.html 
sidebar: sidebar 
keywords: move, logical, interfaces, lifs 
summary: 'Spostare le interfacce logiche (LIF) su una porta meno trafficata può aiutare a migliorare il bilanciamento del carico, agevolare le operazioni di manutenzione e l"ottimizzazione delle prestazioni e ridurre l"accesso indiretto.' 
---
= Spostare le interfacce logiche (LIF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Spostare le interfacce logiche (LIF) su una porta meno trafficata può aiutare a migliorare il bilanciamento del carico, agevolare le operazioni di manutenzione e l'ottimizzazione delle prestazioni e ridurre l'accesso indiretto.

L'accesso indiretto può ridurre l'efficienza del sistema.  Si verifica quando un carico di lavoro di volume utilizza nodi diversi per l'elaborazione di rete e l'elaborazione dei dati.  Per ridurre l'accesso indiretto, è possibile riorganizzare i LIF, ovvero spostarli in modo che utilizzino lo stesso nodo per l'elaborazione di rete e l'elaborazione dei dati.  È possibile configurare il bilanciamento del carico in modo che ONTAP sposti automaticamente i LIF occupati su una porta diversa oppure è possibile spostare un LIF manualmente.

[cols="2*"]
|===
| *Benefici* | *Considerazioni* 


 a| 
* Migliorare il bilanciamento del carico.
* Ridurre l'accesso indiretto.

 a| 
[NOTE]
====
Quando si sposta un LIF connesso alle condivisioni CIFS, i client che accedono alle condivisioni CIFS vengono disconnessi.  Tutte le richieste di lettura o scrittura sulle condivisioni CIFS vengono interrotte.

====
|===
Per configurare il bilanciamento del carico si utilizzano i comandi ONTAP .  Per ulteriori informazioni, consultare la documentazione sulla rete ONTAP .

Per spostare manualmente i LIF, utilizzare ONTAP System Manager e i comandi ONTAP CLI.
