---
permalink: performance-checker/concept_add_disks_and_perform_aggregate_layout_reconstruction.html 
sidebar: sidebar 
keywords: add, disks, perform, aggregate, layout, reconstruction 
summary: 'È possibile aggiungere dischi a un aggregato per aumentarne la capacità di archiviazione e le prestazioni.  Dopo aver aggiunto i dischi, si nota un miglioramento delle prestazioni solo dopo aver ricostruito l"aggregato.' 
---
= Aggiungere dischi ed eseguire la ricostruzione del layout aggregato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere dischi a un aggregato per aumentarne la capacità di archiviazione e le prestazioni.  Dopo aver aggiunto i dischi, si nota un miglioramento delle prestazioni solo dopo aver ricostruito l'aggregato.

Quando si riceve un evento soglia definito dal sistema nella pagina Dettagli evento, il testo della descrizione dell'evento elenca il nome dell'aggregato che presenta il problema.  È possibile aggiungere dischi e ricostruire i dati su questo aggregato.

I dischi aggiunti all'aggregato devono già esistere nel cluster.  Se il cluster non dispone di dischi aggiuntivi, potrebbe essere necessario contattare l'amministratore o acquistarne altri.  È possibile utilizzare ONTAP System Manager o i comandi ONTAP per aggiungere dischi a un aggregato.

https://www.netapp.com/pdf.html?item=/media/19675-tr-3838.pdf["Rapporto tecnico 3838: Guida alla configurazione del sottosistema di archiviazione"^]
