---
permalink: performance-checker/concept_refine_object_inventory_performance_page_content.html 
sidebar: sidebar 
keywords: refining, performance, inventory, page, contents 
summary: Le pagine di inventario per gli oggetti di prestazione contengono strumenti che consentono di perfezionare il contenuto dei dati di inventario degli oggetti, consentendo di individuare dati specifici in modo rapido e semplice. 
---
= Contenuto della pagina dell'inventario delle prestazioni di raffinazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le pagine di inventario per gli oggetti di prestazione contengono strumenti che consentono di perfezionare il contenuto dei dati di inventario degli oggetti, consentendo di individuare dati specifici in modo rapido e semplice.

Le informazioni contenute nelle pagine dell'inventario degli oggetti Performance possono essere molto estese e spesso occupano più pagine.  Questo tipo di dati completi è ottimo per monitorare, tracciare e migliorare le prestazioni; tuttavia, per individuare dati specifici sono necessari strumenti che consentano di individuare rapidamente i dati che si stanno cercando.  Pertanto, le pagine dell'inventario degli oggetti Performance contengono funzionalità per la ricerca, l'ordinamento e il filtraggio.  Inoltre, la ricerca e il filtraggio possono interagire tra loro per restringere ulteriormente i risultati.
