---
permalink: performance-checker/concept_analyze_events_from_system_defined_performance_thresholds.html 
sidebar: sidebar 
keywords: analyze, events, system-defined, performance, thresholds 
summary: 'Gli eventi generati dalle soglie di prestazioni definite dal sistema indicano che un contatore delle prestazioni, o un set di contatori delle prestazioni, per un determinato oggetto di archiviazione ha superato la soglia di una policy definita dal sistema.  Ciò indica che l"oggetto di archiviazione, ad esempio un aggregato o un nodo, sta riscontrando un problema di prestazioni.' 
---
= Analizza gli eventi dalle soglie di prestazione definite dal sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi generati dalle soglie di prestazioni definite dal sistema indicano che un contatore delle prestazioni, o un set di contatori delle prestazioni, per un determinato oggetto di archiviazione ha superato la soglia di una policy definita dal sistema.  Ciò indica che l'oggetto di archiviazione, ad esempio un aggregato o un nodo, sta riscontrando un problema di prestazioni.

È possibile utilizzare la pagina Dettagli evento per analizzare l'evento prestazionale e, se necessario, adottare misure correttive per riportare le prestazioni alla normalità.

[NOTE]
====
I criteri di soglia definiti dal sistema non sono abilitati sui sistemi Cloud Volumes ONTAP, ONTAP Edge o ONTAP Select .

====