---
permalink: performance-checker/concept_manage_performance_thresholds.html 
sidebar: sidebar 
keywords: manage, performance, thresholds 
summary: 'I criteri di soglia delle prestazioni consentono di determinare il punto in cui Unified Manager genera un evento per informare gli amministratori di sistema sui problemi che potrebbero influire sulle prestazioni del carico di lavoro.  Queste policy di soglia sono note come soglie di prestazione definite dall"utente.' 
---
= Gestire le soglie di prestazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I criteri di soglia delle prestazioni consentono di determinare il punto in cui Unified Manager genera un evento per informare gli amministratori di sistema sui problemi che potrebbero influire sulle prestazioni del carico di lavoro.  Queste policy di soglia sono note come soglie di prestazione _definite dall'utente_.

Questa versione supporta soglie di prestazioni definite dall'utente, definite dal sistema e dinamiche.  Grazie a soglie di prestazioni dinamiche e definite dal sistema, Unified Manager analizza l'attività del carico di lavoro per determinare il valore di soglia appropriato.  Grazie alle soglie definite dall'utente, è possibile definire i limiti massimi delle prestazioni per molti contatori delle prestazioni e per molti oggetti di archiviazione.

[NOTE]
====
Le soglie di prestazioni definite dal sistema e le soglie di prestazioni dinamiche sono impostate da Unified Manager e non sono configurabili.  Se si ricevono eventi non necessari da qualsiasi criterio di soglia delle prestazioni definito dal sistema, è possibile disattivare i singoli criteri dalla pagina Configurazione evento.

====