---
permalink: performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html 
sidebar: sidebar 
keywords: roles, workloads, involved, performance, event 
summary: 'Unified Manager utilizza i ruoli per identificare il coinvolgimento di un carico di lavoro in un evento di prestazione.  I ruoli includono vittime, bulli e squali.  Un carico di lavoro definito dall"utente può essere allo stesso tempo vittima, bullo e squalo.' 
---
= Ruoli dei carichi di lavoro coinvolti in un evento di performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager utilizza i ruoli per identificare il coinvolgimento di un carico di lavoro in un evento di prestazione.  I ruoli includono vittime, bulli e squali.  Un carico di lavoro definito dall'utente può essere allo stesso tempo vittima, bullo e squalo.

|===
| Ruolo | Descrizione 


 a| 
Vittima
 a| 
Un carico di lavoro definito dall'utente le cui prestazioni sono diminuite a causa di altri carichi di lavoro, denominati "bulli", che utilizzano eccessivamente un componente del cluster.  Solo i carichi di lavoro definiti dall'utente vengono identificati come vittime.  Unified Manager identifica i carichi di lavoro delle vittime in base alla loro deviazione nella latenza, dove la latenza effettiva, durante un evento, è notevolmente aumentata rispetto alla latenza prevista (intervallo previsto).



 a| 
Bullo
 a| 
Un carico di lavoro definito dall'utente o dal sistema il cui utilizzo eccessivo di un componente del cluster ha causato una riduzione delle prestazioni di altri carichi di lavoro, denominati vittime.  Unified Manager identifica i carichi di lavoro eccessivi in base alla loro deviazione nell'utilizzo di un componente del cluster, in cui l'utilizzo effettivo, durante un evento, è aumentato notevolmente rispetto all'intervallo di utilizzo previsto.



 a| 
Squalo
 a| 
Un carico di lavoro definito dall'utente con il più elevato utilizzo di un componente del cluster rispetto a tutti i carichi di lavoro coinvolti in un evento.  Unified Manager identifica i carichi di lavoro degli Shark in base al loro utilizzo di un componente del cluster durante un evento.

|===
I carichi di lavoro su un cluster possono condividere molti dei componenti del cluster, come gli aggregati e la CPU per l'elaborazione di dati e di rete.  Quando un carico di lavoro, ad esempio un volume, aumenta l'utilizzo di un componente del cluster al punto che il componente non riesce a soddisfare in modo efficiente le richieste del carico di lavoro, il componente è in competizione.  Il carico di lavoro che comporta l'utilizzo eccessivo di un componente del cluster è un bullo.  Le vittime sono gli altri carichi di lavoro che condividono tali componenti e le cui prestazioni sono influenzate dal bullo.  Anche le attività derivanti da carichi di lavoro definiti dal sistema, come la deduplicazione o le copie Snapshot, possono degenerare in "bullismo".

Quando Unified Manager rileva un evento, identifica tutti i carichi di lavoro e i componenti del cluster coinvolti, inclusi i carichi di lavoro indesiderato che hanno causato l'evento, il componente del cluster in conflitto e i carichi di lavoro vittima le cui prestazioni sono diminuite a causa dell'aumento dell'attività dei carichi di lavoro indesiderato.

[NOTE]
====
Se Unified Manager non riesce a identificare i carichi di lavoro indesiderabili, invia avvisi solo sui carichi di lavoro vittime e sul componente del cluster coinvolto.

====
Unified Manager è in grado di identificare i carichi di lavoro che sono vittime di carichi di lavoro prepotenti e anche di capire quando questi stessi carichi di lavoro diventano carichi di lavoro prepotenti.  Un carico di lavoro può essere un bullo per se stesso.  Ad esempio, un carico di lavoro ad alte prestazioni che viene limitato da un limite del gruppo di policy determina la limitazione di tutti i carichi di lavoro nel gruppo di policy, incluso se stesso.  Un carico di lavoro che si comporta da bullo o da vittima in un evento di performance in corso potrebbe cambiare il suo ruolo o non partecipare più all'evento.
