---
permalink: performance-checker/concept_components_of_performance_explorer_page.html 
sidebar: sidebar 
keywords: components, performance, explorer, page 
summary: 'La pagina Performance Explorer consente di confrontare le prestazioni di oggetti simili in un cluster, ad esempio tutti i volumi in un cluster.  Ciò è utile quando si risolvono problemi relativi alle prestazioni e si ottimizzano le prestazioni degli oggetti.  È anche possibile confrontare gli oggetti con l"oggetto radice, che rappresenta la base di riferimento rispetto alla quale vengono effettuati altri confronti tra oggetti.' 
---
= Componenti della pagina Performance Explorer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Performance Explorer consente di confrontare le prestazioni di oggetti simili in un cluster, ad esempio tutti i volumi in un cluster.  Ciò è utile quando si risolvono problemi relativi alle prestazioni e si ottimizzano le prestazioni degli oggetti.  È anche possibile confrontare gli oggetti con l'oggetto radice, che rappresenta la base di riferimento rispetto alla quale vengono effettuati altri confronti tra oggetti.

È possibile fare clic sul pulsante *Passa alla visualizzazione Salute* per visualizzare la pagina dei dettagli Salute per questo oggetto.  In alcuni casi è possibile ottenere informazioni importanti sulle impostazioni di configurazione dell'archiviazione per questo oggetto, che potrebbero rivelarsi utili per la risoluzione di un problema.

La pagina Performance Explorer visualizza un elenco di oggetti cluster e i relativi dati sulle prestazioni.  Questa pagina visualizza tutti gli oggetti del cluster dello stesso tipo (ad esempio, volumi e statistiche sulle prestazioni specifiche dell'oggetto) in formato tabellare.  Questa vista fornisce una panoramica efficiente delle prestazioni degli oggetti cluster.

[NOTE]
====
Se in una cella della tabella compare "`N/D`", significa che un valore per quel contatore non è disponibile perché in quel momento non c'è I/O su quell'oggetto.

====
La pagina Performance Explorer contiene i seguenti componenti:

* *Intervallo di tempo*
+
Consente di selezionare un intervallo di tempo per i dati dell'oggetto.

+
È possibile scegliere un intervallo predefinito oppure specificare un intervallo di tempo personalizzato.

* *Visualizza e confronta*
+
Consente di selezionare il tipo di oggetto correlato da visualizzare nella griglia.

+
Le opzioni disponibili dipendono dal tipo di oggetto radice e dai dati disponibili.  È possibile fare clic sull'elenco a discesa Visualizza e confronta per selezionare un tipo di oggetto.  Il tipo di oggetto selezionato viene visualizzato nell'elenco.

* *Filtro*
+
Ti consente di restringere la quantità di dati che ricevi, in base alle tue preferenze.

+
È possibile creare filtri da applicare ai dati dell'oggetto, ad esempio IOPS maggiori di 4.  È possibile aggiungere fino a quattro filtri contemporaneamente.

* *Confronto*
+
Visualizza un elenco degli oggetti selezionati per il confronto con l'oggetto radice.

+
I dati degli oggetti nel riquadro Confronto vengono visualizzati nei grafici Contatore.

* *Visualizza le statistiche in*
+
Per volume e LUN, consente di selezionare se le statistiche vengono visualizzate dopo ogni ciclo di raccolta (impostazione predefinita: 5 minuti) oppure se vengono mostrate come media oraria.  Questa funzionalità consente di visualizzare il grafico della latenza a supporto del programma NetApp "Performance Guarantee".

* *Grafici di contropartita*
+
Visualizza i dati rappresentati graficamente per ogni categoria di prestazioni dell'oggetto.

+
Di solito, per impostazione predefinita vengono visualizzati solo tre o quattro grafici.  Il componente Scegli grafici consente di visualizzare grafici aggiuntivi o di nascondere grafici specifici.  Puoi anche scegliere di mostrare o nascondere la cronologia degli eventi.

* *Cronologia degli eventi*
+
Visualizza gli eventi relativi a prestazioni e stato di salute che si verificano nella sequenza temporale selezionata nel componente Intervallo di tempo.


