---
permalink: performance-checker/concept_performance_incident_analysis_for_metrocluster_configuration.html 
sidebar: sidebar 
keywords: performance, event, analysis, metrocluster, configuration 
summary: 'È possibile utilizzare Unified Manager per analizzare un evento di prestazioni per una configurazione MetroCluster .  È possibile identificare i carichi di lavoro coinvolti nell"evento e rivedere le azioni suggerite per risolverlo.' 
---
= Analisi degli eventi prestazionali per una configurazione MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Unified Manager per analizzare un evento di prestazioni per una configurazione MetroCluster .  È possibile identificare i carichi di lavoro coinvolti nell'evento e rivedere le azioni suggerite per risolverlo.

Gli eventi relativi alle prestazioni MetroCluster potrebbero essere dovuti a carichi di lavoro eccessivi che sfruttano eccessivamente i collegamenti interswitch (ISL) tra i cluster oppure a problemi di integrità dei collegamenti.  Unified Manager monitora ogni cluster in una configurazione MetroCluster in modo indipendente, senza considerare gli eventi relativi alle prestazioni su un cluster partner.

Gli eventi relativi alle prestazioni di entrambi i cluster nella configurazione MetroCluster vengono visualizzati anche nella pagina Dashboard di Unified Manager.  È anche possibile visualizzare le pagine Integrità di Unified Manager per controllare lo stato di ciascun cluster e visualizzarne le relazioni.
