---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: I gruppi di policy QoS adattivi ridimensionano automaticamente un limite massimo o minimo di throughput in base alle dimensioni del volume, mantenendo il rapporto tra IOPS e TB al variare delle dimensioni del volume.  A partire da ONTAP 9.5 è possibile specificare la dimensione del blocco nella policy QoS per applicare contemporaneamente una soglia MB/s. 
---
= Comprendere gli eventi provenienti da policy QoS adattive che hanno una dimensione di blocco definita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I gruppi di policy QoS adattivi ridimensionano automaticamente un limite massimo o minimo di throughput in base alle dimensioni del volume, mantenendo il rapporto tra IOPS e TB al variare delle dimensioni del volume.  A partire da ONTAP 9.5 è possibile specificare la dimensione del blocco nella policy QoS per applicare contemporaneamente una soglia MB/s.

L'assegnazione di una soglia IOPS in una policy QoS adattiva pone un limite solo al numero di operazioni che si verificano in ciascun carico di lavoro.  A seconda della dimensione del blocco impostata sul client che genera i carichi di lavoro, alcuni IOPS includono molti più dati e quindi impongono un carico molto maggiore sui nodi che elaborano le operazioni.

Il valore MB/s per un carico di lavoro viene generato utilizzando la seguente formula:

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
Se un carico di lavoro ha una media di 3.000 IOPS e la dimensione del blocco sul client è impostata su 32 KB, il valore effettivo di MB/s per questo carico di lavoro è 96.  Se lo stesso carico di lavoro ha una media di 3.000 IOPS e la dimensione del blocco sul client è impostata su 48 KB, il valore effettivo di MB/s per questo carico di lavoro è 144.  È possibile notare che il nodo elabora il 50% di dati in più quando la dimensione del blocco è maggiore.

Diamo un'occhiata alla seguente policy QoS adattiva che ha una dimensione di blocco definita e al modo in cui gli eventi vengono attivati in base alla dimensione di blocco impostata sul client.

Crea una policy e imposta la velocità massima su 2.500 IOPS/TB con una dimensione del blocco di 32 KB.  In questo modo la soglia MB/s viene impostata di fatto su 80 MB/s ((2500 IOPS * 32 KB) / 1000) per un volume con una capacità utilizzata di 1 TB.  Si noti che Unified Manager genera un evento di avviso quando il valore della velocità effettiva è inferiore del 10% rispetto alla soglia definita.  Gli eventi vengono generati nelle seguenti situazioni:

|===
| Capacità utilizzata 2+| L'evento viene generato quando la velocità effettiva supera questo numero di ... 


|  | IOPS | MB/s 


 a| 
1 TB
 a| 
2.250 IOPS
 a| 
72 MB/s



 a| 
2 TB
 a| 
4.500 IOPS
 a| 
144 MB/s



 a| 
5 TB
 a| 
11.250 IOPS
 a| 
360 MB/s

|===
Se il volume utilizza 2 TB di spazio disponibile, gli IOPS sono 4.000 e la dimensione del blocco QoS è impostata su 32 KB sul client, la velocità effettiva MB/ps è 128 MB/s ((4.000 IOPS * 32 KB) / 1000).  In questo scenario non viene generato alcun evento perché sia 4.000 IOPS che 128 MB/s sono al di sotto della soglia per un volume che utilizza 2 TB di spazio.

Se il volume utilizza 2 TB di spazio disponibile, gli IOPS sono 4.000 e la dimensione del blocco QoS è impostata su 64 KB sul client, la velocità effettiva MB/s è 256 MB/s ((4.000 IOPS * 64 KB) / 1000).  In questo caso i 4.000 IOPS non generano un evento, ma il valore MB/s di 256 MB/s è superiore alla soglia di 144 MB/s e viene generato un evento.

Per questo motivo, quando un evento viene attivato in base a una violazione di MB/s per una policy QoS adattiva che include la dimensione del blocco, nella sezione Diagnosi di sistema della pagina Dettagli evento viene visualizzato un grafico MB/s.  Se l'evento viene attivato in base a una violazione IOPS per la policy QoS adattiva, nella sezione Diagnosi di sistema viene visualizzato un grafico IOPS.  Se si verifica una violazione sia per IOPS che per MB/s, riceverai due eventi.

Per ulteriori informazioni sulla regolazione delle impostazioni QoS, vedere https://docs.netapp.com/us-en/ontap/performance-admin/index.html["Panoramica sulla gestione delle prestazioni"] .
