---
permalink: performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html 
sidebar: sidebar 
keywords: introduction, active iq, unified manager, performance, monitor 
summary: 'Active IQ Unified Manager (in precedenza OnCommand Unified Manager) offre funzionalità di monitoraggio delle prestazioni e analisi delle cause principali degli eventi per i sistemi che eseguono il software NetApp ONTAP .' 
---
= Introduzione al monitoraggio delle prestazioni Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager (in precedenza OnCommand Unified Manager) offre funzionalità di monitoraggio delle prestazioni e analisi delle cause principali degli eventi per i sistemi che eseguono il software NetApp ONTAP .

Unified Manager ti aiuta a identificare i carichi di lavoro che utilizzano eccessivamente i componenti del cluster e riducono le prestazioni degli altri carichi di lavoro sul cluster.  Definendo criteri di soglia delle prestazioni è anche possibile specificare valori massimi per determinati contatori delle prestazioni, in modo che vengano generati eventi quando la soglia viene superata.  Unified Manager ti avvisa di questi eventi relativi alle prestazioni, in modo che tu possa adottare misure correttive e riportare le prestazioni ai normali livelli operativi.  È possibile visualizzare e analizzare gli eventi nell'interfaccia utente di Unified Manager.

Unified Manager monitora le prestazioni di due tipi di carichi di lavoro:

* Carichi di lavoro definiti dall'utente
+
Questi carichi di lavoro sono costituiti da volumi FlexVol e volumi FlexGroup creati nel cluster.

* Carichi di lavoro definiti dal sistema
+
Questi carichi di lavoro sono costituiti da attività di sistema interne.


