---
permalink: performance-checker/concept_options_for_improving_workload_performance_from_client.html 
sidebar: sidebar 
keywords: options, improving, workload, performance, client-side 
summary: 'È possibile controllare i carichi di lavoro dei client, come applicazioni o database, che inviano I/O ai volumi coinvolti in un evento di prestazioni per determinare se una modifica sul lato client potrebbe correggere l"evento.' 
---
= Opzioni per migliorare le prestazioni del carico di lavoro dal lato client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare i carichi di lavoro dei client, come applicazioni o database, che inviano I/O ai volumi coinvolti in un evento di prestazioni per determinare se una modifica sul lato client potrebbe correggere l'evento.

Quando i client connessi ai volumi di un cluster aumentano le loro richieste di I/O, il cluster deve lavorare di più per soddisfare la domanda.  Se si sa quali client hanno un numero elevato di richieste di I/O su un particolare volume del cluster, è possibile migliorare le prestazioni del cluster regolando il numero di client che accedono al volume o riducendo la quantità di I/O sul volume.  È anche possibile applicare o aumentare un limite al gruppo di policy QoS di cui il volume è membro.

È possibile analizzare i client e le relative applicazioni per determinare se i client inviano più I/O del solito, il che potrebbe causare conflitti su un componente del cluster.  Nella pagina Dettagli evento, la sezione Diagnosi di sistema visualizza i carichi di lavoro del volume principale che utilizzano il componente in competizione.  Se si sa quale client sta accedendo a un volume specifico, è possibile andare al client per determinare se l'hardware del client o un'applicazione non funziona come previsto o sta eseguendo più lavoro del solito.

In una configurazione MetroCluster , le richieste di scrittura su un volume su un cluster locale vengono replicate su un volume sul cluster remoto.  Mantenere sincronizzato il volume di origine sul cluster locale con il volume di destinazione sul cluster remoto può anche aumentare la richiesta di entrambi i cluster nella configurazione MetroCluster .  Riducendo le richieste di scrittura su questi volumi mirror, i cluster possono eseguire meno operazioni di sincronizzazione, riducendo così l'impatto sulle prestazioni di altri carichi di lavoro.
