---
permalink: performance-checker/concept_add_disks_and_reallocate_data.html 
sidebar: sidebar 
keywords: add, disks, reallocate, data 
summary: È possibile aggiungere dischi a un aggregato per aumentarne la capacità di archiviazione e le prestazioni.  Dopo aver aggiunto i dischi, noterai un miglioramento nelle prestazioni di lettura solo dopo aver riallocato i dati tra i dischi aggiunti. 
---
= Aggiungi dischi e rialloca i dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere dischi a un aggregato per aumentarne la capacità di archiviazione e le prestazioni.  Dopo aver aggiunto i dischi, noterai un miglioramento nelle prestazioni di lettura solo dopo aver riallocato i dati tra i dischi aggiunti.

È possibile utilizzare queste istruzioni quando Unified Manager ha ricevuto eventi aggregati attivati da soglie dinamiche o da soglie di prestazioni definite dal sistema:

* Quando si riceve un evento di soglia dinamica, nella pagina Dettagli evento, l'icona del componente cluster che rappresenta l'aggregato in competizione è evidenziata in rosso.
+
Sotto l'icona, tra parentesi, è riportato il nome dell'aggregato, che identifica l'aggregato a cui è possibile aggiungere dischi.

* Quando si riceve un evento soglia definito dal sistema, nella pagina Dettagli evento, il testo della descrizione dell'evento elenca il nome dell'aggregato che presenta il problema.
+
È possibile aggiungere dischi e riallocare i dati su questo aggregato.



I dischi aggiunti all'aggregato devono già esistere nel cluster.  Se il cluster non dispone di dischi aggiuntivi, potrebbe essere necessario contattare l'amministratore o acquistarne altri.  È possibile utilizzare ONTAP System Manager o i comandi ONTAP per aggiungere dischi a un aggregato.

[NOTE]
====
È necessario riallocare i dati solo quando si utilizzano aggregati HDD e Flash Pool.  Non riallocare i dati sugli aggregati SSD o FabricPool .

====