---
permalink: performance-checker/concept_understand_counter_charts.html 
sidebar: sidebar 
keywords: understand, counter, charts 
summary: 'I grafici nel riquadro Grafici contatore consentono di visualizzare e confrontare i dati sulle prestazioni dell"oggetto radice e degli oggetti aggiunti dalla griglia degli oggetti correlati.  Ciò può aiutarti a comprendere le tendenze delle prestazioni e a isolare e risolvere i problemi di prestazioni.' 
---
= Comprendere i grafici dei contatori
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I grafici nel riquadro Grafici contatore consentono di visualizzare e confrontare i dati sulle prestazioni dell'oggetto radice e degli oggetti aggiunti dalla griglia degli oggetti correlati.  Ciò può aiutarti a comprendere le tendenze delle prestazioni e a isolare e risolvere i problemi di prestazioni.

I grafici dei contatori visualizzati per impostazione predefinita sono Eventi, Latenza, IOPS e MBps.  I grafici facoltativi che puoi scegliere di visualizzare sono Utilizzo, Capacità di prestazioni utilizzata, IOPS disponibili, IOPS/TB e Rapporto di mancata memorizzazione nella cache.  Inoltre, è possibile scegliere di visualizzare i valori totali o i valori di ripartizione per i grafici Latenza, IOPS, MBps e Capacità di prestazioni utilizzata.

Per impostazione predefinita, Performance Explorer visualizza determinati grafici dei contatori, indipendentemente dal fatto che l'oggetto di archiviazione li supporti tutti o meno.  Quando un contatore non è supportato, il grafico del contatore è vuoto e il messaggio `Not applicable for <object>` viene visualizzato.

I grafici mostrano le tendenze delle prestazioni per l'oggetto radice e per tutti gli oggetti selezionati nel riquadro Confronto.  I dati in ogni grafico sono organizzati come segue:

* *asse X*
+
Visualizza il periodo di tempo specificato.  Se non hai specificato un intervallo di tempo, l'impostazione predefinita è il periodo di 72 ore precedente.

* *Asse Y*
+
Visualizza le unità di misura specifiche dell'oggetto o degli oggetti selezionati.



I colori delle linee di tendenza corrispondono al colore del nome dell'oggetto visualizzato nel riquadro Confronto.  È possibile posizionare il cursore su un punto di qualsiasi linea di tendenza per visualizzare i dettagli relativi a tempo e valore per quel punto.

Se si desidera analizzare un periodo di tempo specifico all'interno di un grafico, è possibile utilizzare uno dei seguenti metodi:

* Utilizzare il pulsante *<* per espandere il riquadro Grafici contatore in modo che copra l'intera larghezza della pagina.
* Utilizzare il cursore (quando si trasforma in una lente di ingrandimento) per selezionare una porzione dell'intervallo di tempo nel grafico per mettere a fuoco e ingrandire quell'area.  È possibile fare clic su Reimposta zoom grafico per riportare il grafico all'intervallo di tempo predefinito.
* Utilizzare il pulsante *Zoom vista* per visualizzare un grande grafico a contatore singolo contenente dettagli estesi e indicatori di soglia.


[NOTE]
====
Occasionalmente si verificano delle lacune nelle linee di tendenza.  Le lacune indicano che Unified Manager non è riuscito a raccogliere i dati sulle prestazioni dal sistema di archiviazione oppure che Unified Manager potrebbe essere inattivo.

====