---
permalink: performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html 
sidebar: sidebar 
keywords: types, workloads, monitored, unified manager 
summary: 'È possibile utilizzare Unified Manager per monitorare le prestazioni di due tipi di carichi di lavoro: definiti dall"utente e definiti dal sistema.' 
---
= Tipi di carichi di lavoro monitorati da Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Unified Manager per monitorare le prestazioni di due tipi di carichi di lavoro: definiti dall'utente e definiti dal sistema.

* *_Carichi di lavoro definiti dall'utente_*
+
La velocità di I/O dalle applicazioni al cluster.  Si tratta di processi coinvolti nelle richieste di lettura e scrittura.  Un volume, una LUN, una condivisione NFS, una condivisione SMB/CIFS e un carico di lavoro sono carichi di lavoro definiti dall'utente.

+
[NOTE]
====
Unified Manager monitora solo l'attività del carico di lavoro sul cluster.  Non monitora le applicazioni, i client o i percorsi tra le applicazioni e il cluster.

====
+
Se una o più delle seguenti condizioni sono vere per un carico di lavoro, questo non può essere monitorato da Unified Manager:

+
** Si tratta di una copia di protezione dei dati (DP) in modalità di sola lettura.  (I volumi DP vengono monitorati per il traffico generato dall'utente.)
** Si tratta di un clone di dati offline.
** Si tratta di un volume speculare in una configurazione MetroCluster .


* *_Carichi di lavoro definiti dal sistema_*
+
I processi interni coinvolti nell'efficienza di archiviazione, nella replicazione dei dati e nello stato del sistema, tra cui:

+
** Efficienza di archiviazione, come la deduplicazione
** Integrità del disco, che include la ricostruzione RAID, la pulizia del disco e così via
** Replicazione dei dati, come le copie SnapMirror
** Attività di gestione
** Stato del file system, che include varie attività WAFL
** Scanner del file system, come la scansione WAFL
** Copia offload, ad esempio operazioni di efficienza di archiviazione scaricate dagli host VMware
** Stato di salute del sistema, come spostamenti di volume, compressione dei dati e così via
** Volumi non monitorati




I dati sulle prestazioni per i carichi di lavoro definiti dal sistema vengono visualizzati nell'interfaccia utente grafica solo quando il componente cluster utilizzato da tali carichi di lavoro è in competizione.  Ad esempio, non è possibile cercare il nome di un carico di lavoro definito dal sistema per visualizzarne i dati sulle prestazioni nell'interfaccia utente grafica.
