---
permalink: performance-checker/concept_counter_charts_zoom_view.html 
sidebar: sidebar 
keywords: counter, charts, zoom, view 
summary: I grafici dei contatori forniscono una vista zoom che consente di ingrandire i dettagli delle prestazioni nel periodo di tempo specificato.  Ciò consente di visualizzare i dettagli delle prestazioni e gli eventi con una granularità molto più elevata, il che è utile quando si risolvono problemi di prestazioni. 
---
= Visualizzazione zoom dei grafici dei contatori
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I grafici dei contatori forniscono una vista zoom che consente di ingrandire i dettagli delle prestazioni nel periodo di tempo specificato.  Ciò consente di visualizzare i dettagli delle prestazioni e gli eventi con una granularità molto più elevata, il che è utile quando si risolvono problemi di prestazioni.

Quando vengono visualizzati in modalità Zoom, alcuni grafici di ripartizione forniscono informazioni aggiuntive rispetto a quelle visualizzate quando il grafico non è in modalità Zoom.  Ad esempio, le pagine Zoom View dei grafici di ripartizione IOPS, IOPS/TB e MBps mostrano i valori dei criteri QoS per volumi e LUN se sono stati impostati in ONTAP.

[NOTE]
====
Per i criteri di soglia delle prestazioni definiti dal sistema, nell'elenco *Criteri* sono disponibili solo i criteri "`Risorse nodo sovrautilizzate`" e "`Limite di throughput QoS violato`".  Al momento, gli altri criteri di soglia definiti dal sistema non sono disponibili.

====