---
permalink: performance-checker/concept_check_for_client_or_network_issues.html 
sidebar: sidebar 
keywords: check, client, network, issues 
summary: 'Quando i client connessi ai volumi di un cluster aumentano le loro richieste di I/O, il cluster deve lavorare di più per soddisfare la domanda.  L"aumento della domanda sul cluster può mettere in competizione un componente, aumentare la latenza dei carichi di lavoro che lo utilizzano e attivare un evento in Unified Manager.' 
---
= Verificare la presenza di problemi con il client o con la rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando i client connessi ai volumi di un cluster aumentano le loro richieste di I/O, il cluster deve lavorare di più per soddisfare la domanda.  L'aumento della domanda sul cluster può mettere in competizione un componente, aumentare la latenza dei carichi di lavoro che lo utilizzano e attivare un evento in Unified Manager.

Nella pagina Dettagli evento, la sezione Diagnosi di sistema visualizza i carichi di lavoro del volume principale che utilizzano il componente in competizione.  Se si sa quale client sta accedendo a un volume specifico, è possibile andare al client per determinare se l'hardware del client o un'applicazione non funziona come previsto o sta eseguendo più lavoro del solito.  Potrebbe essere necessario contattare l'amministratore del client o il fornitore dell'applicazione per ricevere assistenza.

È possibile controllare l'infrastruttura di rete per determinare se sono presenti problemi hardware, colli di bottiglia o carichi di lavoro concorrenti che potrebbero aver causato un rallentamento delle richieste di I/O tra il cluster e i client connessi.  Potrebbe essere necessario contattare l'amministratore di rete per assistenza.
