---
permalink: performance-checker/reference_performance_dashboard_cluster_banner_messages.html 
sidebar: sidebar 
keywords: performance, banner, messages, descriptions 
summary: 'Unified Manager può visualizzare messaggi banner nella pagina Notifiche (dalla campana delle notifiche) per avvisarti di problemi di stato per un cluster specifico.' 
---
= Messaggi e descrizioni dei banner sulle prestazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager può visualizzare messaggi banner nella pagina Notifiche (dalla campana delle notifiche) per avvisarti di problemi di stato per un cluster specifico.

|===
| Messaggio banner | Descrizione | Risoluzione 


 a| 
`No performance data is being collected from cluster _cluster_name_. Restart Unified Manager to correct this issue.`
 a| 
Il servizio di raccolta Unified Manager è stato arrestato e non vengono raccolti dati sulle prestazioni da alcun cluster.
 a| 
Riavviare Unified Manager per correggere il problema.  Se il problema persiste, contattare l'assistenza tecnica.



 a| 
`More than x hour(s) of historical data is being collected from cluster _cluster_name_. Current data collections will start after all historical data is collected.`
 a| 
È attualmente in esecuzione un ciclo di raccolta della continuità dei dati per recuperare i dati sulle prestazioni al di fuori del ciclo di raccolta delle prestazioni del cluster in tempo reale.
 a| 
Non è richiesta alcuna azione. I dati sulle prestazioni attuali saranno raccolti una volta completato il ciclo di raccolta della continuità dei dati.

Un ciclo di raccolta della continuità dei dati viene eseguito quando viene aggiunto un nuovo cluster o quando Unified Manager non è riuscito a raccogliere i dati sulle prestazioni correnti per qualche motivo.

|===