---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: Alcuni contatori di prestazioni comuni, come IOPS e MB/s, possono avere soglie impostate per tutti gli oggetti di archiviazione.  Esistono altri contatori per i quali è possibile impostare soglie solo per determinati oggetti di archiviazione. 
---
= Quali contatori delle prestazioni possono essere monitorati utilizzando le soglie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alcuni contatori di prestazioni comuni, come IOPS e MB/s, possono avere soglie impostate per tutti gli oggetti di archiviazione.  Esistono altri contatori per i quali è possibile impostare soglie solo per determinati oggetti di archiviazione.



== Contatori di prestazioni disponibili

|===
| Oggetto di archiviazione | Contatore delle prestazioni | Descrizione 


 a| 
Grappolo
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dal cluster al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questo cluster al secondo.



 a| 
Nodo
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dal nodo al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questo nodo al secondo.



 a| 
Latenza
 a| 
Numero medio di millisecondi impiegati dal nodo per rispondere alle richieste dell'applicazione.



 a| 
Utilizzo
 a| 
Percentuale media della CPU e della RAM del nodo utilizzata.



 a| 
Capacità di prestazione utilizzata
 a| 
Percentuale media della capacità di prestazione consumata dal nodo.



 a| 
Capacità di prestazione utilizzata - Acquisizione
 a| 
Percentuale media della capacità di prestazione consumata dal nodo, più la capacità di prestazione del nodo partner.



 a| 
Aggregato
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dall'aggregato al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questo aggregato al secondo.



 a| 
Latenza
 a| 
Numero medio di millisecondi impiegati dall'aggregato per rispondere alle richieste dell'applicazione.



 a| 
Utilizzo
 a| 
Percentuale media dei dischi dell'aggregato utilizzati.



 a| 
Capacità di prestazione utilizzata
 a| 
Percentuale media della capacità prestazionale consumata dall'aggregato.



 a| 
VM di archiviazione
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dall'SVM al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questa SVM al secondo.



 a| 
Latenza
 a| 
Numero medio di millisecondi impiegati dall'SVM per rispondere alle richieste dell'applicazione.



 a| 
Volume
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dal volume al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questo volume al secondo.



 a| 
Latenza
 a| 
Numero medio di millisecondi impiegati dal volume per rispondere alle richieste dell'applicazione.



 a| 
Rapporto di mancata memorizzazione nella cache
 a| 
Percentuale media di richieste di lettura da applicazioni client restituite dal volume anziché dalla cache.



 a| 
LUN
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dalla LUN al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questa LUN al secondo.



 a| 
Latenza
 a| 
Numero medio di millisecondi impiegati dalla LUN per rispondere alle richieste dell'applicazione.



 a| 
Spazio dei nomi
 a| 
IOPS
 a| 
Numero medio di operazioni di input/output elaborate dallo spazio dei nomi al secondo.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questo namespace al secondo.



 a| 
Latenza
 a| 
Numero medio di millisecondi impiegati dallo spazio dei nomi per rispondere alle richieste dell'applicazione.



 a| 
Porta
 a| 
Utilizzo della larghezza di banda
 a| 
Percentuale media della larghezza di banda disponibile della porta utilizzata.



 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questa porta al secondo.



 a| 
Interfaccia di rete (LIF)
 a| 
MB/s
 a| 
Numero medio di megabyte di dati trasferiti da e verso questo LIF al secondo.

|===