---
permalink: performance-checker/task_view_performance_threshold_policies.html 
sidebar: sidebar 
keywords: view, performance, threshold, policies 
summary: È possibile visualizzare tutti i criteri di soglia delle prestazioni attualmente definiti dalla pagina Soglie delle prestazioni. 
---
= Visualizza i criteri di soglia delle prestazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare tutti i criteri di soglia delle prestazioni attualmente definiti dalla pagina Soglie delle prestazioni.

L'elenco delle policy di soglia è ordinato alfabeticamente in base al nome della policy e include policy per tutti i tipi di oggetti di archiviazione.  È possibile fare clic sull'intestazione di una colonna per ordinare le policy in base a quella colonna.  Se stai cercando una policy specifica, utilizza i meccanismi di filtro e ricerca per restringere l'elenco delle policy di soglia visualizzate nell'elenco dell'inventario.

È possibile passare il cursore sul Nome della policy e sul Nome della condizione per visualizzare i dettagli di configurazione della policy.  Inoltre, è possibile utilizzare i pulsanti forniti per creare, clonare, modificare ed eliminare criteri di soglia definiti dall'utente.

.Fare un passo
. Nel riquadro di navigazione a sinistra, seleziona *Soglie eventi* > *Prestazioni*.
+
Viene visualizzata la pagina Soglie di prestazione.


