---
permalink: performance-checker/task_move_workloads_to_another_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, another, node, different, ha pair 
summary: È possibile utilizzare Unified Manager per identificare un aggregato su un nodo in una coppia HA diversa che sia meno occupata della coppia HA in cui sono attualmente in esecuzione i carichi di lavoro.  È quindi possibile spostare i volumi selezionati negli aggregati sulla nuova coppia HA.  Spostando i carichi di lavoro ad alte prestazioni su un aggregato su un nodo meno trafficato, i carichi di lavoro su entrambi i nodi possono funzionare in modo più efficiente. 
---
= Spostare i carichi di lavoro su un altro nodo in una coppia HA diversa
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Unified Manager per identificare un aggregato su un nodo in una coppia HA diversa che sia meno occupata della coppia HA in cui sono attualmente in esecuzione i carichi di lavoro.  È quindi possibile spostare i volumi selezionati negli aggregati sulla nuova coppia HA.  Spostando i carichi di lavoro ad alte prestazioni su un aggregato su un nodo meno trafficato, i carichi di lavoro su entrambi i nodi possono funzionare in modo più efficiente.

.Prima di iniziare
* È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.
* Il cluster deve essere composto da almeno due coppie HA; non è possibile utilizzare questo processo di ripristino se nel cluster è presente una sola coppia HA.
* È necessario aver registrato i nomi dei due nodi nella coppia HA che attualmente presentano problemi di prestazioni.
* È necessario aver registrato la data e l'ora in cui i nodi hanno ricevuto l'evento di prestazione.
* Unified Manager deve aver raccolto e analizzato almeno un mese di dati sulle prestazioni.


Questi passaggi ti aiutano a identificare le seguenti risorse in modo da poter spostare carichi di lavoro ad alte prestazioni su un nodo meno utilizzato su una coppia HA diversa:

* I nodi in una coppia HA diversa sullo stesso cluster che sono meno utilizzati
* Gli aggregati sui nuovi nodi che sono meno utilizzati
* I volumi più performanti sui nodi attuali


.Passi
. Identificare i nodi che fanno parte di una diversa coppia HA sullo stesso cluster:
+
.. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Cluster* e selezionare *Prestazioni* > *Tutti i cluster* dal menu Visualizza.
+
Viene visualizzata la vista Prestazioni: tutti i cluster.

.. Fare clic sul numero nel campo *Conteggio nodi* per il cluster corrente.
+
Viene visualizzata la vista Prestazioni: Tutti i nodi.

.. Annotare i nomi dei nodi che si trovano in coppie HA diverse dalla coppia HA che attualmente presenta il problema di prestazioni.


. Identificare un nodo nella nuova coppia HA che sia il meno utilizzato:
+
.. Fare clic sulla colonna *Utilizzo* per ordinare i nodi in base al loro utilizzo minore.
+
È anche possibile identificare i nodi che hanno la maggiore *Capacità libera*.  Viene fornito un elenco di potenziali nodi su cui potresti voler spostare i carichi di lavoro.

.. Annotare il nome del nodo su cui si desidera spostare i carichi di lavoro.


. Identificare un aggregato sul nuovo nodo che sia il meno utilizzato:
+
.. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Aggregati* e selezionare *Prestazioni* > *Tutti gli aggregati* dal menu Visualizza.
+
Viene visualizzata la vista Prestazioni: Tutti gli aggregati.

.. Fare clic su *Filtro*, selezionare *Nodo* dal menu a discesa a sinistra, digitare il nome del nodo nel campo di testo, quindi fare clic su *Applica filtro*.
+
Viene nuovamente visualizzata la vista Prestazioni: tutti gli aggregati con l'elenco degli aggregati disponibili su questo nodo.

.. Fare clic sulla colonna *Utilizzo* per ordinare gli aggregati in base al loro utilizzo minore.
+
È anche possibile identificare gli aggregati che hanno la maggiore *Capacità libera*.  Viene fornito un elenco di potenziali aggregati su cui potresti voler spostare i carichi di lavoro.

.. Annotare il nome dell'aggregato su cui si desidera spostare i carichi di lavoro.


. Identificare i carichi di lavoro ad alte prestazioni dai nodi che hanno ricevuto l'evento:
+
.. Torna alla pagina dei dettagli dell'evento.
.. Nel campo *Volumi interessati*, fare clic sul collegamento per il numero di volumi per il primo nodo.
+
La vista Prestazioni: Tutti i volumi viene visualizzata con un elenco filtrato dei volumi su quel nodo.

.. Fare clic sulla colonna *Capacità totale* per ordinare i volumi in base allo spazio allocato più grande.
+
Viene fornito un elenco di potenziali volumi che potresti voler spostare.

.. Annotare i nomi dei volumi che si desidera spostare e i nomi degli aggregati correnti su cui risiedono.
.. Eseguire i passaggi 4c e 4d per il secondo nodo che faceva parte di questo evento per identificare anche i possibili volumi che si desidera spostare da quel nodo.


. Sposta i volumi sugli aggregati identificati come poco utilizzati sul nuovo nodo.
+
È possibile eseguire l'operazione di spostamento utilizzando ONTAP System Manager, OnCommand Workflow Automation, i comandi ONTAP o una combinazione di questi strumenti.



Dopo alcuni giorni, controlla se stai ricevendo lo stesso tipo di eventi da questo nodo o aggregato.
