---
permalink: performance-checker/task_configure_connection_between_um_server_and_external_data_provider.html 
sidebar: sidebar 
keywords: configuring, connection, unified manager, server, external, data, provider 
summary: 'Unified Manager può inviare dati sulle prestazioni del cluster a un server esterno.  È possibile specificare il tipo di dati statistici da inviare e l"intervallo di invio dei dati.' 
---
= Configurare una connessione da un server Unified Manager a un provider di dati esterno
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager può inviare dati sulle prestazioni del cluster a un server esterno.  È possibile specificare il tipo di dati statistici da inviare e l'intervallo di invio dei dati.

.Prima di iniziare
* È necessario disporre di un ID utente autorizzato per accedere alla console di manutenzione del server Unified Manager.
* È necessario disporre delle seguenti informazioni sul fornitore di dati esterno:
+
** Nome del server o indirizzo IP (IPv4 o IPv6)
** Porta predefinita del server (se non si utilizza la porta predefinita 2003)


* È necessario aver configurato il server remoto e il software di terze parti in modo che possano ricevere dati statistici dal server Unified Manager.
* Devi sapere quale gruppo di statistiche vuoi inviare:
+
** PERFORMANCE_INDICATOR: statistiche del monitoraggio delle prestazioni
** RESOURCE_UTILIZATION: statistiche di utilizzo delle risorse e monitoraggio delle prestazioni
** DRILL_DOWN: Tutte le statistiche


* È necessario conoscere l'intervallo di tempo in cui si desidera trasmettere le statistiche: 5, 10 o 15 minuti
+
Per impostazione predefinita, Unified Manager raccoglie le statistiche a intervalli di 5 minuti.  Se si imposta l'intervallo di trasmissione su 10 (o 15) minuti, la quantità di dati inviata durante ogni trasmissione è due (o tre) volte maggiore rispetto all'intervallo predefinito di 5 minuti.

+
[NOTE]
====
Se si modifica l'intervallo di raccolta delle prestazioni di Unified Manager a 10 o 15 minuti, è necessario modificare l'intervallo di trasmissione in modo che sia uguale o maggiore dell'intervallo di raccolta di Unified Manager.

====


È possibile configurare una connessione tra un server Unified Manager e un server provider di dati esterno.

.Passi
. Accedere come utente addetto alla manutenzione alla console di manutenzione del server Unified Manager.
+
Vengono visualizzati i prompt della console di manutenzione di Unified Manager.

. Nella console di manutenzione, digitare il numero dell'opzione di menu *Fornitore di dati esterno*.
+
Viene visualizzato il menu Connessione al server esterno.

. Digitare il numero dell'opzione di menu *Aggiungi/Modifica connessione server*.
+
Vengono visualizzate le informazioni sulla connessione corrente al server.

. Quando richiesto, digitare `*y*` per continuare.
. Quando richiesto, immettere l'indirizzo IP o il nome del server di destinazione e le informazioni sulla porta del server (se diversa dalla porta predefinita 2003).
. Quando richiesto, digitare `*y*` per verificare che le informazioni inserite siano corrette.
. Premere un tasto qualsiasi per tornare al menu Connessione server esterno.
. Digitare il numero dell'opzione di menu *Modifica configurazione server*.
+
Vengono visualizzate le informazioni sulla configurazione corrente del server.

. Quando richiesto, digitare `*y*` per continuare.
. Quando richiesto, immettere il tipo di statistiche da inviare, l'intervallo di tempo in cui inviare le statistiche e se si desidera abilitare la trasmissione delle statistiche ora:
+
|===
| Per.. | Entra... 


 a| 
ID gruppo statistiche
 a| 
`*0*`- PERFORMANCE_INDICATOR (predefinito)

`*1*`- UTILIZZO_RISORSE

`*2*`- DRILL_DOWN



 a| 
Etichetta del fornitore
 a| 
Nome descrittivo per la cartella in cui verranno archiviate le statistiche sul server esterno.  "`netapp-performance`" è il nome predefinito, ma è possibile immettere un altro valore.

Utilizzando la notazione puntata è possibile definire una struttura gerarchica delle cartelle.  Ad esempio, inserendo `*stats.performance.netapp*` le statistiche si troveranno in *stats* > *performance* > *netapp*.



 a| 
Intervallo di trasmissione
 a| 
`*5*`(predefinito), `*10*` , O `*15*` minuti



 a| 
Abilita/disabilita
 a| 
`*0*`- Disabilita

`*1*`- Abilita (predefinito)

|===
. Quando richiesto, digitare `*y*` per verificare che le informazioni inserite siano corrette.
. Premere un tasto qualsiasi per tornare al menu Connessione server esterno.
. Tipo `*x*` per uscire dalla console di manutenzione.


Dopo aver configurato la connessione, i dati sulle prestazioni selezionati vengono inviati al server di destinazione nell'intervallo di tempo specificato.  Ci vogliono alcuni minuti prima che le metriche inizino ad apparire nello strumento esterno.  Potrebbe essere necessario aggiornare il browser per visualizzare le nuove metriche nella gerarchia delle metriche.
