---
permalink: performance-checker/task_identify_shark_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, shark workloads, involved, dynamic, performance, event 
summary: 'In Unified Manager è possibile identificare quali carichi di lavoro presentano la deviazione più elevata nell"utilizzo per un componente di archiviazione in competizione.  L"identificazione di questi carichi di lavoro aiuta a stabilire se è opportuno spostarli in un cluster meno utilizzato.' 
---
= Identificare i carichi di lavoro degli squali coinvolti in un evento di performance dinamica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager è possibile identificare quali carichi di lavoro presentano la deviazione più elevata nell'utilizzo per un componente di archiviazione in competizione.  L'identificazione di questi carichi di lavoro aiuta a stabilire se è opportuno spostarli in un cluster meno utilizzato.

.Prima di iniziare
* È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.
* Ci sono eventi dinamici di performance nuovi, riconosciuti o obsoleti.


La pagina Dettagli evento visualizza un elenco dei carichi di lavoro definiti dall'utente e dal sistema, classificati in base al maggiore utilizzo del componente o al maggiore impatto dell'evento.  I valori si basano sui picchi identificati da Unified Manager quando ha rilevato e analizzato per l'ultima volta l'evento.

.Passi
. Visualizza la pagina *Dettagli evento* per visualizzare le informazioni sull'evento.
. Nei grafici Latenza del carico di lavoro e Attività del carico di lavoro, seleziona *Carichi di lavoro Shark*.
. Passa il cursore sui grafici per visualizzare i principali carichi di lavoro definiti dall'utente che influiscono sul componente e il nome del carico di lavoro Shark.

