---
permalink: performance-checker/task_analyze_performance_incident_in_metrocluster.html 
sidebar: sidebar 
keywords: analyzing, dynamic, performance, event, remote, cluster, metrocluster, configuration 
summary: 'È possibile utilizzare Unified Manager per analizzare gli eventi di prestazioni dinamiche su un cluster remoto in una configurazione MetroCluster .  L"analisi consente di determinare se un evento sul cluster remoto ha causato un evento sul cluster partner.' 
---
= Analizza un evento di prestazioni dinamiche per un cluster remoto su una configurazione MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Unified Manager per analizzare gli eventi di prestazioni dinamiche su un cluster remoto in una configurazione MetroCluster .  L'analisi consente di determinare se un evento sul cluster remoto ha causato un evento sul cluster partner.

.Prima di iniziare
* È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver analizzato un evento di prestazioni su un cluster locale in una configurazione MetroCluster e ottenuto il tempo di rilevamento dell'evento.
* È necessario aver verificato lo stato del cluster locale e del cluster partner coinvolto nell'evento di prestazione e aver ottenuto il nome del cluster partner.


.Passi
. Accedi all'istanza di Unified Manager che monitora il cluster partner.
. Nel riquadro di navigazione a sinistra, fare clic su *Eventi* per visualizzare l'elenco degli eventi.
. Dal selettore *Intervallo di tempo*, seleziona *Ultima ora*, quindi fai clic su *Applica intervallo*.
. Nel selettore *Filtro*, seleziona *Cluster* dal menu a discesa a sinistra, digita il nome del cluster partner nel campo di testo, quindi fai clic su *Applica filtro*.
+
Se non si sono verificati eventi per il cluster selezionato nell'ultima ora, ciò indica che il cluster non ha riscontrato problemi di prestazioni durante il periodo in cui l'evento è stato rilevato sul suo partner.

. Se nel cluster selezionato sono stati rilevati eventi nell'ultima ora, confrontare l'ora di rilevamento dell'evento con l'ora di rilevamento dell'evento per l'evento nel cluster locale.
+
Se questi eventi comportano carichi di lavoro eccessivi che causano conflitti sul componente di elaborazione dati, uno o più di questi carichi eccessivi potrebbero aver causato l'evento sul cluster locale.  Puoi cliccare sull'evento per analizzarlo e rivedere le azioni suggerite per risolverlo nella pagina dei dettagli dell'evento.

+
Se questi eventi non comportano carichi di lavoro eccessivi, non hanno causato l'evento di prestazioni sul cluster locale.


