---
permalink: performance-checker/task_respond_to_system_defined_node_resources_overutilized.html 
sidebar: sidebar 
keywords: node, resources, overutilized, performance, events 
summary: 'Unified Manager genera eventi di avviso di sovrautilizzo delle risorse del nodo quando un singolo nodo funziona oltre i limiti della sua efficienza operativa, influenzando potenzialmente le latenze del carico di lavoro.  Questi eventi definiti dal sistema offrono l"opportunità di correggere potenziali problemi di prestazioni prima che molti carichi di lavoro siano interessati dalla latenza.' 
---
= Rispondere agli eventi di prestazioni di sovrautilizzo delle risorse del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager genera eventi di avviso di sovrautilizzo delle risorse del nodo quando un singolo nodo funziona oltre i limiti della sua efficienza operativa, influenzando potenzialmente le latenze del carico di lavoro.  Questi eventi definiti dal sistema offrono l'opportunità di correggere potenziali problemi di prestazioni prima che molti carichi di lavoro siano interessati dalla latenza.

.Prima di iniziare
* È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.
* Devono esserci eventi di performance nuovi o obsoleti.


Unified Manager genera eventi di avviso per violazioni delle policy di utilizzo eccessivo delle risorse dei nodi, cercando i nodi che utilizzano più del 100% della loro capacità prestazionale per più di 30 minuti.

È possibile utilizzare System Manager o i comandi ONTAP per correggere questo tipo di problema di prestazioni, incluse le seguenti attività:

* Creazione e applicazione di una policy QoS a tutti i volumi o LUN che utilizzano eccessivamente le risorse di sistema
* Riduzione del limite massimo di throughput QoS di un gruppo di policy a cui sono stati applicati carichi di lavoro
* Spostamento di un carico di lavoro su un aggregato o nodo diverso
* Aumentare la capacità aggiungendo dischi al nodo o aggiornando a un nodo con una CPU più veloce e più RAM


.Passi
. Visualizza la pagina *Dettagli evento* per visualizzare le informazioni sull'evento.
. Esaminare la *Descrizione*, che descrive la violazione della soglia che ha causato l'evento.
+
Ad esempio, il messaggio "`Perf.  Il valore di Capacità utilizzata del 139% su simplicity-02 ha attivato un evento di AVVISO per identificare potenziali problemi di prestazioni nell'unità di elaborazione dati.`" indica che la capacità di prestazioni sul nodo simplicity-02 è sovrautilizzata e influisce sulle prestazioni del nodo.

. Nella sezione *Diagnosi di sistema*, esaminare i tre grafici: uno per la capacità di prestazioni utilizzata sul nodo, uno per gli IOPS di storage medi utilizzati dai carichi di lavoro principali e uno per la latenza sui carichi di lavoro principali.  Organizzandoli in questo modo è possibile vedere quali carichi di lavoro sono la causa della latenza sul nodo.
+
È possibile visualizzare a quali carichi di lavoro sono applicati criteri QoS e a quali no, spostando il cursore sul grafico IOPS.

. Nella sezione *Azioni suggerite*, rivedi i suggerimenti e determina quali azioni dovresti eseguire per evitare un aumento della latenza del carico di lavoro.
+
Se necessario, fare clic sul pulsante *Aiuto* per visualizzare maggiori dettagli sulle azioni suggerite che è possibile eseguire per provare a risolvere l'evento di prestazione.


