---
permalink: performance-checker/task_view_event_details_in_performance_explorer_events_timeline.html 
sidebar: sidebar 
keywords: view, event, details, timeline 
summary: 'È possibile visualizzare tutti gli eventi e i relativi dettagli nel riquadro Cronologia eventi di Performance Explorer.  Si tratta di un metodo rapido ed efficiente per visualizzare tutti gli eventi relativi a integrità e prestazioni che si sono verificati sull"oggetto radice durante un intervallo di tempo specificato, il che può essere utile per la risoluzione dei problemi di prestazioni.' 
---
= Visualizza i dettagli dell'evento nella cronologia degli eventi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare tutti gli eventi e i relativi dettagli nel riquadro Cronologia eventi di Performance Explorer.  Si tratta di un metodo rapido ed efficiente per visualizzare tutti gli eventi relativi a integrità e prestazioni che si sono verificati sull'oggetto radice durante un intervallo di tempo specificato, il che può essere utile per la risoluzione dei problemi di prestazioni.

Il riquadro Cronologia eventi mostra gli eventi critici, di errore, di avviso e informativi che si sono verificati sull'oggetto radice durante l'intervallo di tempo selezionato.  Ogni gravità dell'evento ha una propria tempistica.  Gli eventi singoli e multipli sono rappresentati da un punto evento sulla sequenza temporale.  Puoi posizionare il cursore sul punto di un evento per visualizzarne i dettagli.  Per aumentare la granularità visiva di più eventi, è possibile ridurre l'intervallo di tempo.  In questo modo più eventi vengono suddivisi in singoli eventi, consentendo di visualizzare e analizzare separatamente ciascun evento.

Ogni punto dell'evento di performance sulla cronologia degli eventi si allinea verticalmente con un picco corrispondente nelle linee di tendenza dei grafici del contatore visualizzate sotto la cronologia degli eventi.  Ciò fornisce una correlazione visiva diretta tra gli eventi e le prestazioni complessive.  Anche gli eventi sanitari vengono visualizzati sulla cronologia, ma questi tipi di eventi non coincidono necessariamente con un picco in uno dei grafici delle prestazioni.

.Passi
. Nel riquadro *Cronologia eventi*, posizionare il cursore su un punto evento su una cronologia per visualizzare un riepilogo dell'evento o degli eventi in quel punto.
+
Una finestra di dialogo pop-up mostra informazioni sui tipi di evento, la data e l'ora in cui si sono verificati gli eventi, lo stato e la durata dell'evento.

. Visualizza i dettagli completi dell'evento per uno o più eventi:
+
|===
| Per fare questo... | Clicca qui... 


 a| 
Visualizza i dettagli di un singolo evento
 a| 
*Visualizza dettagli evento* nella finestra di dialogo pop-up.



 a| 
Visualizza i dettagli per più eventi
 a| 
*Visualizza dettagli evento* nella finestra di dialogo pop-up.

[NOTE]
====
Facendo clic su un singolo evento nella finestra di dialogo degli eventi multipli viene visualizzata la pagina Dettagli evento appropriata.

====
|===

