---
permalink: storage-mgmt/concept_what_quota_limits_are.html 
sidebar: sidebar 
keywords: quota, limits 
summary: 'I limiti delle quote utente sono valori che il server Unified Manager utilizza per valutare se il consumo di spazio da parte di un utente si sta avvicinando al limite o ha raggiunto il limite impostato dalla quota dell"utente.  Se viene superato il limite flessibile o se viene raggiunto il limite rigido, il server Unified Manager genera eventi di quota utente.' 
---
= Quali sono i limiti delle quote
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I limiti delle quote utente sono valori che il server Unified Manager utilizza per valutare se il consumo di spazio da parte di un utente si sta avvicinando al limite o ha raggiunto il limite impostato dalla quota dell'utente.  Se viene superato il limite flessibile o se viene raggiunto il limite rigido, il server Unified Manager genera eventi di quota utente.

Per impostazione predefinita, il server Unified Manager invia un'e-mail di notifica agli utenti che hanno superato il limite flessibile della quota o hanno raggiunto il limite rigido della quota e per i quali sono configurati eventi di quota utente.  Gli utenti con il ruolo di amministratore dell'applicazione possono configurare avvisi che notificano ai destinatari specificati gli eventi relativi alle quote utente o gruppo di utenti.

È possibile specificare i limiti di quota utilizzando ONTAP System Manager o ONTAP CLI.
