---
permalink: storage-mgmt/concept_monitor_and_manage_clusters_from_dashboard.html 
sidebar: sidebar 
keywords: monitor, manage, clusters, dashboard 
summary: 'La dashboard fornisce informazioni cumulative e immediate sullo stato attuale dei sistemi ONTAP monitorati.  La dashboard fornisce "pannelli" che consentono di valutare la capacità complessiva, le prestazioni e lo stato di sicurezza dei cluster monitorati.' 
---
= Monitora e gestisci i cluster dalla dashboard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La dashboard fornisce informazioni cumulative e immediate sullo stato attuale dei sistemi ONTAP monitorati.  La dashboard fornisce dei "pannelli" che consentono di valutare la capacità complessiva, le prestazioni e lo stato di sicurezza dei cluster monitorati.

Inoltre, ci sono alcuni problemi ONTAP che è possibile risolvere direttamente dall'interfaccia utente di Unified Manager, senza dover utilizzare ONTAP System Manager o ONTAP CLI.

Nella parte superiore della dashboard è possibile selezionare se i pannelli devono visualizzare le informazioni per tutti i cluster monitorati o per un singolo cluster.  È possibile iniziare visualizzando lo stato di tutti i cluster e poi passare ai singoli cluster quando si desidera visualizzare informazioni dettagliate.

[NOTE]
====
In base alla configurazione, alcuni dei pannelli elencati di seguito potrebbero non essere visualizzati nella pagina.

====
|===
| Pannelli | Descrizione 


 a| 
Azioni di gestione
 a| 
Quando Unified Manager riesce a diagnosticare e determinare una singola soluzione per un problema, tali soluzioni vengono visualizzate in questo pannello con un pulsante *Correggi*.



 a| 
Capacità
 a| 
Visualizza la capacità totale e utilizzata per il livello locale e il livello cloud, nonché il numero di giorni necessari affinché la capacità locale raggiunga il limite massimo.



 a| 
Capacità di prestazione
 a| 
Visualizza il valore della capacità prestazionale per ciascun cluster e il numero di giorni necessari affinché la capacità prestazionale raggiunga il limite superiore.



 a| 
IOPS del carico di lavoro
 a| 
Visualizza il numero totale di carichi di lavoro attualmente in esecuzione in un determinato intervallo di IOPS.



 a| 
Prestazioni del carico di lavoro
 a| 
Visualizza il numero totale di carichi di lavoro conformi e non conformi assegnati a ciascun livello di servizio di prestazione definito.



 a| 
Sicurezza
 a| 
Visualizza il numero di cluster conformi o non conformi, il numero di SVM conformi o non conformi e il numero di volumi crittografati o non crittografati.



 a| 
Protezione
 a| 
Visualizza il numero di VM di archiviazione protette dalla relazione SVM-DR, volumi protetti dalla relazione SnapMirror , volumi protetti da Snapshot e cluster protetti da MetroCluster.



 a| 
Panoramica sull'utilizzo
 a| 
Visualizza i cluster ordinati in base al numero più elevato di IOPS, alla velocità effettiva più elevata (MBps) o alla capacità fisica più elevata utilizzata.

|===