---
permalink: storage-mgmt/concept_fix_ontap_issues_directly_from_unified_manager.html 
sidebar: sidebar 
keywords: fix, ontap, issues, directly, unified manager, fix it, fix-it, remediation 
summary: 'È possibile risolvere determinati problemi ONTAP direttamente dall"interfaccia utente di Unified Manager anziché dover utilizzare ONTAP System Manager o ONTAP CLI.  L"opzione "Azioni di gestione" fornisce correzioni a una serie di problemi ONTAP che hanno attivato eventi Unified Manager.' 
---
= Gestisci i problemi o le funzionalità ONTAP direttamente da Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile risolvere determinati problemi ONTAP o gestire determinate funzionalità ONTAP direttamente dall'interfaccia utente di Unified Manager, anziché dover utilizzare ONTAP System Manager o ONTAP CLI.  L'opzione "`Azioni di gestione`" fornisce correzioni a una serie di problemi ONTAP che hanno attivato eventi Unified Manager.

È possibile risolvere i problemi direttamente dalla pagina Azioni di gestione selezionando l'opzione *Azioni di gestione* nel riquadro di navigazione a sinistra.  Le azioni di gestione sono disponibili anche nel pannello Azioni di gestione nella Dashboard, nella pagina Dettagli evento e nella selezione Analisi del carico di lavoro nel menu di navigazione a sinistra.

Ci sono alcuni problemi che Unified Manager può diagnosticare in modo approfondito e fornire una soluzione univoca.  Per alcune funzionalità ONTAP , come il monitoraggio anti-ransomware, Unified Manager esegue controlli interni e consiglia azioni specifiche.  Se disponibili, tali risoluzioni vengono visualizzate in Azioni di gestione con un pulsante *Correggi*.  Fare clic sul pulsante *Risolvi* per risolvere il problema.  È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Unified Manager invia comandi ONTAP al cluster per apportare la correzione richiesta.  Una volta completata la correzione, l'evento diventa obsoleto.

Alcune azioni di gestione consentono di risolvere lo stesso problema su più oggetti di archiviazione utilizzando il pulsante *Correggi tutto*.  Ad esempio, potrebbero esserci 5 volumi con l'evento "Spazio volume pieno" che potrebbe essere risolto facendo clic sull'azione di gestione *Correggi tutto* per "Abilita aumento automatico volume".  Con un clic è possibile risolvere il problema su 5 volumi.

Per informazioni sui problemi e sulle funzionalità ONTAP che è possibile gestire utilizzando la correzione automatica, vederelink:../storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html["Quali problemi può risolvere Unified Manager"] .
