---
permalink: storage-mgmt/concept_overview_of_quota_process_um_6_1.html 
sidebar: sidebar 
keywords: overview, quota, process 
summary: 'Le quote possono essere flessibili o rigide.  Le quote flessibili fanno sì che ONTAP invii una notifica quando vengono superati i limiti specificati, mentre le quote rigide impediscono che un"operazione di scrittura vada a buon fine quando vengono superati i limiti specificati.' 
---
= Panoramica del processo di quota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le quote possono essere flessibili o rigide.  Le quote flessibili fanno sì che ONTAP invii una notifica quando vengono superati i limiti specificati, mentre le quote rigide impediscono che un'operazione di scrittura vada a buon fine quando vengono superati i limiti specificati.

Quando ONTAP riceve una richiesta da un utente o da un gruppo di utenti per scrivere su un FlexVol volume, verifica se le quote sono attivate su quel volume per l'utente o il gruppo di utenti e determina quanto segue:

* Se verrà raggiunto il limite massimo
+
In caso affermativo, l'operazione di scrittura fallisce quando viene raggiunto il limite massimo e viene inviata la notifica della quota massima.

* Se il limite soft verrà violato
+
In caso affermativo, l'operazione di scrittura riesce quando il limite flessibile viene superato e viene inviata la notifica della quota flessibile.

* Se un'operazione di scrittura non supererà il limite flessibile
+
In caso affermativo, l'operazione di scrittura riesce e non viene inviata alcuna notifica.


