---
permalink: storage-mgmt/task_edit_clusters.html 
sidebar: sidebar 
keywords: edit, clusters 
summary: 'È possibile modificare le impostazioni di un cluster esistente, ad esempio il nome host o l"indirizzo IP, il nome utente, la password e la porta, utilizzando la finestra di dialogo Modifica cluster.' 
---
= Modifica cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di un cluster esistente, ad esempio il nome host o l'indirizzo IP, il nome utente, la password e la porta, utilizzando la finestra di dialogo Modifica cluster.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o di Amministratore dell'archiviazione.

[NOTE]
====
A partire da Unified Manager 9.7, i cluster possono essere aggiunti solo tramite HTTPS.

====
.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Configurazione cluster*.
. Nella pagina *Configurazione cluster*, seleziona il cluster che desideri modificare, quindi fai clic su *Modifica*.
. Nella finestra di dialogo *Modifica cluster*, modificare i valori come desiderato.  + Se hai modificato i dettagli di un cluster aggiunto a Unified Manager, puoi visualizzare i dettagli del certificato per la comunicazione Mutual TLS, in base alla versione ONTAP .  Per maggiori informazioni sulla versione ONTAP , vederelink:../storage-mgmt/task_add_clusters.html["Certificati per la comunicazione TLS reciproca"] .  + È possibile visualizzare i dettagli del certificato facendo clic su *Dettagli certificato*.  Se il certificato è scaduto, fare clic sul pulsante *Rigenera* per incorporare il nuovo certificato.
. Fare clic su *Invia*.
. Nella finestra di dialogo Autorizza host, fare clic su *Visualizza certificato* per visualizzare le informazioni sul certificato del cluster.
. Fare clic su *Sì*.


*Informazioni correlate*

link:../config/task_add_users.html["Aggiunta di utenti"]

link:../health-checker/task_view_cluster_list_and_details.html["Visualizzazione dell'elenco e dei dettagli dei cluster"]
