---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: 'È possibile creare LUN che supportano i protocolli CIFS/SMB e NFS su un cluster esistente e su una macchina virtuale di archiviazione (VM di archiviazione) dalla pagina Provision Workload.' 
---
= Fornitura di LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare LUN che supportano i protocolli CIFS/SMB e NFS su un cluster esistente e su una macchina virtuale di archiviazione (VM di archiviazione) dalla pagina Provision Workload.

.Prima di iniziare
* La VM di archiviazione deve disporre di spazio per il provisioning della LUN.
* Sia iSCSI che FCP devono essere abilitati sulla VM di archiviazione su cui si crea il LUN.
* Per selezionare e assegnare il Performance Service Level (PSL) e la Storage Efficiency Policy (SEP) al carico di lavoro, è necessario che le policy siano state create prima di iniziare a creare il carico di lavoro.


.Passi
. Nella pagina *Provision Workload*, aggiungi il nome del carico di lavoro che desideri creare, quindi seleziona il cluster dall'elenco disponibile.
+
In base al cluster selezionato, il campo *STORAGE VM* filtra le VM di archiviazione disponibili per quel cluster.

. Selezionare dall'elenco la VM di archiviazione che supporta i servizi iSCSI e FCP.
+
In base alla selezione effettuata, l'opzione SAN viene abilitata nella sezione Informazioni host.

. Nella sezione *Archiviazione e ottimizzazione*, assegnare la capacità di archiviazione e il PSL e, facoltativamente, l'SEP per il carico di lavoro.
+
Le specifiche per il SEP vengono assegnate al LUN e le definizioni per il PSL vengono applicate al carico di lavoro al momento della sua creazione.

. Selezionare la casella di controllo *Applica limiti di prestazioni* se si desidera applicare il PSL assegnato al carico di lavoro.
+
L'assegnazione di un PSL a un carico di lavoro garantisce che l'aggregato su cui viene creato il carico di lavoro possa supportare gli obiettivi di prestazioni e capacità definiti nella rispettiva policy.  Ad esempio, se a un carico di lavoro viene assegnato il PSL "Prestazioni estreme", l'aggregato su cui deve essere eseguito il provisioning del carico di lavoro deve essere in grado di supportare gli obiettivi di prestazioni e capacità della policy "Prestazioni estreme", come l'archiviazione SSD.

+
[NOTE]
====
A meno che non si selezioni questa casella di controllo, il PSL non viene applicato al carico di lavoro e lo stato del carico di lavoro sul dashboard appare come `unassigned` .

====
. Selezionare l'opzione *SAN*.  Se non riesci a vedere l'opzione *SAN* abilitata, verifica se la VM di archiviazione selezionata supporta iSCSI e FCP.
. Selezionare il sistema operativo host.
. Specificare la mappatura host per controllare l'accesso degli iniziatori alla LUN.  È possibile assegnare gruppi di iniziatori esistenti (igroup) oppure definire e mappare nuovi igroup.
+
[NOTE]
====
Se si crea un nuovo igroup durante il provisioning della LUN, è necessario attendere il successivo ciclo di rilevamento (fino a 15 minuti) per utilizzarlo.  Si consiglia pertanto di utilizzare un igroup esistente dall'elenco degli igroup disponibili.

====
+
Se si desidera creare un nuovo igroup, selezionare il pulsante *Crea un nuovo gruppo iniziatore* e immettere le informazioni per l'igroup.

. Fare clic su *Salva*.
+
La LUN viene aggiunta all'elenco dei carichi di lavoro di archiviazione.


