---
permalink: storage-mgmt/task_view_user_and_user_group_quotas.html 
sidebar: sidebar 
keywords: view, user, user, group, quotas 
summary: 'La pagina Dettagli VM di archiviazione/Stato visualizza informazioni sulle quote utente e gruppo utente configurate sulla SVM.  È possibile visualizzare il nome dell"utente o del gruppo di utenti, i limiti impostati sui dischi e sui file, lo spazio su disco e sui file utilizzato e l"indirizzo e-mail per le notifiche.' 
---
= Visualizza le quote degli utenti e dei gruppi di utenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Dettagli VM di archiviazione/Stato visualizza informazioni sulle quote utente e gruppo utente configurate sulla SVM.  È possibile visualizzare il nome dell'utente o del gruppo di utenti, i limiti impostati sui dischi e sui file, lo spazio su disco e sui file utilizzato e l'indirizzo e-mail per le notifiche.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *VM di archiviazione*.
. Nella vista *Integrità: tutte le VM di archiviazione*, seleziona una VM di archiviazione e quindi fai clic sulla scheda *Quote utente e gruppo*.


*Informazioni correlate*

link:../config/task_add_users.html["Aggiunta di utenti"]
