---
permalink: storage-mgmt/task_change_performance_statistics_collection_interval.html 
sidebar: sidebar 
keywords: change, performance, statistics, collection, interval 
summary: 'L"intervallo di raccolta predefinito per le statistiche sulle prestazioni è di 5 minuti.  È possibile modificare questo intervallo a 10 o 15 minuti se si nota che le raccolte provenienti da cluster di grandi dimensioni non vengono completate entro il tempo predefinito.  Questa impostazione influisce sulla raccolta di statistiche da tutti i cluster monitorati da questa istanza di Unified Manager.' 
---
= Modificare l'intervallo di raccolta delle statistiche sulle prestazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'intervallo di raccolta predefinito per le statistiche sulle prestazioni è di 5 minuti.  È possibile modificare questo intervallo a 10 o 15 minuti se si nota che le raccolte provenienti da cluster di grandi dimensioni non vengono completate entro il tempo predefinito.  Questa impostazione influisce sulla raccolta di statistiche da tutti i cluster monitorati da questa istanza di Unified Manager.

.Prima di iniziare
Per accedere alla console di manutenzione del server Unified Manager è necessario disporre di un ID utente e di una password autorizzati.

Il problema delle raccolte di statistiche sulle prestazioni che non terminano in tempo è indicato dai messaggi del banner `Unable to consistently collect from cluster <cluster_name> or Data collection is taking too long on cluster <cluster_name>.`

Dovresti modificare l'intervallo di raccolta solo quando necessario a causa di un problema di raccolta delle statistiche.  Non modificare questa impostazione per nessun altro motivo.

[NOTE]
====
La modifica di questo valore rispetto all'impostazione predefinita di 5 minuti può influire sul numero e sulla frequenza degli eventi di prestazione segnalati da Unified Manager.  Ad esempio, le soglie di prestazioni definite dal sistema attivano eventi quando la policy viene superata per 30 minuti.  Quando si utilizzano raccolte di 5 minuti, la norma deve essere superata per sei raccolte consecutive.  Per le raccolte di 15 minuti, la norma deve essere superata solo per due periodi di raccolta.

====
Un messaggio nella parte inferiore della pagina Configurazione cluster indica l'intervallo corrente di raccolta dei dati statistici.

.Passi
. Accedere tramite SSH come utente di manutenzione all'host Unified Manager.
+
Vengono visualizzati i prompt della console di manutenzione di Unified Manager.

. Digitare il numero dell'opzione di menu denominata *Configurazione intervallo di polling delle prestazioni*, quindi premere Invio.
. Se richiesto, immettere nuovamente la password dell'utente addetto alla manutenzione.
. Digitare il numero per il nuovo intervallo di polling che si desidera impostare, quindi premere Invio.


Se hai modificato l'intervallo di raccolta di Unified Manager in 10 o 15 minuti e hai una connessione corrente a un provider di dati esterno (ad esempio Graphite), devi modificare l'intervallo di trasmissione del provider di dati in modo che sia uguale o maggiore dell'intervallo di raccolta di Unified Manager.
