---
permalink: storage-mgmt/task_rediscover_clusters.html 
sidebar: sidebar 
keywords: rediscover clusters, 
summary: È possibile riscoprire manualmente un cluster dalla pagina Configurazione cluster per ottenere le informazioni più recenti sullo stato di integrità, di monitoraggio e sulle prestazioni del cluster. 
---
= Riscoprire i cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile riscoprire manualmente un cluster dalla pagina Configurazione cluster per ottenere le informazioni più recenti sullo stato di integrità, di monitoraggio e sulle prestazioni del cluster.

È possibile riscoprire manualmente un cluster quando si desidera aggiornarlo, ad esempio aumentando le dimensioni di un aggregato quando lo spazio non è sufficiente, e si desidera che Unified Manager rilevi le modifiche apportate.

Quando Unified Manager è associato a OnCommand Workflow Automation (WFA), l'associazione attiva la riacquisizione dei dati memorizzati nella cache da WFA.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Configurazione cluster*.
. Nella pagina *Configurazione cluster*, fare clic su *Riscopri*.
+
Unified Manager riscopre il cluster selezionato e visualizza lo stato di integrità e le prestazioni più recenti.



*Informazioni correlate*

link:../health-checker/task_view_cluster_list_and_details.html["Visualizzazione dell'elenco e dei dettagli dei cluster"]
