---
permalink: health-checker/concept_what_database_restore_is.html 
sidebar: sidebar 
keywords: unified manager, database, restore 
summary: 'Il ripristino del database MySQL è il processo di ripristino di un file di backup di Unified Manager esistente sullo stesso server Unified Manager o su uno diverso.  L"operazione di ripristino viene eseguita dalla console di manutenzione di Unified Manager.' 
---
= Che cosa è un ripristino del database
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ripristino del database MySQL è il processo di ripristino di un file di backup di Unified Manager esistente sullo stesso server Unified Manager o su uno diverso.  L'operazione di ripristino viene eseguita dalla console di manutenzione di Unified Manager.

Se si esegue un'operazione di ripristino sullo stesso sistema (locale) e tutti i file di backup sono archiviati localmente, è possibile eseguire l'opzione di ripristino utilizzando la posizione predefinita.  Se si esegue un'operazione di ripristino su un sistema Unified Manager diverso (un sistema remoto), è necessario copiare il file o i file di backup dall'archivio secondario al disco locale prima di eseguire l'opzione di ripristino.

Durante il processo di ripristino, verrai disconnesso da Unified Manager.  Una volta completato il processo di ripristino, sarà possibile accedere al sistema.

Se si ripristina l'immagine di backup su un nuovo server, al termine dell'operazione di ripristino è necessario generare un nuovo certificato di sicurezza HTTPS e riavviare il server Unified Manager.  Sarà inoltre necessario riconfigurare le impostazioni di autenticazione SAML, se necessario, quando si ripristina l'immagine di backup su un nuovo server.

[NOTE]
====
Non è possibile utilizzare i vecchi file di backup per ripristinare un'immagine dopo che Unified Manager è stato aggiornato a una versione più recente del software.  Per risparmiare spazio, tutti i vecchi file di backup, ad eccezione del file più recente, vengono rimossi automaticamente quando si aggiorna Unified Manager.

====
*Informazioni correlate*

link:../config/task_generate_an_https_security_certificate_ocf.html["Generazione di un certificato di sicurezza HTTPS"]

link:../config/task_enable_saml_authentication_um.html["Abilitazione dell'autenticazione SAML"]

link:../config/concept_authentication_with_active_directory_or_openldap.html["Autenticazione con Active Directory o OpenLDAP"]
