---
permalink: health-checker/concept_what_annotations_are.html 
sidebar: sidebar 
keywords: annotations 
summary: 'Un"annotazione è una stringa di testo (il nome) assegnata a un"altra stringa di testo (il valore).  Ogni coppia nome-valore di annotazione può essere associata dinamicamente agli oggetti di archiviazione utilizzando le regole di annotazione.  Quando si associano oggetti di archiviazione ad annotazioni predefinite, è possibile filtrare e visualizzare gli eventi ad essi correlati.  È possibile applicare annotazioni a cluster, volumi e macchine virtuali di archiviazione (SVM).' 
---
= Cosa sono le annotazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un'annotazione è una stringa di testo (il nome) assegnata a un'altra stringa di testo (il valore).  Ogni coppia nome-valore di annotazione può essere associata dinamicamente agli oggetti di archiviazione utilizzando le regole di annotazione.  Quando si associano oggetti di archiviazione ad annotazioni predefinite, è possibile filtrare e visualizzare gli eventi ad essi correlati.  È possibile applicare annotazioni a cluster, volumi e macchine virtuali di archiviazione (SVM).

Ogni nome di annotazione può avere più valori; ogni coppia nome-valore può essere associata a un oggetto di archiviazione tramite regole.

Ad esempio, è possibile creare un'annotazione denominata "`data-center`" con i valori "`Boston`" e "`Canada`".  È quindi possibile applicare l'annotazione "`data-center`" con il valore "`Boston`" al volume v1.  Quando viene generato un avviso per un evento su un volume v1 annotato con "`data-center`", l'e-mail generata indica la posizione del volume, "`Boston`", e questo consente di stabilire le priorità e risolvere il problema.
