---
permalink: health-checker/concept_how_scripts_work_with_alerts.html 
sidebar: sidebar 
keywords: scripts, work, alerts 
summary: È possibile associare un avviso allo script in modo che venga eseguito quando viene generato un avviso per un evento in Unified Manager.  È possibile utilizzare gli script per risolvere problemi con gli oggetti di archiviazione o identificare quali oggetti di archiviazione generano gli eventi. 
---
= Come funzionano gli script con gli avvisi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile associare un avviso allo script in modo che venga eseguito quando viene generato un avviso per un evento in Unified Manager.  È possibile utilizzare gli script per risolvere problemi con gli oggetti di archiviazione o identificare quali oggetti di archiviazione generano gli eventi.

Quando viene generato un avviso per un evento in Unified Manager, viene inviata un'e-mail di avviso ai destinatari specificati.  Se hai associato un avviso a uno script, lo script viene eseguito.  È possibile ottenere i dettagli degli argomenti passati allo script dall'e-mail di avviso.

[NOTE]
====
Se hai creato uno script personalizzato e lo hai associato a un avviso per un tipo di evento specifico, le azioni vengono eseguite in base allo script personalizzato per quel tipo di evento e le azioni *Correggi* non sono disponibili per impostazione predefinita nella pagina Azioni di gestione o nella dashboard di Unified Manager.

====
Lo script utilizza i seguenti argomenti per l'esecuzione:

* `-eventID`
* `-eventName`
* `-eventSeverity`
* `-eventSourceID`
* `-eventSourceName`
* `-eventSourceType`
* `-eventState`
* `-eventArgs`


È possibile utilizzare gli argomenti negli script e raccogliere informazioni sugli eventi correlati o modificare gli oggetti di archiviazione.



== Esempio per ottenere argomenti dagli script

[listing]
----
print "$ARGV[0] : $ARGV[1]\n"
print "$ARGV[7] : $ARGV[8]\n"
----
Quando viene generato un avviso, questo script viene eseguito e viene visualizzato il seguente output:

[listing]
----
-eventID : 290
-eventSourceID : 4138
----