---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: 'Active IQ Unified Manager supporta il backup e il ripristino tramite NetApp Snapshot sul sistema operativo Windows con l"ausilio di LUN tramite protocollo iSCSI.' 
---
= Configurare il backup su Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager supporta il backup e il ripristino tramite NetApp Snapshot sul sistema operativo Windows con l'ausilio di LUN tramite protocollo iSCSI.

È possibile eseguire il backup basato su snapshot mentre tutti i servizi di Unified Manager sono in esecuzione.  Uno stato coerente del database viene acquisito come parte dello Snapshot, poiché il backup applica un blocco di lettura globale all'intero database, impedendo qualsiasi scrittura simultanea.  Per consentire al sistema Unified Manager installato sul sistema operativo Windows di eseguire il backup e il ripristino tramite NetApp Snapshot, è necessario innanzitutto configurare il backup di Unified Manager basato su Snapshot tramite la console di manutenzione.

Prima di configurare Unified Manager per la creazione di copie Snapshot, è necessario eseguire le seguenti attività di configurazione.

* Configurare il cluster ONTAP
* Configurare la macchina host Windows

