---
permalink: health-checker/concept_how_group_rules_work_for_groups.html 
sidebar: sidebar 
keywords: group rules, work, groups 
summary: 'Una regola di gruppo è un criterio definito per consentire l"inclusione di oggetti di archiviazione (volumi, cluster o SVM) in un gruppo specifico.  È possibile utilizzare gruppi di condizioni o condizioni per definire una regola di gruppo per un gruppo.' 
---
= Come funzionano le regole di gruppo per i gruppi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una regola di gruppo è un criterio definito per consentire l'inclusione di oggetti di archiviazione (volumi, cluster o SVM) in un gruppo specifico.  È possibile utilizzare gruppi di condizioni o condizioni per definire una regola di gruppo per un gruppo.

* È necessario associare una regola di gruppo a un gruppo.
* È necessario associare un tipo di oggetto per una regola di gruppo; a una regola di gruppo è associato un solo tipo di oggetto.
* Gli oggetti di archiviazione vengono aggiunti o rimossi dal gruppo dopo ogni ciclo di monitoraggio o quando una regola viene creata, modificata o eliminata.
* Una regola di gruppo può avere uno o più gruppi di condizioni e ogni gruppo di condizioni può avere una o più condizioni.
* Gli oggetti di archiviazione possono appartenere a più gruppi in base alle regole di gruppo create.




== Condizioni

È possibile creare più gruppi di condizioni e ogni gruppo di condizioni può avere una o più condizioni.  È possibile applicare tutti i gruppi di condizioni definiti in una regola di gruppo per i gruppi, al fine di specificare quali oggetti di archiviazione sono inclusi nel gruppo.

Le condizioni all'interno di un gruppo di condizioni vengono eseguite utilizzando l'operatore logico AND.  Devono essere soddisfatte tutte le condizioni di un gruppo di condizioni.  Quando si crea o si modifica una regola di gruppo, viene creata una condizione che applica, seleziona e raggruppa solo gli oggetti di archiviazione che soddisfano tutte le condizioni nel gruppo di condizioni.  È possibile utilizzare più condizioni all'interno di un gruppo di condizioni quando si desidera restringere l'ambito degli oggetti di archiviazione da includere in un gruppo.

È possibile creare condizioni con oggetti di archiviazione utilizzando i seguenti operandi e operatori e specificando il valore richiesto.

[cols="2*"]
|===
| Tipo di oggetto di archiviazione | Operandi applicabili 


 a| 
Volume
 a| 
* Nome dell'oggetto
* Nome del cluster proprietario
* Possedere il nome SVM
* Annotazioni




 a| 
SVM
 a| 
* Nome dell'oggetto
* Nome del cluster proprietario
* Annotazioni




 a| 
Grappolo
 a| 
* Nome dell'oggetto
* Annotazioni


|===
Quando si seleziona l'annotazione come operando per un qualsiasi oggetto di archiviazione, è disponibile l'operatore "`Is`".  Per tutti gli altri operandi, è possibile selezionare come operatore "`Is`" o "`Contains`".

* Operando
+
L'elenco degli operandi in Unified Manager cambia in base al tipo di oggetto selezionato.  L'elenco include il nome dell'oggetto, il nome del cluster proprietario, il nome dell'SVM proprietario e le annotazioni definite in Unified Manager.

* Operatore
+
L'elenco degli operatori cambia in base all'operando selezionato per una condizione.  Gli operatori supportati in Unified Manager sono "`Is`" e "`Contains`".

+
Quando si seleziona l'operatore "`Is`", la condizione viene valutata per verificare la corrispondenza esatta del valore dell'operando con il valore fornito per l'operando selezionato.

+
Quando si seleziona l'operatore "`Contiene`", la condizione viene valutata in modo che soddisfi uno dei seguenti criteri:

+
** Il valore dell'operando corrisponde esattamente al valore fornito per l'operando selezionato
** Il valore dell'operando contiene il valore fornito per l'operando selezionato


* Valore
+
Il campo valore cambia in base all'operando selezionato.





== Esempio di una regola di gruppo con condizioni

Consideriamo un gruppo di condizioni per un volume con le due condizioni seguenti:

* Il nome contiene "`vol`"
* Il nome SVM è "`data_svm`"


Questo gruppo di condizioni seleziona tutti i volumi che includono "`vol`" nei loro nomi e che sono ospitati su SVM con il nome "`data_svm`".



== Gruppi di condizioni

I gruppi di condizioni vengono eseguiti utilizzando l'operatore logico OR e quindi applicati agli oggetti di archiviazione.  Per essere inclusi in un gruppo, gli oggetti di archiviazione devono soddisfare uno dei gruppi di condizioni.  Vengono combinati gli oggetti di archiviazione di tutti i gruppi di condizioni.  È possibile utilizzare i gruppi di condizioni per ampliare l'ambito degli oggetti di archiviazione da includere in un gruppo.



== Esempio di una regola di gruppo con gruppi di condizioni

Consideriamo due gruppi di condizioni per un volume, ciascuno contenente le due condizioni seguenti:

* Gruppo di condizioni 1
+
** Il nome contiene "`vol`"
** Il nome SVM è "`data_svm`". Il gruppo di condizioni 1 seleziona tutti i volumi che includono "`vol`" nei loro nomi e che sono ospitati su SVM con il nome "`data_svm`".


* Gruppo di condizioni 2
+
** Il nome contiene "`vol`"
** Il valore di annotazione di data-priority è "`critical`". Il gruppo di condizioni 2 seleziona tutti i volumi che includono "`vol`" nei loro nomi e che sono annotati con il valore di annotazione data-priority come "`critical`".




Quando una regola di gruppo contenente questi due gruppi di condizioni viene applicata agli oggetti di archiviazione, i seguenti oggetti di archiviazione vengono aggiunti a un gruppo selezionato:

* Tutti i volumi che includono "`vol`" nei loro nomi e che sono ospitati sulla SVM con il nome "`data_svm`".
* Tutti i volumi che includono "`vol`" nei loro nomi e che sono annotati con il valore di annotazione data-priority "`critical`".

