---
permalink: health-checker/concept_what_group_is.html 
sidebar: sidebar 
keywords: group 
summary: 'Un gruppo è una raccolta dinamica di oggetti di archiviazione eterogenei (cluster, SVM o volumi).  È possibile creare gruppi in Unified Manager per gestire facilmente un set di oggetti di archiviazione.  I membri di un gruppo potrebbero cambiare a seconda degli oggetti di archiviazione monitorati da Unified Manager in un dato momento.' 
---
= Che cosa è un gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un gruppo è una raccolta dinamica di oggetti di archiviazione eterogenei (cluster, SVM o volumi).  È possibile creare gruppi in Unified Manager per gestire facilmente un set di oggetti di archiviazione.  I membri di un gruppo potrebbero cambiare a seconda degli oggetti di archiviazione monitorati da Unified Manager in un dato momento.

* Ogni gruppo ha un nome univoco.
* È necessario configurare almeno una regola di gruppo per ogni gruppo.
* È possibile associare un gruppo a più di una regola di gruppo.
* Ogni gruppo può includere più tipi di oggetti di archiviazione, come cluster, SVM o volumi.
* Gli oggetti di archiviazione vengono aggiunti dinamicamente a un gruppo in base al momento in cui viene creata una regola di gruppo o al momento in cui Unified Manager completa un ciclo di monitoraggio.
* È possibile applicare contemporaneamente azioni a tutti gli oggetti di archiviazione in un gruppo, ad esempio impostando soglie per i volumi.

