---
permalink: health-checker/reference_description_of_predefined_annotation_values.html 
sidebar: sidebar 
keywords: description, predefined, annotation values 
summary: 'Data-priority è un"annotazione predefinita che ha i valori Mission critical, High e Low.  Questi valori consentono di annotare gli oggetti di archiviazione in base alla priorità dei dati in essi contenuti.  Non è possibile modificare o eliminare i valori di annotazione predefiniti.' 
---
= Descrizione dei valori di annotazione predefiniti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*Data-priority* è un'annotazione predefinita che ha i valori Mission critical, High e Low.  Questi valori consentono di annotare gli oggetti di archiviazione in base alla priorità dei dati in essi contenuti.  Non è possibile modificare o eliminare i valori di annotazione predefiniti.

* *Priorità dei dati: Missione critica*
+
Questa annotazione viene applicata agli oggetti di archiviazione che contengono dati critici per la missione.  Ad esempio, gli oggetti che contengono applicazioni di produzione possono essere considerati mission critical.

* *Priorità dati: Alta*
+
Questa annotazione viene applicata agli oggetti di archiviazione che contengono dati ad alta priorità.  Ad esempio, gli oggetti che ospitano applicazioni aziendali possono essere considerati ad alta priorità.

* *Priorità dati: Bassa*
+
Questa annotazione viene applicata agli oggetti di archiviazione che contengono dati a bassa priorità.  Ad esempio, gli oggetti che si trovano su un archivio secondario, come destinazioni di backup e mirror, potrebbero avere una bassa priorità.


