---
permalink: health-checker/reference_health_aggregate_details_page.html 
sidebar: sidebar 
keywords: unified manager, aggregate, health details page 
summary: 'È possibile utilizzare la pagina Dettagli aggregato/integrità per visualizzare informazioni dettagliate sull"aggregato selezionato, come capacità, informazioni sul disco, dettagli di configurazione ed eventi generati.  È inoltre possibile visualizzare informazioni sugli oggetti correlati e sugli avvisi correlati per tale aggregato.' 
---
= Pagina dei dettagli aggregati/sanitari
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la pagina Dettagli aggregato/integrità per visualizzare informazioni dettagliate sull'aggregato selezionato, come capacità, informazioni sul disco, dettagli di configurazione ed eventi generati.  È inoltre possibile visualizzare informazioni sugli oggetti correlati e sugli avvisi correlati per tale aggregato.



== Pulsanti di comando

[NOTE]
====
Durante il monitoraggio di un aggregato abilitato per FabricPool, i valori committed e overcommit in questa pagina sono rilevanti solo per la capacità locale o del livello di prestazioni.  La quantità di spazio disponibile nel livello cloud non si riflette nei valori sovraimpegnati.  Allo stesso modo, i valori soglia aggregati sono rilevanti solo per il livello di prestazioni locale.

====
I pulsanti di comando consentono di eseguire le seguenti attività per l'aggregato selezionato:

* *Passa alla visualizzazione delle prestazioni*
+
Consente di accedere alla pagina dei dettagli Aggregati/Prestazioni.

* *Azioni*
+
** Aggiungi avviso
+
Consente di aggiungere un avviso all'aggregato selezionato.

** Modifica soglie
+
Consente di modificare le impostazioni della soglia per l'aggregato selezionato.



* *Visualizza aggregati*
+
Consente di passare alla vista Salute: Tutti gli aggregati.





== Scheda Capacità

La scheda Capacità visualizza informazioni dettagliate sull'aggregato selezionato, come la sua capacità, le soglie e il tasso di crescita giornaliero.

Per impostazione predefinita, gli eventi di capacità non vengono generati per gli aggregati radice.  Inoltre, i valori soglia utilizzati da Unified Manager non sono applicabili agli aggregati radice del nodo.  Solo un rappresentante del supporto tecnico può modificare le impostazioni per la generazione di questi eventi.  Quando le impostazioni vengono modificate da un rappresentante del supporto tecnico, i valori di soglia vengono applicati all'aggregato radice del nodo.

* *Capacità*
+
Visualizza il grafico della capacità dei dati e il grafico delle copie snapshot, che mostrano i dettagli della capacità dell'aggregato:

+
** Spazio logico utilizzato
+
La dimensione reale dei dati memorizzati in forma aggregata, senza considerare i risparmi derivanti dall'utilizzo delle tecnologie di efficienza di archiviazione ONTAP .

** Usato
+
La capacità fisica utilizzata dai dati nell'aggregato.

** Troppo impegnato
+
Quando lo spazio nell'aggregato è sovraccaricato, il grafico visualizza un flag con la quantità sovraccaricata.

** Avvertimento
+
Visualizza una linea tratteggiata nel punto in cui è impostata la soglia di avviso, a indicare che lo spazio nell'aggregato è quasi pieno.  Se questa soglia viene superata, viene generato l'evento Spazio quasi pieno.

** Errore
+
Visualizza una linea continua nel punto in cui è impostata la soglia di errore, a indicare che lo spazio nell'aggregato è pieno.  Se questa soglia viene superata, viene generato l'evento Spazio pieno.

** Grafico delle copie snapshot
+
Questo grafico viene visualizzato solo quando la capacità Snapshot utilizzata o la riserva Snapshot non è zero.



+
Entrambi i grafici mostrano la capacità per cui la capacità Snapshot supera la riserva Snapshot se la capacità Snapshot utilizzata supera la riserva Snapshot.

* *Livello Cloud*
+
Visualizza lo spazio utilizzato dai dati nel livello cloud per gli aggregati abilitati per FabricPool.  Un FabricPool può essere concesso in licenza o meno.

+
Quando il livello cloud viene replicato su un altro provider cloud (il "livello mirror"), entrambi i livelli cloud vengono visualizzati qui.

* *Dettagli*
+
Visualizza informazioni dettagliate sulla capacità.

+
** Capacità totale
+
Visualizza la capacità totale aggregata.

** Capacità dei dati
+
Visualizza la quantità di spazio utilizzata dall'aggregato (capacità utilizzata) e la quantità di spazio disponibile nell'aggregato (capacità libera).

** Riserva istantanea
+
Visualizza la capacità Snapshot utilizzata e libera dell'aggregato.

** Capacità sovraccaricata
+
Visualizza l'eccesso di impegno aggregato.  L'overcommitment aggregato consente di fornire più spazio di archiviazione di quello effettivamente disponibile da un dato aggregato, a condizione che non tutto lo spazio di archiviazione sia attualmente utilizzato.  Quando si utilizza il thin provisioning, la dimensione totale dei volumi nell'aggregato può superare la capacità totale dell'aggregato.

+
[NOTE]
====
Se hai sovraccaricato il tuo aggregato, devi monitorare attentamente lo spazio disponibile e aggiungere spazio di archiviazione secondo necessità per evitare errori di scrittura dovuti a spazio insufficiente.

====
** Livello cloud
+
Visualizza lo spazio utilizzato dai dati nel livello cloud per gli aggregati abilitati per FabricPool.  Un FabricPool può essere concesso in licenza o meno.  Quando il livello cloud viene rispecchiato su un altro provider cloud (il livello mirror), entrambi i livelli cloud vengono visualizzati qui

** Spazio totale nella cache
+
Visualizza lo spazio totale delle unità a stato solido (SSD) o delle unità di allocazione aggiunte a un aggregato Flash Pool.  Se hai abilitato Flash Pool per un aggregato ma non hai aggiunto alcun SSD, lo spazio della cache viene visualizzato come 0 KB.

+
[NOTE]
====
Questo campo è nascosto se Flash Pool è disabilitato per un aggregato.

====
** Soglie aggregate
+
Visualizza le seguenti soglie di capacità aggregata:

+
*** Soglia quasi piena
+
Specifica la percentuale in cui un aggregato è quasi pieno.

*** Soglia completa
+
Specifica la percentuale in cui un aggregato è pieno.

*** Soglia quasi superata
+
Specifica la percentuale in cui un aggregato è quasi sovraimpegnato.

*** Soglia di impegno eccessivo
+
Specifica la percentuale in cui un aggregato è sovraimpegnato.



** Altri dettagli: tasso di crescita giornaliero
+
Visualizza lo spazio su disco utilizzato nell'aggregato se il tasso di variazione tra gli ultimi due campioni continua per 24 ore.

+
Ad esempio, se un aggregato utilizza 10 GB di spazio su disco alle 14:00 e 12 GB alle 18:00, il tasso di crescita giornaliero (GB) per questo aggregato è di 2 GB.

** Spostamento del volume
+
Visualizza il numero di operazioni di spostamento del volume attualmente in corso:

+
*** Volumi fuori
+
Visualizza il numero e la capacità dei volumi che vengono spostati fuori dall'aggregato.

+
È possibile fare clic sul collegamento per visualizzare ulteriori dettagli, ad esempio il nome del volume, l'aggregato in cui è stato spostato il volume, lo stato dell'operazione di spostamento del volume e l'ora di fine stimata.

*** Volumi in
+
Visualizza il numero e la capacità residua dei volumi che vengono spostati nell'aggregato.

+
È possibile fare clic sul collegamento per visualizzare ulteriori dettagli, ad esempio il nome del volume, l'aggregato da cui il volume viene spostato, lo stato dell'operazione di spostamento del volume e l'ora di fine stimata.

*** Capacità stimata utilizzata dopo lo spostamento del volume
+
Visualizza la quantità stimata di spazio utilizzato (in percentuale e in KB, MB, GB e così via) in forma aggregata dopo il completamento delle operazioni di spostamento del volume.





* *Panoramica della capacità - Volumi*
+
Visualizza grafici che forniscono informazioni sulla capacità dei volumi contenuti nell'aggregato.  Vengono visualizzate la quantità di spazio utilizzata dal volume (capacità utilizzata) e la quantità di spazio disponibile (capacità libera) nel volume.  Quando viene generato l'evento Spazio a rischio del volume con thin provisioning per i volumi con thin provisioning, vengono visualizzate la quantità di spazio utilizzata dal volume (capacità utilizzata) e la quantità di spazio disponibile nel volume ma che non può essere utilizzata (capacità inutilizzabile) a causa di problemi di capacità aggregata.

+
È possibile selezionare il grafico che si desidera visualizzare dagli elenchi a discesa.  È possibile ordinare i dati visualizzati nel grafico per visualizzare dettagli quali la dimensione utilizzata, la dimensione fornita, la capacità disponibile, il tasso di crescita giornaliero più rapido e il tasso di crescita più lento.  È possibile filtrare i dati in base alle macchine virtuali di archiviazione (SVM) che contengono i volumi nell'aggregato.  È anche possibile visualizzare i dettagli dei volumi con provisioning ridotto.  È possibile visualizzare i dettagli di punti specifici sul grafico posizionando il cursore sull'area di interesse.  Per impostazione predefinita, il grafico visualizza i primi 30 volumi filtrati in forma aggregata.





== Scheda Informazioni sul disco

Visualizza informazioni dettagliate sui dischi nell'aggregato selezionato, tra cui il tipo e la dimensione RAID e il tipo di dischi utilizzati nell'aggregato.  La scheda visualizza anche graficamente i gruppi RAID e i tipi di dischi utilizzati (ad esempio SAS, ATA, FCAL, SSD o VMDISK).  È possibile visualizzare ulteriori informazioni, come l'alloggiamento, lo scaffale e la velocità di rotazione del disco, posizionando il cursore sui dischi di parità e sui dischi dati.

* *Dati*
+
Visualizza graficamente i dettagli sui dischi dati dedicati, sui dischi dati condivisi o su entrambi.  Quando i dischi dati contengono dischi condivisi, vengono visualizzati i dettagli grafici dei dischi condivisi.  Quando i dischi dati contengono dischi dedicati e dischi condivisi, vengono visualizzati i dettagli grafici sia dei dischi dati dedicati sia di quelli condivisi.

+
** *Dettagli RAID*
+
I dettagli RAID vengono visualizzati solo per i dischi dedicati.

+
*** Tipo
+
Visualizza il tipo di RAID (RAID0, RAID4, RAID-DP o RAID-TEC).

*** Dimensione del gruppo
+
Visualizza il numero massimo di dischi consentiti nel gruppo RAID.

*** Gruppi
+
Visualizza il numero di gruppi RAID nell'aggregato.



** *Dischi utilizzati*
+
*** Tipo efficace
+
Visualizza i tipi di dischi dati (ad esempio, ATA, SATA, FCAL, SSD o VMDISK) in forma aggregata.

*** Dischi dati
+
Visualizza il numero e la capacità dei dischi dati assegnati a un aggregato.  I dettagli del disco dati non vengono visualizzati quando l'aggregato contiene solo dischi condivisi.

*** Dischi di parità
+
Visualizza il numero e la capacità dei dischi di parità assegnati a un aggregato.  I dettagli del disco di parità non vengono visualizzati quando l'aggregato contiene solo dischi condivisi.

*** Dischi condivisi
+
Visualizza il numero e la capacità dei dischi dati condivisi assegnati a un aggregato.  I dettagli sui dischi condivisi vengono visualizzati solo quando l'aggregato contiene dischi condivisi.



** *Dischi di riserva*
+
Visualizza il tipo effettivo del disco, il numero e la capacità dei dischi dati di riserva disponibili per il nodo nell'aggregato selezionato.

+
[NOTE]
====
Quando un aggregato viene sottoposto a failover sul nodo partner, Unified Manager non visualizza tutti i dischi di riserva compatibili con l'aggregato.

====


* *Cache SSD*
+
Fornisce dettagli sui dischi SSD con cache dedicata e sui dischi SSD con cache condivisa.

+
Vengono visualizzati i seguenti dettagli per i dischi SSD con cache dedicata:

+
** *Dettagli RAID*
+
*** Tipo
+
Visualizza il tipo di RAID (RAID0, RAID4, RAID-DP o RAID-TEC).

*** Dimensione del gruppo
+
Visualizza il numero massimo di dischi consentiti nel gruppo RAID.

*** Gruppi
+
Visualizza il numero di gruppi RAID nell'aggregato.



** *Dischi utilizzati*
+
*** Tipo efficace
+
Indica che i dischi utilizzati per la cache nell'aggregato sono di tipo SSD.

*** Dischi dati
+
Visualizza il numero e la capacità dei dischi dati assegnati a un aggregato per la cache.

*** Dischi di parità
+
Visualizza il numero e la capacità dei dischi di parità assegnati a un aggregato per la cache.



** *Dischi di riserva*
+
Visualizza il tipo effettivo del disco, il numero e la capacità dei dischi di riserva disponibili per il nodo nell'aggregato selezionato per la cache.

+
[NOTE]
====
Quando un aggregato viene sottoposto a failover sul nodo partner, Unified Manager non visualizza tutti i dischi di riserva compatibili con l'aggregato.

====


+
Fornisce i seguenti dettagli per la cache condivisa:

+
** *Pool di archiviazione*
+
Visualizza il nome del pool di archiviazione.  È possibile spostare il puntatore sul nome del pool di archiviazione per visualizzare i seguenti dettagli:

+
*** Stato
+
Visualizza lo stato del pool di archiviazione, che può essere integro o non integro.

*** Assegnazioni totali
+
Visualizza le unità di allocazione totali e le dimensioni nel pool di archiviazione.

*** Dimensione dell'unità di allocazione
+
Visualizza la quantità minima di spazio nel pool di archiviazione che può essere allocata a un aggregato.

*** Dischi
+
Visualizza il numero di dischi utilizzati per creare il pool di archiviazione.  Se il conteggio dei dischi nella colonna del pool di archiviazione e il numero di dischi visualizzati nella scheda Informazioni disco per quel pool di archiviazione non corrispondono, significa che uno o più dischi sono danneggiati e il pool di archiviazione non è integro.

*** Assegnazione utilizzata
+
Visualizza il numero e la dimensione delle unità di allocazione utilizzate dagli aggregati.  È possibile fare clic sul nome dell'aggregato per visualizzarne i dettagli.

*** Assegnazione disponibile
+
Visualizza il numero e la dimensione delle unità di allocazione disponibili per i nodi.  È possibile fare clic sul nome del nodo per visualizzare i dettagli aggregati.



** *Cache allocata*
+
Visualizza la dimensione delle unità di allocazione utilizzate dall'aggregato.

** *Unità di allocazione*
+
Visualizza il numero di unità di allocazione utilizzate dall'aggregato.

** *Dischi*
+
Visualizza il numero di dischi contenuti nel pool di archiviazione.

** *Dettagli*
+
*** Pool di archiviazione
+
Visualizza il numero di pool di archiviazione.

*** Dimensione totale
+
Visualizza la dimensione totale dei pool di archiviazione.





* *Livello Cloud*
+
Visualizza il nome del livello cloud, se è stato configurato un aggregato abilitato per FabricPool, e mostra lo spazio totale utilizzato.  Quando il livello cloud viene rispecchiato su un altro provider cloud (il livello mirror), i dettagli per entrambi i livelli cloud vengono visualizzati qui





== Scheda di configurazione

La scheda Configurazione visualizza i dettagli sull'aggregato selezionato, come il nodo del cluster, il tipo di blocco, il tipo di RAID, la dimensione del RAID e il conteggio dei gruppi RAID:

* *Panoramica*
+
** Nodo
+
Visualizza il nome del nodo che contiene l'aggregato selezionato.

** Tipo di blocco
+
Visualizza il formato del blocco dell'aggregato: 32 bit o 64 bit.

** Tipo RAID
+
Visualizza il tipo di RAID (RAID0, RAID4, RAID-DP, RAID-TEC o RAID misto).

** Dimensioni RAID
+
Visualizza la dimensione del gruppo RAID.

** Gruppi RAID
+
Visualizza il numero di gruppi RAID nell'aggregato.

** Tipo SnapLock
+
Visualizza il tipo SnapLock dell'aggregato.



* *Livello Cloud*
+
Se si tratta di un aggregato abilitato per FabricPool, vengono visualizzati i dettagli per il livello cloud.  Alcuni campi variano a seconda del fornitore di archiviazione.  Quando il livello cloud viene replicato su un altro provider cloud (il "livello mirror"), entrambi i livelli cloud vengono visualizzati qui.

+
** Fornitore
+
Visualizza il nome del provider di archiviazione, ad esempio StorageGRID, Amazon S3, IBM Cloud Object Storage, Microsoft Azure Cloud, Google Cloud Storage o Alibaba Cloud Object Storage.

** Nome
+
Visualizza il nome del livello cloud al momento della sua creazione da parte di ONTAP.

** Server
+
Visualizza il nome di dominio completo (FQDN) del livello cloud.

** Porta
+
La porta utilizzata per comunicare con il provider cloud.

** Chiave di accesso o account
+
Visualizza la chiave di accesso o l'account per il livello cloud.

** Nome del contenitore
+
Visualizza il nome del bucket o del contenitore del livello cloud.

** SSL
+
Mostra se la crittografia SSL è abilitata per il livello cloud.







== Area storica

L'area Cronologia visualizza grafici che forniscono informazioni sulla capacità dell'aggregato selezionato.  Inoltre, puoi cliccare sul pulsante *Esporta* per creare un report in formato CSV per il grafico che stai visualizzando.

È possibile selezionare un tipo di grafico dall'elenco a discesa nella parte superiore del riquadro Cronologia.  È anche possibile visualizzare i dettagli per un periodo di tempo specifico selezionando 1 settimana, 1 mese o 1 anno.  I grafici cronologici possono aiutarti a identificare le tendenze: ad esempio, se l'utilizzo aggregato supera costantemente la soglia "Quasi pieno", puoi adottare le misure appropriate.

I grafici cronologici mostrano le seguenti informazioni:

* *Capacità aggregata utilizzata (%)*
+
Visualizza la capacità utilizzata nell'aggregato e l'andamento del modo in cui la capacità aggregata viene utilizzata in base alla cronologia di utilizzo come grafici a linee, in percentuale, sull'asse verticale (y).  Il periodo di tempo è visualizzato sull'asse orizzontale (x).  È possibile selezionare un periodo di tempo di una settimana, un mese o un anno.  È possibile visualizzare i dettagli di punti specifici sul grafico posizionando il cursore su un'area specifica.  È possibile nascondere o visualizzare un grafico a linee facendo clic sulla legenda appropriata.  Ad esempio, quando si fa clic sulla legenda Capacità utilizzata, la linea del grafico Capacità utilizzata viene nascosta.

* *Capacità aggregata utilizzata rispetto alla capacità totale*
+
Visualizza l'andamento dell'utilizzo della capacità aggregata in base alla cronologia di utilizzo, nonché la capacità utilizzata e la capacità totale, sotto forma di grafici lineari, in byte, kilobyte, megabyte e così via, sull'asse verticale (y).  Il periodo di tempo è visualizzato sull'asse orizzontale (x).  È possibile selezionare un periodo di tempo di una settimana, un mese o un anno.  È possibile visualizzare i dettagli di punti specifici sul grafico posizionando il cursore su un'area specifica.  È possibile nascondere o visualizzare un grafico a linee facendo clic sulla legenda appropriata.  Ad esempio, quando si fa clic sulla legenda Capacità di tendenza utilizzata, la linea del grafico Capacità di tendenza utilizzata viene nascosta.

* *Capacità aggregata utilizzata (%) rispetto a quella impegnata (%)*
+
Visualizza l'andamento dell'utilizzo della capacità aggregata in base alla cronologia di utilizzo, nonché lo spazio impegnato sotto forma di grafici a linee, in percentuale, sull'asse verticale (y).  Il periodo di tempo è visualizzato sull'asse orizzontale (x).  È possibile selezionare un periodo di tempo di una settimana, un mese o un anno.  È possibile visualizzare i dettagli di punti specifici sul grafico posizionando il cursore su un'area specifica.  È possibile nascondere o visualizzare un grafico a linee facendo clic sulla legenda appropriata.  Ad esempio, quando si fa clic sulla legenda Spazio impegnato, la linea del grafico Spazio impegnato viene nascosta.





== Elenco degli eventi

L'elenco Eventi mostra i dettagli sugli eventi nuovi e riconosciuti:

* *Gravità*
+
Visualizza la gravità dell'evento.

* *Evento*
+
Visualizza il nome dell'evento.

* *Tempo di attivazione*
+
Visualizza il tempo trascorso da quando è stato generato l'evento.  Se il tempo trascorso supera una settimana, viene visualizzato il timestamp del momento in cui è stato generato l'evento.





== Riquadro Dispositivi correlati

Il riquadro Dispositivi correlati consente di visualizzare i nodi del cluster, i volumi e i dischi correlati all'aggregato:

* *Nodo*
+
Visualizza la capacità e lo stato di integrità del nodo che contiene l'aggregato.  La capacità indica la capacità totale utilizzabile rispetto alla capacità disponibile.

* *Aggregati nel nodo*
+
Visualizza il numero e la capacità di tutti gli aggregati nel nodo cluster che contiene l'aggregato selezionato.  Viene visualizzato anche lo stato di salute degli aggregati, in base al livello di gravità più elevato.  Ad esempio, se un nodo del cluster contiene dieci aggregati, cinque dei quali visualizzano lo stato Avviso e i restanti cinque visualizzano lo stato Critico, lo stato visualizzato è Critico.

* *Volumi*
+
Visualizza il numero e la capacità dei volumi FlexVol e FlexGroup in forma aggregata; il numero non include i componenti FlexGroup .  Viene visualizzato anche lo stato di integrità dei volumi, in base al livello di gravità più elevato.

* *Pool di risorse*
+
Visualizza i pool di risorse correlati all'aggregato.

* *Dischi*
+
Visualizza il numero di dischi nell'aggregato selezionato.





== Riquadro Avvisi correlati

Il riquadro Avvisi correlati consente di visualizzare l'elenco degli avvisi creati per l'aggregato selezionato.  È anche possibile aggiungere un avviso cliccando sul link Aggiungi avviso oppure modificare un avviso esistente cliccando sul nome dell'avviso.

*Informazioni correlate*

link:../health-checker/task_view_storage_pool_details.html["Visualizzazione dei dettagli del pool di archiviazione"]
