---
permalink: health-checker/task_delete_snapshot_copies.html 
sidebar: sidebar 
keywords: delete, snapshot copies 
summary: È possibile eliminare una copia Snapshot per risparmiare spazio o liberare spazio sul disco, oppure è possibile eliminare la copia Snapshot se non è più necessaria. 
---
= Elimina le copie Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare una copia Snapshot per risparmiare spazio o liberare spazio sul disco, oppure è possibile eliminare la copia Snapshot se non è più necessaria.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Il volume deve essere online.

Per eliminare una copia Snapshot occupata o bloccata, è necessario aver rilasciato la copia Snapshot dall'applicazione che la stava utilizzando.

* Non è possibile eliminare la copia Snapshot di base in un volume padre se un volume FlexClone sta utilizzando tale copia Snapshot.
+
La copia Snapshot di base è la copia Snapshot utilizzata per creare il volume FlexClone e visualizza lo stato `Busy` e dipendenza dell'applicazione come `Busy, Vclone` nel volume padre.

* Non è possibile eliminare una copia Snapshot bloccata utilizzata in una relazione SnapMirror .
+
La copia Snapshot è bloccata ed è necessaria per il prossimo aggiornamento.



.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Volumi*.
. Nella vista *Integrità: Tutti i volumi*, seleziona il volume che contiene le copie Snapshot che desideri visualizzare.
+
Viene visualizzato l'elenco delle copie Snapshot.

. Nella pagina dei dettagli *Volume/Salute*, fare clic sulla scheda *Capacità*.
. Nel riquadro *Dettagli* della scheda *Capacità*, nella sezione Altri dettagli, fare clic sul collegamento accanto a *Copie snapshot*.
+
Il numero di copie Snapshot è un collegamento che visualizza l'elenco delle copie Snapshot.

. Nella vista *Copie snapshot*, seleziona le copie snapshot che desideri eliminare, quindi fai clic su *Elimina selezionati*.

