---
permalink: health-checker/task_edit_individual_aggregate_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, aggregate, health, threshold, settings 
summary: 'È possibile modificare le impostazioni della soglia di integrità per la capacità aggregata, la crescita e le copie Snapshot di uno o più aggregati.  Quando viene superata una soglia, vengono generati degli avvisi e si ricevono delle notifiche.  Queste notifiche ti aiutano ad adottare misure preventive in base all"evento generato.' 
---
= Modifica le impostazioni delle soglie di salute aggregate individuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni della soglia di integrità per la capacità aggregata, la crescita e le copie Snapshot di uno o più aggregati.  Quando viene superata una soglia, vengono generati degli avvisi e si ricevono delle notifiche.  Queste notifiche ti aiutano ad adottare misure preventive in base all'evento generato.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

In base alle modifiche ai valori soglia, gli eventi vengono generati o resi obsoleti nel ciclo di monitoraggio successivo.

Quando Autogrow è abilitato sui volumi che risiedono nell'aggregato, le soglie di capacità dell'aggregato vengono considerate superate in base alla dimensione massima del volume impostata da Autogrow, non in base alla dimensione del volume originale.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Aggregati*.
. Nella vista *Salute: Tutti gli aggregati*, seleziona uno o più aggregati e poi fai clic su *Modifica soglie*.
. Nella finestra di dialogo *Modifica soglie aggregate*, modificare le impostazioni della soglia di una delle seguenti: capacità, crescita o copie Snapshot selezionando la casella di controllo appropriata e quindi modificando le impostazioni.
. Fare clic su *Salva*.


*Informazioni correlate*

link:../config/task_add_users.html["Aggiunta di utenti"]
