---
permalink: health-checker/task_view_health_and_capacity_status_of_all_san_array_clusters.html 
sidebar: sidebar 
keywords: view, all san array, health and capacity, clusters 
summary: È possibile utilizzare le pagine Inventario cluster per visualizzare lo stato di integrità e capacità di tutti i cluster SAN Array. 
---
= Visualizza lo stato di integrità e capacità di tutti i cluster SAN Array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare le pagine Inventario cluster per visualizzare lo stato di integrità e capacità di tutti i cluster SAN Array.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

È possibile visualizzare informazioni generali per tutti i cluster SAN Array nella vista Integrità: Tutti i cluster e nella vista Capacità: Tutti i cluster.  Inoltre, è possibile visualizzare i dettagli nella pagina Dettagli cluster/stato.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Cluster*.
. Assicurarsi che la colonna "`Personalità`" sia visualizzata nella vista *Salute: Tutti i cluster* oppure aggiungerla utilizzando il controllo *Mostra / Nascondi*.
+
Questa colonna visualizza "`All SAN Array`" per i cluster All SAN Array.

. Rivedi le informazioni.
. Per visualizzare informazioni sulla capacità di archiviazione in tali cluster, selezionare la vista Capacità: Tutti i cluster.
. Per visualizzare informazioni dettagliate sullo stato di integrità e sulla capacità di archiviazione in tali cluster, fare clic sul nome di un cluster All SAN Array.
+
Visualizza i dettagli nelle schede Integrità, Capacità e Nodi nella pagina Dettagli cluster/integrità


