---
permalink: health-checker/task_perform_suggested_remedial_actions_for_full_volume.html 
sidebar: sidebar 
keywords: perform, suggested, remedial actions, volume 
summary: 'Dopo aver ricevuto un evento di errore "Spazio volume pieno", puoi esaminare le azioni correttive suggerite nella pagina Dettagli evento e decidere di eseguirne una.' 
---
= Eseguire le azioni correttive suggerite per un volume completo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver ricevuto un evento di errore "`Spazio volume pieno`", puoi esaminare le azioni correttive suggerite nella pagina Dettagli evento e decidere di eseguirne una.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Un utente con qualsiasi ruolo può eseguire tutte le attività in questo flusso di lavoro che utilizzano Unified Manager.

In questo esempio, hai visualizzato un evento di errore Spazio volume pieno nella pagina dell'inventario di Unified ManagerEvent Management e hai fatto clic sul nome dell'evento.

Le possibili azioni correttive che potresti intraprendere per un volume intero includono quanto segue:

* Abilitazione dell'aumento automatico, della deduplicazione o della compressione sul volume
* Ridimensionamento o spostamento del volume
* Eliminazione o spostamento dei dati dal volume


Sebbene tutte queste azioni debbano essere eseguite da ONTAP System Manager o da ONTAP CLI, è possibile utilizzare Unified Manager per trovare le informazioni necessarie per determinare quali azioni intraprendere.

.Passi
. Dalla pagina dei dettagli *Evento*, fare clic sul nome del volume nel campo Origine per visualizzare i dettagli sul volume interessato.
. Nella pagina dei dettagli *Volume/Integrità*, fai clic su *Configurazione* e vedrai che la deduplicazione e la compressione sono già abilitate sul volume.
+
Decidi di ridimensionare il volume.

. Nel riquadro *Dispositivi correlati*, fare clic sul nome dell'aggregato di hosting per verificare se l'aggregato può ospitare un volume maggiore.
. Nella pagina dei dettagli *Aggregato/Stato*, puoi vedere che l'aggregato che ospita il volume completo ha sufficiente capacità non impegnata, quindi puoi utilizzare ONTAP System Manager per ridimensionare il volume, assegnandogli maggiore capacità.


*Informazioni correlate*

link:../events/reference_event_details_page.html["Pagina dei dettagli dell'evento"]
