---
permalink: health-checker/task_reorder_annotation_rules.html 
sidebar: sidebar 
keywords: reorder, annotation rules 
summary: 'È possibile modificare l"ordine in cui Unified Manager applica le regole di annotazione agli oggetti di archiviazione.  Le regole di annotazione vengono applicate agli oggetti di archiviazione in sequenza in base al loro rango.  Quando si configura una regola di annotazione, il grado è minimo.  Ma puoi modificare il grado della regola di annotazione in base alle tue esigenze.' 
---
= Riordina le regole di annotazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare l'ordine in cui Unified Manager applica le regole di annotazione agli oggetti di archiviazione.  Le regole di annotazione vengono applicate agli oggetti di archiviazione in sequenza in base al loro rango.  Quando si configura una regola di annotazione, il grado è minimo.  Ma puoi modificare il grado della regola di annotazione in base alle tue esigenze.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

È possibile selezionare una singola riga o più righe ed eseguire numerose operazioni di trascinamento della selezione per modificare il grado delle regole di annotazione.  Tuttavia, è necessario salvare le modifiche affinché la ridefinizione delle priorità venga visualizzata nella scheda Regole di annotazione.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Annotazioni*.
. Nella scheda *Regole di annotazione*, fare clic su *Riordina*.
. Nella finestra di dialogo *Riordina regola annotazione*, trascinare e rilasciare una o più righe per riorganizzare la sequenza delle regole di annotazione.
. Fare clic su *Salva*.
+
Per visualizzare il riordino è necessario salvare le modifiche.


