---
permalink: health-checker/task_restore_mysql_db_on_linux.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati.  È possibile ripristinare il database di Unified Manager su un sistema Red Hat Enterprise Linux locale o remoto utilizzando la console di manutenzione di Unified Manager. 
---
= Ripristinare un backup del database MySQL su un sistema Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati.  È possibile ripristinare il database di Unified Manager su un sistema Red Hat Enterprise Linux locale o remoto utilizzando la console di manutenzione di Unified Manager.

.Prima di iniziare
* È necessario disporre delle credenziali utente root per l'host Linux su cui è installato Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager è necessario disporre di un ID utente e di una password autorizzati.
* È necessario aver copiato il file di backup di Unified Manager e il contenuto della directory del repository del database nel sistema su cui verrà eseguita l'operazione di ripristino.
+
Si consiglia di copiare il file di backup nella directory predefinita/`data/ocum` -backup.  I file del repository del database devono essere copiati nel/`database-dumps-repo` sottodirectory sotto il/`ocum-backup` elenco.

* I file di backup devono essere di `.7z` tipo.


La funzionalità di ripristino è specifica della piattaforma e della versione.  È possibile ripristinare un backup di Unified Manager solo sulla stessa versione di Unified Manager.  È possibile ripristinare un file di backup Linux o un file di backup di un'appliance virtuale su un sistema Red Hat Enterprise Linux.

[TIP]
====
Se il nome della cartella di backup contiene uno spazio, è necessario includere il percorso assoluto o il percorso relativo tra virgolette doppie.

====
.Passi
. Se si esegue un ripristino su un nuovo server, dopo aver installato Unified Manager non avviare l'interfaccia utente né configurare cluster, utenti o impostazioni di autenticazione al termine dell'installazione.  Il file di backup inserisce queste informazioni durante il processo di ripristino.
. Utilizzando Secure Shell, connettersi all'indirizzo IP o al nome di dominio completo del sistema Unified Manager.
. Accedi al sistema con il nome utente di manutenzione (umadmin) e la password.
. Inserisci il comando `maintenance_console` e premere Invio.
. Nel *Menu principale* della console di manutenzione, immettere il numero per l'opzione *Backup e ripristino*.
. Immettere il numero per il *Ripristino backup MySQL*.
. Quando richiesto, immettere il percorso assoluto del file di backup.
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
Una volta completata l'operazione di ripristino, è possibile accedere a Unified Manager.



Dopo aver ripristinato il backup, se il server OnCommand Workflow Automation non funziona, procedere come segue:

. Sul server Workflow Automation, modificare l'indirizzo IP del server Unified Manager in modo che punti alla macchina più recente.
. Sul server Unified Manager, reimpostare la password del database se l'acquisizione non riesce nel passaggio 1.

