---
permalink: health-checker/task_delete_group_actions.html 
sidebar: sidebar 
keywords: delete, group actions 
summary: 'È possibile eliminare un"azione di gruppo da Unified Manager quando non è più necessaria.' 
---
= Elimina azioni di gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare un'azione di gruppo da Unified Manager quando non è più necessaria.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Quando si elimina l'azione di gruppo per la soglia di integrità del volume, le soglie globali vengono applicate agli oggetti di archiviazione in quel gruppo.  Le soglie di integrità a livello di oggetto impostate sull'oggetto di archiviazione non sono interessate.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Gruppi*.
. Nella scheda *Azioni di gruppo*, seleziona l'azione di gruppo che desideri eliminare, quindi fai clic su *Elimina*.
. Nella finestra di dialogo *Avviso*, confermare l'eliminazione facendo clic su *Sì*.

