---
permalink: health-checker/task_reorder_group_actions.html 
sidebar: sidebar 
keywords: reorder, group actions 
summary: 'È possibile modificare l"ordine delle azioni di gruppo da applicare agli oggetti di archiviazione in un gruppo.  Le azioni di gruppo vengono applicate agli oggetti di archiviazione in sequenza in base al loro grado.  Il grado più basso viene assegnato all"azione di gruppo configurata per ultima.  È possibile modificare il grado dell"azione di gruppo in base alle proprie esigenze.' 
---
= Riordina le azioni di gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare l'ordine delle azioni di gruppo da applicare agli oggetti di archiviazione in un gruppo.  Le azioni di gruppo vengono applicate agli oggetti di archiviazione in sequenza in base al loro grado.  Il grado più basso viene assegnato all'azione di gruppo configurata per ultima.  È possibile modificare il grado dell'azione di gruppo in base alle proprie esigenze.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

È possibile selezionare una singola riga o più righe e quindi eseguire più operazioni di trascinamento della selezione per modificare il grado delle azioni di gruppo.  Tuttavia, è necessario salvare le modifiche affinché la ridefinizione delle priorità venga riflessa nella griglia delle azioni del gruppo.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Gruppi*.
. Nella scheda *Azioni di gruppo*, fare clic su *Riordina*.
. Nella finestra di dialogo *Riordina azioni di gruppo*, trascinare e rilasciare le righe per riorganizzare la sequenza delle azioni di gruppo come desiderato.
. Fare clic su *Salva*.

