---
permalink: health-checker/task_configure_windows_host_machine.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies windows, configure, windows host machine 
summary: 'È necessario configurare il computer host Windows prima di poter utilizzare NetApp Snapshot per eseguire il backup e il ripristino Active IQ Unified Manager.  Per avviare l"iniziatore iSCSI Microsoft su un computer host Windows, digitare "iscsi" nella barra di ricerca e fare clic su Iniziatore iSCSI.' 
---
= Configurare la macchina host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare il computer host Windows prima di poter utilizzare NetApp Snapshot per eseguire il backup e il ripristino Active IQ Unified Manager.  Per avviare l'iniziatore iSCSI Microsoft su un computer host Windows, digitare "`iscsi`" nella barra di ricerca e fare clic su *iSCSI Initiator*.

.Prima di iniziare
Dovresti ripulire tutte le configurazioni precedenti sulla macchina host.

Se si tenta di avviare l'iniziatore iSCSI su una nuova installazione di Windows, verrà richiesta una conferma e, una volta confermata, verrà visualizzata la finestra di dialogo Proprietà iSCSI.  Se si tratta di un'installazione Windows esistente, la finestra di dialogo Proprietà iSCSI viene visualizzata con una destinazione inattiva o che sta tentando di connettersi.  Pertanto, sarà necessario assicurarsi che tutte le configurazioni precedenti sull'host Windows vengano rimosse.

.Passi
. Pulire tutte le configurazioni precedenti sulla macchina host.
. Scopri il portale di destinazione.
. Connettiti al portale di destinazione.
. Connettersi tramite multipath al portale di destinazione.
. Scopri entrambi i LIF.
. Scopri il LUN configurato nel computer Windows come dispositivo.
. Configurare il LUN rilevato come nuova unità di volume in Windows.

