---
permalink: health-checker/task_resolve_capacity_issues.html 
sidebar: sidebar 
keywords: resolve, capacity issues 
summary: Questo flusso di lavoro fornisce un esempio di come è possibile risolvere un problema di capacità.  In questo scenario, sei un amministratore o un operatore e accedi alla pagina Dashboard di Unified Manager per verificare se uno degli oggetti di archiviazione monitorati presenta problemi di capacità.  Vuoi determinare la possibile causa del problema e la sua possibile soluzione. 
---
= Risolvere i problemi di capacità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo flusso di lavoro fornisce un esempio di come è possibile risolvere un problema di capacità.  In questo scenario, sei un amministratore o un operatore e accedi alla pagina Unified ManagerDashboard per verificare se uno degli oggetti di archiviazione monitorati presenta problemi di capacità.  Vuoi determinare la possibile causa del problema e la sua possibile soluzione.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

Nella pagina Dashboard, cercare un evento di errore "`Spazio volume pieno`" nel pannello Capacità sotto l'elenco a discesa degli eventi.

.Passi
. Nel pannello *Capacità* della pagina *Dashboard*, fare clic sul nome dell'evento di errore Spazio volume pieno.
+
Viene visualizzata la pagina dei dettagli dell'evento relativo all'errore.

. Dalla pagina dei dettagli dell'*Evento*, puoi eseguire una o più delle seguenti attività:
+
** Esaminare il messaggio di errore nel campo Causa e fare clic sui suggerimenti in Azioni correttive suggerite per esaminare le descrizioni delle possibili soluzioni.
** Fare clic sul nome dell'oggetto, in questo caso un volume, nel campo Origine per ottenere dettagli sull'oggetto.
** Cerca le note che potrebbero essere state aggiunte su questo evento.
** Aggiungi una nota all'evento.
** Assegna l'evento a un altro utente.
** Riconosci l'evento.
** Contrassegna l'evento come risolto.




*Informazioni correlate*

link:../events/reference_event_details_page.html["Pagina dei dettagli dell'evento"]
