---
permalink: health-checker/task_perform_corrective_action_for_storage_failover_interconnect_links.html 
sidebar: sidebar 
keywords: perform, corrective action, storage failover, interconnect links 
summary: 'Quando si visualizza la pagina Dettagli evento di un evento correlato al failover dell"archiviazione, è possibile esaminare le informazioni di riepilogo della pagina per determinare l"urgenza dell"evento, la possibile causa del problema e la possibile soluzione al problema.' 
---
= Eseguire un'azione correttiva per i collegamenti di interconnessione del failover di archiviazione inattivi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si visualizza la pagina Dettagli evento di un evento correlato al failover dell'archiviazione, è possibile esaminare le informazioni di riepilogo della pagina per determinare l'urgenza dell'evento, la possibile causa del problema e la possibile soluzione al problema.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

In questo scenario di esempio, il riepilogo dell'evento fornito nella pagina Dettagli evento contiene le seguenti informazioni sulla condizione di inattività del collegamento di interconnessione del failover di archiviazione:

[listing]
----
Event: Storage Failover Interconnect One or More Links Down

Summary

Severity: Warning
State: New
Impact Level: Risk
Impact Area: Availability
Source: aardvark
Source Type: Node
Acknowledged By:
Resolved By:
Assigned To:
Cause: At least one storage failover interconnected link
       between the nodes aardvark and bonobo is down.
       RDMA interconnect is up (Link0 up, Link1 down)
----
Le informazioni sull'evento di esempio indicano che un collegamento di interconnessione di failover di archiviazione, Link1, tra i nodi della coppia HA aardvark e bonobo è inattivo, ma che Link0 tra Apple e Boy è attivo.  Poiché un collegamento è attivo, l'accesso alla memoria dinamica remota (RDMA) è ancora funzionante e un processo di failover dell'archiviazione può ancora avere esito positivo.

Tuttavia, per evitare che entrambi i collegamenti falliscano e che la protezione failover dello storage venga completamente disattivata, si decide di diagnosticare ulteriormente il motivo per cui Link1 non funziona.

.Passi
. Dalla pagina dei dettagli *Evento*, è possibile fare clic sul collegamento all'evento specificato nel campo Origine per ottenere ulteriori dettagli su altri eventi che potrebbero essere correlati alla condizione di inattività del collegamento di interconnessione del failover di archiviazione.
+
In questo esempio, l'origine dell'evento è il nodo denominato aardvark.  Facendo clic sul nome del nodo vengono visualizzati i dettagli HA per la coppia HA interessata, aardvark e bonobo, nella scheda Nodi della pagina Dettagli cluster/stato e vengono visualizzati altri eventi che si sono verificati di recente sulla coppia HA interessata.

. Per maggiori informazioni relative all'evento, consultare i *Dettagli HA*.
+
In questo esempio, le informazioni rilevanti si trovano nella tabella Eventi.  La tabella mostra l'evento "`Storage Failover Connection One or More Link Down`", l'ora in cui è stato generato l'evento e, ancora una volta, il nodo da cui ha avuto origine l'evento.



Utilizzando le informazioni sulla posizione del nodo nei dettagli HA, richiedere o completare personalmente un'ispezione fisica e la riparazione del problema di failover dell'archiviazione sui nodi della coppia HA interessati.

*Informazioni correlate*

link:../events/reference_event_details_page.html["Pagina dei dettagli dell'evento"]

link:../config/reference_unified_manager_roles_and_capabilities.html["Ruoli e capacità degli utenti di Unified Manager"]
