---
permalink: health-checker/task_view_aggregate_list_and_details.html 
sidebar: sidebar 
keywords: view, aggregate list, details 
summary: 'Dalla vista Salute: Tutti gli aggregati, puoi monitorare il tuo inventario di aggregati.  La vista Capacità: tutti gli aggregati consente di visualizzare informazioni sulla capacità e sull"utilizzo degli aggregati in tutti i cluster.' 
---
= Visualizza l'elenco aggregato e i dettagli
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla vista Salute: Tutti gli aggregati, puoi monitorare il tuo inventario di aggregati.  La vista Capacità: tutti gli aggregati consente di visualizzare informazioni sulla capacità e sull'utilizzo degli aggregati in tutti i cluster.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

È possibile visualizzare dettagli quali capacità e configurazione aggregate e informazioni sul disco nella pagina Dettagli aggregati/integrità.  Se necessario, è possibile utilizzare questi dettagli prima di configurare le impostazioni della soglia.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Aggregati*.
. Per visualizzare i dettagli aggregati, scegli uno dei seguenti metodi:
+
** Per visualizzare informazioni sullo stato di integrità di tutti gli aggregati in tutti i cluster, nel menu Visualizza, selezionare Integrità: vista Tutti gli aggregati.
** Per visualizzare informazioni sulla capacità e l'utilizzo di tutti gli aggregati in tutti i cluster, nel menu Visualizza, selezionare Capacità: vista Tutti gli aggregati.
** Per visualizzare i dettagli completi, fare clic sul nome dell'aggregato.
+
È anche possibile visualizzare i dettagli completi cliccando su *Visualizza dettagli* nella finestra di dialogo dei dettagli minimi.



. Visualizza gli oggetti correlati all'aggregato facendo clic su *Visualizza correlati* nella finestra di dialogo dei dettagli minimi.


*Informazioni correlate*

* link:../health-checker/reference_health_aggregate_details_page.html["Pagina dei dettagli aggregati/sanitari"]
* link:../performance-checker/performance-view-all.html#performance-all-aggregates-view["Prestazioni: visualizzazione di tutti gli aggregati"]
* link:../reporting/concept_customize_aggregate_capacity_reports.html["Personalizzazione dei report sulla capacità aggregata"]

