---
permalink: health-checker/task_disable_specific_security_events.html 
sidebar: sidebar 
keywords: disable, specific, security events 
summary: Tutti gli eventi sono abilitati per impostazione predefinita.  È possibile disabilitare eventi specifici per impedire la generazione di notifiche per quegli eventi che non sono importanti nel proprio ambiente.  È possibile abilitare gli eventi disabilitati se si desidera riprendere a ricevere le relative notifiche. 
---
= Disabilitare eventi di sicurezza specifici
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tutti gli eventi sono abilitati per impostazione predefinita.  È possibile disabilitare eventi specifici per impedire la generazione di notifiche per quegli eventi che non sono importanti nel proprio ambiente.  È possibile abilitare gli eventi disabilitati se si desidera riprendere a ricevere le relative notifiche.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Quando si disabilitano gli eventi, gli eventi generati in precedenza nel sistema vengono contrassegnati come obsoleti e gli avvisi configurati per tali eventi non vengono attivati.  Quando si abilitano eventi disabilitati, le notifiche per questi eventi vengono generate a partire dal ciclo di monitoraggio successivo.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Configurazione evento*.
. Nella pagina Impostazione *Evento*, disabilita o abilita gli eventi scegliendo una delle seguenti opzioni:
+
[cols="2*"]
|===
| Se lo desidera... | Allora fai così... 


 a| 
Disabilitare gli eventi
 a| 
.. Fare clic su *Disabilita*.
.. Nella finestra di dialogo Disabilita eventi, selezionare la gravità *Avviso*.  Questa è la categoria per tutti gli eventi di sicurezza.
.. Nella colonna Eventi corrispondenti, seleziona gli eventi di sicurezza che desideri disabilitare, quindi fai clic sulla freccia destra per spostare tali eventi nella colonna Disabilita eventi.
.. Fare clic su *Salva e chiudi*.
.. Verificare che gli eventi disabilitati siano visualizzati nella vista elenco della pagina Impostazione evento.




 a| 
Abilita eventi
 a| 
.. Dall'elenco degli eventi disabilitati, seleziona la casella di controllo relativa all'evento o agli eventi che desideri riabilitare.
.. Fare clic su *Abilita*.


|===

