---
permalink: health-checker/task_view_fabricpool_capacity_information.html 
sidebar: sidebar 
keywords: view, fabricPool, cloud tier, mirror tier, capacity, information 
summary: È possibile visualizzare le informazioni sulla capacità FabricPool per cluster, aggregati e volumi nelle pagine di inventario e dettagli Capacità e Prestazioni per questi oggetti.  Queste pagine visualizzano anche le informazioni sul mirror FabricPool quando è stato configurato un livello mirror. 
---
= Visualizza le informazioni sulla capacità FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare le informazioni sulla capacità FabricPool per cluster, aggregati e volumi nelle pagine di inventario e dettagli Capacità e Prestazioni per questi oggetti.  Queste pagine visualizzano anche le informazioni sul mirror FabricPool quando è stato configurato un livello mirror.

Queste pagine visualizzano informazioni quali la capacità disponibile sul livello di prestazioni locale e sul livello cloud, la quantità di capacità utilizzata in entrambi i livelli, quali aggregati sono collegati a un livello cloud e quali volumi implementano le funzionalità FabricPool spostando determinate informazioni sul livello cloud.

Quando un livello cloud viene replicato su un altro provider cloud (il "livello mirror"), entrambi i livelli cloud vengono visualizzati nella pagina dei dettagli Aggregati/Stato.

.Passi
. Eseguire una delle seguenti operazioni:
+
[cols="2*"]
|===
| Per visualizzare le informazioni sulla capacità per... | Fai questo... 


 a| 
Cluster
 a| 
.. Nella vista Capacità: Tutti i cluster, fare clic su un cluster.
.. Nella pagina dei dettagli Cluster/Stato, fare clic sulla scheda *Configurazione*.
+
Il display mostra i nomi di tutti i livelli cloud a cui è connesso questo cluster.





 a| 
Aggregati
 a| 
.. Nella vista Capacità: Tutti gli aggregati, fare clic su un aggregato in cui il campo Tipo indica "`SSD (FabricPool)`" o "`HDD (FabricPool)`".
.. Nella pagina dei dettagli Aggregati/Salute, fare clic sulla scheda *Capacità*.
+
Il display mostra la capacità totale utilizzata nel livello cloud.

.. Fare clic sulla scheda *Informazioni disco*.
+
Il display mostra il nome del livello cloud e la capacità utilizzata.

.. Fare clic sulla scheda *Configurazione*.
+
Il display mostra il nome del livello cloud e altre informazioni dettagliate sul livello cloud.





 a| 
Volumi
 a| 
.. Nella vista Capacità: Tutti i volumi, fare clic su un volume in cui appare un nome di policy nel campo "`Tiering Policy`".
.. Nella pagina Dettagli volume/integrità, fare clic sulla scheda *Configurazione*.
+
Nella schermata viene visualizzato il nome del criterio di suddivisione in livelli FabricPool assegnato al volume.



|===
. Nella pagina *Analisi del carico di lavoro* è possibile selezionare "`Cloud Tier View`" nell'area *Capacity Trend* per visualizzare la capacità utilizzata nel Performance Tier locale e nel Cloud Tier nel mese precedente.


Per ulteriori informazioni sugli aggregati FabricPool , vedere https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["Panoramica dei dischi e degli aggregati"] .
