---
permalink: health-checker/task_retrieve_support_bundle_using_windows_client.html 
sidebar: sidebar 
keywords: retrieve, support bundle, windows client 
summary: Se sei un utente Windows, puoi scaricare e installare uno strumento per recuperare il pacchetto di supporto dal tuo server Unified Manager.  È possibile inviare il pacchetto di supporto al supporto tecnico per una diagnosi più dettagliata di un problema.  Filezilla o WinSCP sono esempi di strumenti che puoi utilizzare. 
---
= Recupera il pacchetto di supporto utilizzando un client Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se sei un utente Windows, puoi scaricare e installare uno strumento per recuperare il pacchetto di supporto dal tuo server Unified Manager.  È possibile inviare il pacchetto di supporto al supporto tecnico per una diagnosi più dettagliata di un problema.  Filezilla o WinSCP sono esempi di strumenti che puoi utilizzare.

.Prima di iniziare
Per eseguire questa attività è necessario essere un utente addetto alla manutenzione.

È necessario utilizzare uno strumento che supporti SCP o SFTP.

.Passi
. Scarica e installa uno strumento per recuperare il pacchetto di supporto.
. Aprire lo strumento.
. Connettiti al tuo server di gestione Unified Manager tramite SFTP.
+
Lo strumento visualizza il contenuto della directory /support e consente di visualizzare tutti i pacchetti di supporto esistenti.

. Selezionare la directory di destinazione per il pacchetto di supporto che si desidera copiare.
. Seleziona il pacchetto di supporto che desideri copiare e utilizza lo strumento per copiare il file dal server Unified Manager al tuo sistema locale.

