---
permalink: health-checker/task_delete_annotations.html 
sidebar: sidebar 
keywords: delete, annotations 
summary: È possibile eliminare le annotazioni personalizzate e i relativi valori quando non sono più necessari. 
---
= Elimina annotazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare le annotazioni personalizzate e i relativi valori quando non sono più necessari.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* I valori di annotazione non devono essere utilizzati in altre annotazioni o regole di gruppo.


.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Annotazioni*.
. Nella scheda *Annotazioni*, seleziona l'annotazione che desideri eliminare.
+
Vengono visualizzati i dettagli dell'annotazione selezionata.

. Fare clic su *Azioni* > *Elimina* per eliminare l'annotazione selezionata e il relativo valore.
. Nella finestra di dialogo di avviso, fare clic su *Sì* per confermare l'eliminazione.

