---
permalink: health-checker/task_delete_values_from_annotations.html 
sidebar: sidebar 
keywords: delete, values, annotations 
summary: 'È possibile eliminare i valori associati alle annotazioni personalizzate quando tali valori non sono più applicabili all"annotazione.' 
---
= Elimina i valori dalle annotazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare i valori associati alle annotazioni personalizzate quando tali valori non sono più applicabili all'annotazione.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* Il valore di annotazione non deve essere associato ad alcuna regola di annotazione o regola di gruppo.


Non è possibile eliminare i valori dalle annotazioni predefinite.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Annotazioni*.
. Nell'elenco delle annotazioni nella scheda *Annotazioni*, seleziona l'annotazione da cui desideri eliminare un valore.
. Nell'area *Valori* della scheda *Annotazioni*, seleziona il valore che desideri eliminare, quindi fai clic su *Elimina*.
. Nella finestra di dialogo *Avviso*, fare clic su *Sì*.
+
Il valore viene eliminato e non viene più visualizzato nell'elenco dei valori per l'annotazione selezionata.


