---
permalink: health-checker/task_view_all_security_events.html 
sidebar: sidebar 
keywords: view, active, security events 
summary: È possibile visualizzare tutti gli eventi di sicurezza attivi e quindi assegnare ciascuno di essi a un utente in grado di risolvere il problema.  Inoltre, se ci sono determinati eventi di sicurezza che non desideri ricevere, questo elenco può aiutarti a identificare gli eventi che vuoi disabilitare. 
---
= Visualizza tutti gli eventi di sicurezza attivi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare tutti gli eventi di sicurezza attivi e quindi assegnare ciascuno di essi a un utente in grado di risolvere il problema.  Inoltre, se ci sono determinati eventi di sicurezza che non desideri ricevere, questo elenco può aiutarti a identificare gli eventi che vuoi disabilitare.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione eventi*.
+
Per impostazione predefinita, gli eventi Nuovi e Riconosciuti vengono visualizzati nella pagina dell'inventario Gestione eventi.

. Dal menu Visualizza, seleziona *Eventi di sicurezza attivi*.
+
La pagina visualizza tutti gli eventi di sicurezza nuovi e riconosciuti generati negli ultimi 7 giorni.


