---
permalink: health-checker/task_restore_mysql_database_backup_on_windows.html 
sidebar: sidebar 
keywords: restore, windows, mysql, database, backup 
summary: In caso di perdita o danneggiamento dei dati, è possibile utilizzare la funzionalità di ripristino per riportare Unified Manager allo stato stabile precedente con una perdita minima.  È possibile ripristinare il database MySQL di Unified Manager su un sistema Windows locale o remoto utilizzando la console di manutenzione di Unified Manager. 
---
= Ripristinare un backup del database MySQL su Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In caso di perdita o danneggiamento dei dati, è possibile utilizzare la funzionalità di ripristino per riportare Unified Manager allo stato stabile precedente con una perdita minima.  È possibile ripristinare il database MySQL di Unified Manager su un sistema Windows locale o remoto utilizzando la console di manutenzione di Unified Manager.

.Prima di iniziare
* È necessario disporre dei privilegi di amministratore di Windows.
* È necessario aver copiato il file di backup di Unified Manager e il contenuto della directory del repository del database nel sistema su cui verrà eseguita l'operazione di ripristino.
+
Si consiglia di copiare il file di backup nella directory predefinita `\ProgramData\NetApp\OnCommandAppData\ocum\backup` .  I file del repository del database devono essere copiati nel `\database_dumps_repo` sottodirectory sotto il `\backup` elenco.

* I file di backup devono essere di `.7z` tipo.


La funzionalità di ripristino è specifica della piattaforma e della versione.  È possibile ripristinare un backup MySQL di Unified Manager solo sulla stessa versione di Unified Manager, mentre un backup di Windows può essere ripristinato solo su una piattaforma Windows.

[TIP]
====
Se i nomi delle cartelle contengono uno spazio, è necessario includere il percorso assoluto o il percorso relativo del file di backup tra virgolette doppie.

====
.Passi
. Se si esegue un ripristino su un nuovo server, dopo aver installato Unified Manager non avviare l'interfaccia utente né configurare cluster, utenti o impostazioni di autenticazione al termine dell'installazione.  Il file di backup inserisce queste informazioni durante il processo di ripristino.
. Accedi al sistema Unified Manager con le credenziali di amministratore.
. Avvia PowerShell o il prompt dei comandi come amministratore di Windows.
. Inserisci il comando `maintenance_console` e premere Invio.
. Nel *Menu principale* della console di manutenzione, immettere il numero per l'opzione *Backup e ripristino*.
. Immettere il numero per il *Ripristino backup MySQL*.
. Quando richiesto, immettere il percorso assoluto del file di backup.
+
[listing]
----
Bundle to restore from: \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.8.N151118.2300_backup_windows_02-20-2020-02-51.7z
----
+
Una volta completata l'operazione di ripristino, è possibile accedere a Unified Manager.



Dopo aver ripristinato il backup, se il server OnCommand Workflow Automation non funziona, procedere come segue:

. Sul server Workflow Automation, modificare l'indirizzo IP del server Unified Manager in modo che punti alla macchina più recente.
. Sul server Unified Manager, reimpostare la password del database se l'acquisizione non riesce nel passaggio 1.

