---
permalink: health-checker/task_create_volume_where_backups_are_stored.html 
sidebar: sidebar 
keywords: configure, snapshot copy, copies location 
summary: È possibile configurare il volume in cui verranno archiviate le copie Snapshot su uno dei cluster ONTAP utilizzando ONTAP System Manager o ONTAP CLI. 
---
= Configurare la posizione della copia dello snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare il volume in cui verranno archiviate le copie Snapshot su uno dei cluster ONTAP utilizzando ONTAP System Manager o ONTAP CLI.

.Prima di iniziare
Il cluster, la VM di archiviazione e il volume devono soddisfare i seguenti requisiti:

* Requisiti del cluster:
+
** È necessario installare ONTAP 9.3 o versione successiva
** Dovrebbe essere geograficamente vicino al server Unified Manager
** Può essere monitorato da Unified Manager, ma non è obbligatorio


* Requisiti della VM di archiviazione:
+
** Il cambio nome e la mappatura dei nomi devono essere impostati per utilizzare "`files`"
** Utenti locali creati per corrispondere con gli utenti lato client
** Assicurati che sia selezionato l'accesso in lettura/scrittura completo
** Assicurati che l'accesso Superuser sia impostato su "`any`" nella policy di esportazione
** NFS per NetApp Snapshot per Linux
** NFSv4 deve essere abilitato sul server NFS e sul dominio ID NFSv4 specificato sul client e sulla VM di archiviazione
** Il volume dovrebbe essere almeno il doppio della dimensione della directory Unified Manager/opt/netapp/data
+
Utilizzare il comando du -sh /opt/netapp/data/ per verificare la dimensione corrente.



* Requisiti di volume:
+
** Il volume dovrebbe essere almeno il doppio della dimensione della directory /opt/netapp/data di Unified Manager
** Lo stile di sicurezza deve essere impostato su UNIX
** Il criterio di snapshot locale deve essere disabilitato
** Il dimensionamento automatico del volume dovrebbe essere abilitato
** Il livello di servizio delle prestazioni dovrebbe essere impostato su una politica con IOPS elevati e bassa latenza, ad esempio "`Extreme`"




Per i passaggi dettagliati per creare il volume NFS, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["Come configurare NFSv4 in ONTAP 9"] e il http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["Guida rapida alla configurazione NFS ONTAP 9"] .
