---
permalink: health-checker/task_generate_hardware_inventory_report_for_contract_renewal.html 
sidebar: sidebar 
keywords: contract, renewal, cluster, inventory report, hardware, generate 
summary: 'È possibile generare un report contenente un elenco completo delle informazioni sui cluster e sui nodi, ad esempio numeri di modello e numeri di serie dell"hardware, tipi e conteggi dei dischi, licenze installate e altro ancora.  Questo report è utile per il rinnovo dei contratti all"interno di siti sicuri (siti "oscuri") che non sono connessi alla piattaforma NetAppActive IQ.' 
---
= Generare un report di inventario hardware per il rinnovo del contratto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile generare un report contenente un elenco completo delle informazioni sui cluster e sui nodi, ad esempio numeri di modello e numeri di serie dell'hardware, tipi e conteggi dei dischi, licenze installate e altro ancora.  Questo report è utile per il rinnovo dei contratti all'interno di siti protetti (siti "oscuri") che non sono connessi alla piattaforma NetAppActive IQ.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Nodi*.
. Vai alla vista *Integrità: Tutti i nodi* o alla vista *Prestazioni: Tutti i nodi*.
. Selezionare *Report* > *** > **Report inventario hardware*.
+
Il report dell'inventario hardware viene scaricato come file .csv con informazioni complete aggiornate alla data corrente.

. Fornisci queste informazioni al tuo referente dell'assistenza NetApp per il rinnovo del contratto.

