---
permalink: health-checker/task_calculate_reclaimable_space_for_snapshot_copies.html 
sidebar: sidebar 
keywords: calculate, reclaimable space, snapshot copies 
summary: È possibile calcolare la quantità di spazio su disco che può essere recuperata se vengono eliminate una o più copie Snapshot. 
---
= Calcola lo spazio recuperabile per le copie Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile calcolare la quantità di spazio su disco che può essere recuperata se vengono eliminate una o più copie Snapshot.

.Prima di iniziare
* È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.
* Il volume deve essere online.
* Il volume deve essere un FlexVol volume; questa funzionalità non è supportata con i volumi FlexGroup .


.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Volumi*.
. Nella vista *Integrità: Tutti i volumi*, seleziona il volume che contiene le copie Snapshot che desideri visualizzare.
+
Viene visualizzato l'elenco delle copie Snapshot.

. Nella pagina dei dettagli *Volume/Salute*, fare clic sulla scheda *Capacità*.
. Nel riquadro *Dettagli* della scheda *Capacità*, nella sezione Altri dettagli, fare clic sul collegamento accanto a *Copie snapshot*.
+
Il numero di copie Snapshot è un collegamento che visualizza l'elenco delle copie Snapshot.

. Nella vista *Copie snapshot*, seleziona le copie snapshot per le quali desideri calcolare lo spazio recuperabile.
. Fare clic su *Calcola*.
+
Viene visualizzato lo spazio recuperabile (in percentuale, KB, MB, GB e così via) sul volume.

. Per ricalcolare lo spazio recuperabile, selezionare le copie Snapshot desiderate e fare clic su *Ricalcola*.

