---
permalink: install-vapp/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, virtual appliance 
summary: 'L"installazione di Unified Manager su un"infrastruttura virtuale o su un sistema fisico deve soddisfare i requisiti minimi di memoria, CPU e spazio su disco.' 
---
= Requisiti di sistema hardware e infrastruttura virtuale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installazione di Unified Manager su un'infrastruttura virtuale o su un sistema fisico deve soddisfare i requisiti minimi di memoria, CPU e spazio su disco.

Nella tabella seguente sono riportati i valori consigliati per le risorse di memoria, CPU e spazio su disco.  Questi valori sono stati qualificati in modo che Unified Manager soddisfi livelli di prestazioni accettabili.

[cols="2*"]
|===
| Configurazione hardware | Impostazioni consigliate 


 a| 
Memoria RAM
 a| 
12 GB (requisito minimo 8 GB)



 a| 
Processori
 a| 
4 CPU



 a| 
Capacità del ciclo della CPU
 a| 
9572 MHz totali (requisito minimo 9572 MHz)



 a| 
Spazio libero su disco
 a| 
* 5 GB (con provisioning sottile)
* 152 GB (con provisioning spesso)


|===
Unified Manager può essere installato su sistemi con una piccola quantità di memoria, ma i 12 GB di RAM consigliati garantiscono che sia disponibile memoria sufficiente per prestazioni ottimali e che il sistema possa ospitare cluster e oggetti di archiviazione aggiuntivi man mano che la configurazione cresce.  Non dovresti impostare limiti di memoria sulla VM in cui è distribuito Unified Manager e non dovresti abilitare funzionalità (ad esempio, il ballooning) che impediscono al software di utilizzare la memoria allocata sul sistema.

Inoltre, esiste un limite al numero di nodi che una singola istanza di Unified Manager può monitorare prima di installare una seconda istanza di Unified Manager. Per maggiori informazioni, vedere link:https://www.netapp.com/pdf.html?item=/media/13504-tr4621pdf.pdf["Guida alle migliori pratiche di Unified Manager"^].

Lo scambio di pagine di memoria ha un impatto negativo sulle prestazioni del sistema e dell'applicazione di gestione.  La competizione per risorse della CPU non disponibili a causa dell'utilizzo complessivo dell'host può compromettere le prestazioni.



== Requisito per uso dedicato

Il sistema fisico o virtuale su cui si installa Unified Manager deve essere utilizzato esclusivamente per Unified Manager e non deve essere condiviso con altre applicazioni.  Altre applicazioni potrebbero consumare risorse di sistema e ridurre drasticamente le prestazioni di Unified Manager.



== Requisiti di spazio per i backup

Se si prevede di utilizzare la funzionalità di backup e ripristino di Unified Manager, allocare capacità aggiuntiva in modo che la directory o il disco "`data`" disponga di 150 GB di spazio.  Un backup può essere scritto su una destinazione locale o su una destinazione remota.  La procedura consigliata è quella di identificare una posizione remota esterna al sistema host di Unified Manager che disponga di almeno 150 GB di spazio.



== Requisiti per la connettività host

Il sistema fisico o virtuale su cui si installa Unified Manager deve essere configurato in modo tale da poterlo utilizzare correttamente `ping` il nome host dall'host stesso.  In caso di configurazione IPv6, è necessario verificare che `ping6` al nome host ha esito positivo per garantire la corretta installazione di Unified Manager.

È possibile utilizzare il nome host (o l'indirizzo IP host) per accedere all'interfaccia utente Web del prodotto.  Se hai configurato un indirizzo IP statico per la tua rete durante la distribuzione, hai designato un nome per l'host di rete.  Se hai configurato la rete tramite DHCP, dovresti ottenere il nome host dal DNS.

Se si prevede di consentire agli utenti di accedere a Unified Manager utilizzando il nome breve anziché il nome di dominio completo (FQDN) o l'indirizzo IP, la configurazione di rete deve risolvere questo nome breve in un FQDN valido.
