---
permalink: install-vapp/concept_requirements_for_installing_unified_manager.html 
sidebar: sidebar 
keywords: requirements, installing, unified, manager 
summary: Prima di iniziare il processo di installazione, assicurarsi che il server su cui si desidera installare Unified Manager soddisfi i requisiti specifici di software, hardware, CPU e memoria. 
---
= Requisiti per l'installazione di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di iniziare il processo di installazione, assicurarsi che il server su cui si desidera installare Unified Manager soddisfi i requisiti specifici di software, hardware, CPU e memoria.

NetApp non supporta alcuna modifica del codice applicativo di Unified Manager.  Se è necessario applicare misure di sicurezza al server Unified Manager, è necessario apportare tali modifiche al sistema operativo su cui è installato Unified Manager.

Per maggiori dettagli sull'applicazione delle misure di sicurezza al server Unified Manager, consultare l'articolo della Knowledge Base.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/Supportability_for_Security_Measures_applied_to_Active_IQ_Unified_Manager_for_Clustered_Data_ONTAP["Supporto per misure di sicurezza applicate ad Active IQ Unified Manager per Clustered Data ONTAP"]

*Informazioni correlate*

Per maggiori informazioni, vedere https://mysupport.netapp.com/matrix["Strumento matrice di interoperabilità NetApp"]
