---
permalink: install-vapp/task_upgrade_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager, virtual, appliance 
summary: 'È possibile aggiornare l"appliance virtuale Unified Manager' 
---
= Aggiorna l'appliance virtuale Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare l'appliance virtuale Active IQ Unified Manager dalle versioni 9.13 o 9.14 alla versione 9.16.

.Prima di iniziare
Assicurarsi che:

* Hai scaricato il file di aggiornamento, l'immagine ISO dal sito di supporto NetApp .
* Il sistema su cui si sta aggiornando Unified Manager soddisfa i requisiti di sistema e software.
+
Vederelink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisiti dell'infrastruttura virtuale"] .

+
Vederelink:reference_vmware_software_and_installation_requirements.html["Requisiti software e di installazione VMware"] .

* Per gli utenti di vSphere 6.5 e versioni successive, è stata installata VMware Remote Console (VMRC).
* Durante l'aggiornamento, potrebbe esserti richiesto di confermare se desideri mantenere le impostazioni predefinite precedenti per la conservazione dei dati sulle prestazioni per 13 mesi o modificarle in 6 mesi.  Dopo la conferma, i dati storici sulle prestazioni vengono eliminati dopo 6 mesi.
* Hai le seguenti informazioni:
+
** Credenziali di accesso per il sito di supporto NetApp
** Credenziali per l'accesso a VMware vCenter Server e vSphere Web Client
** Credenziali per l'utente addetto alla manutenzione di Unified Manager




Durante il processo di aggiornamento, Unified Manager non è disponibile.  Prima di aggiornare Unified Manager, è necessario completare tutte le operazioni in esecuzione.

Se hai associato Workflow Automation e Unified Manager, devi aggiornare manualmente il nome host in Workflow Automation.

.Passi
. In vSphere Client, fare clic su *Home* > *Inventario* > *VM e modelli*.
. Selezionare la macchina virtuale (VM) su cui è installato l'appliance virtuale Unified Manager.
. Se la VM Unified Manager è in esecuzione, accedere a *Riepilogo* > *Comandi* > *Arresta Guest*.
. Creare una copia di backup, ad esempio uno snapshot o un clone, della VM di Unified Manager per creare un backup coerente con l'applicazione.
. Da vSphere Client, accendere la VM Unified Manager.
. Avviare VMware Remote Console.
. Fare clic sull'icona *CDROM* e selezionare *Connetti al file immagine disco (.iso)*.
. Seleziona il `ActiveIQUnifiedManager-<version>-virtual-update.iso` file e fare clic su *Apri*.
. Fare clic sulla scheda *Console*.
. Accedi alla console di manutenzione di Unified Manager.
. Nel menu principale, seleziona *Aggiorna*.
+
Viene visualizzato un messaggio che informa che Unified Manager non sarà disponibile durante il processo di aggiornamento e che verrà ripreso al termine.

. Tipo `y` per continuare.
+
Viene visualizzato un avviso che ricorda di eseguire il backup della macchina virtuale su cui risiede l'appliance virtuale.

. Tipo `y` per continuare.
+
Il completamento del processo di aggiornamento e del riavvio dei servizi di Unified Manager può richiedere diversi minuti.

. Premere un tasto qualsiasi per continuare.
+
Verrai automaticamente disconnesso dalla console di manutenzione.

. *Facoltativo:* accedi alla console di manutenzione e verifica la versione di Unified Manager.


È possibile avviare l'interfaccia utente Web in una nuova finestra di un browser Web supportato ed effettuare l'accesso per utilizzare la versione aggiornata di Unified Manager.  Tieni presente che è necessario attendere il completamento del processo di individuazione prima di eseguire qualsiasi attività nell'interfaccia utente.
