---
permalink: install-windows/qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Guida rapida per Unified Manager sulla piattaforma Windows. 
---
= Istruzioni di avvio rapido per le installazioni di Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile scaricare il pacchetto di installazione e installare Unified Manager per monitorare e risolvere i problemi relativi a capacità di archiviazione dei dati, disponibilità, prestazioni e protezione.



== Requisiti di sistema

* Sistemi operativi
+
** Microsoft Windows Server 2019 Standard e Datacenter Edition
** Microsoft Windows Server 2022 Standard e Datacenter Edition
+
Unified Manager è supportato sul sistema operativo Windows a 64 bit per le seguenti lingue:

** Inglese
** giapponese
** cinese semplificato


* RAM: 12 GB
* CPU: 9572 MHz totali
* Spazio libero su disco: 100 GB di spazio su disco per la directory di installazione, 50 GB di spazio su disco per la directory dei dati MySQL


Per i requisiti di sistema dettagliati, vederelink:../install-windows/concept_requirements_for_installing_unified_manager.html["Requisiti per l'installazione di Unified Manager"] Elink:http://mysupport.netapp.com/matrix["Matrice di interoperabilità"^] .



== Installa Active IQ Unified Manager



=== Scarica il programma di installazione

. Scarica il `ActiveIQUnifiedManager-<version>.exe` pacchetto di installazione.
. Copiare il file di installazione in una directory sul sistema di destinazione.




=== Installa Unified Manager

Per installare Unified Manager, assicurati di avere installato Microsoft .NET 4.5.2 o una versione successiva.  Come parte del processo di installazione, Unified Manager installa altri pacchetti di terze parti, se necessario.  Per ulteriori informazioni sui pacchetti software dipendenti, fare riferimento alink:../install-windows/reference_windows_software_and_installation_requirements.html["Requisiti di installazione e software Windows"] .

. Accedi a Windows utilizzando l'account amministratore locale predefinito.
. Nella directory in cui hai scaricato il file di installazione, fai clic con il pulsante destro del mouse ed esegui il file eseguibile (.exe) di Unified Manager come amministratore.
. Quando richiesto, immettere il nome utente e la password per creare l'utente addetto alla manutenzione di Unified Manager.
. Nella procedura guidata di connessione al database, immettere la password di root di MySQL.
. Seguire le istruzioni rimanenti per completare l'installazione.
. Al termine dell'installazione fare clic su *Fine* per visualizzare l'interfaccia utente Web di Unified Manager.

