---
permalink: install-windows/task_install_unified_manager_on_windows.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: È possibile installare Unified Manager per monitorare e risolvere i problemi relativi a capacità di archiviazione dei dati, disponibilità, prestazioni e protezione. 
---
= Installa Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare Unified Manager per monitorare e risolvere i problemi relativi a capacità di archiviazione dei dati, disponibilità, prestazioni e protezione.

.Prima di iniziare
* Il sistema su cui si intende installare Unified Manager deve soddisfare i requisiti di sistema e software.
+
Vederelink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisiti di sistema hardware"] .

+
Vederelink:reference_windows_software_and_installation_requirements.html["Requisiti di installazione e software Windows"] .

+
[NOTE]
====
A partire da Unified Manager 9.5, OpenJDK è fornito nel pacchetto di installazione e installato automaticamente.  Oracle Java non è supportato a partire da Unified Manager 9.5.

====
* Dovresti avere privilegi di amministratore di Windows.  Assicurati che il tuo nome utente non inizi con un punto esclamativo "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "` !`".
* Sono supportati tutti i cluster, ad eccezione dei sistemi ASA r2.
* Dovresti avere un browser web supportato.
* La password utente di manutenzione di Unified Manager deve essere compresa tra 8 e 20 caratteri e contenere lettere maiuscole o minuscole, numeri e caratteri speciali.
* I seguenti caratteri speciali non sono consentiti nella stringa della password per l'utente addetto alla manutenzione o per l'utente root di MySQL: " ' ` % , = & < > | ^ \ / ( ) [ ] ;:
+
Sono consentiti i seguenti caratteri speciali: ~ !  @ # $ * - ? .  + { }



.Passi
. Accedi a Windows utilizzando l'account amministratore locale predefinito.
. Accedi al sito di supporto NetApp e vai alla pagina di download per Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Sito di supporto NetApp"^]

. Selezionare la versione richiesta di Unified Manager e accettare il contratto di licenza con l'utente finale (EULA).
. Scaricare il file di installazione di Unified Manager per Windows o il file zip in una directory di destinazione sul sistema Windows.
. Se necessario, estrarre il file zip e andare alla directory in cui si trova il file di installazione.
. Fare clic con il pulsante destro del mouse ed eseguire il file eseguibile (.exe) del programma di installazione di Unified Manager come amministratore.
+
Unified Manager rileva i pacchetti di terze parti mancanti o preinstallati e li elenca.  Se i pacchetti di terze parti richiesti non sono installati nel sistema, Unified Manager li installa come parte dell'installazione.

. Fare clic su *Avanti*.
. Inserisci il nome utente e la password per creare l'utente addetto alla manutenzione.
. Nella procedura guidata di connessione al database, immettere la password di root di MySQL.
. Fare clic su *Modifica* per specificare una nuova posizione per la directory di installazione di Unified Manager e la directory dei dati MySQL.
+
Se non si modifica la directory di installazione, Unified Manager verrà installato nella directory di installazione predefinita.

. Fare clic su *Avanti*.
. Nella procedura guidata Ready to Install Shield, fare clic su *Installa*.
. Una volta completata l'installazione, fare clic su *Fine*.
. Se sul sistema Windows è installato un software antivirus attivo, escludere manualmente i seguenti percorsi dalla scansione antivirus al termine dell'installazione:
+
** Directory dati di Unified Manager
** Directory di installazione di Unified Manager
** Directory dei dati MySQL




L'installazione crea più directory:

* Directory di installazione
+
Questa è la directory radice di Unified Manager, specificata durante l'installazione.  Esempio: `C:\Program Files\NetApp\`

* Directory dei dati MySQL
+
Questa è la directory in cui sono archiviati i database MySQL, specificati durante l'installazione.  Esempio: `C:\ProgramData\MySQL\MySQLServerData\`

* directory Java
+
Questa è la directory in cui è installato OpenJDK.  Esempio: `C:\Program Files\NetApp\JDK\`

* Directory dei dati dell'applicazione Unified Manager (appDataDir)
+
Questa è la directory in cui vengono archiviati tutti i dati generati dall'applicazione.  Ciò include registri, pacchetti di supporto, backup e tutti gli altri dati aggiuntivi.  Esempio: `C:\ProgramData\NetApp\OnCommandAppData\`



È possibile accedere all'interfaccia utente Web per eseguire la configurazione iniziale di Unified Manager, come descritto inlink:../config/concept_configure_unified_manager.html["Configurazione di Active IQ Unified Manager"] .
