---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 'È possibile reimpostare la password JBoss specifica dell"istanza impostata durante l"installazione.  È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l"impostazione di installazione di Unified Manager.  Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.' 
---
= Cambia la password di JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile reimpostare la password JBoss specifica dell'istanza impostata durante l'installazione.  È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l'impostazione di installazione di Unified Manager.  Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.

.Prima di iniziare
* È necessario disporre dei privilegi di amministratore Windows per il sistema su cui è installato Unified Manager.
* Dovresti avere la password per l'utente root di MySQL.
* Dovresti essere in grado di accedere a NetApp fornito `password.bat` script nella directory
+
`C:\Program Files\NetApp\essentials\bin`.



.Passi
. Accedi come utente amministratore sul computer host di Unified Manager.
. Utilizzare la console dei servizi Windows per arrestare i seguenti servizi di Unified Manager:
+
** Servizio di acquisizione NetApp Active IQ (Ocie-au)
** Servizio NetApp Active IQ Management Server (Oncommandsvc)


. Avviare il `password.bat` script per iniziare il processo di modifica della password:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Quando richiesto, immettere la password dell'utente root di MySQL.
. Quando richiesto, immettere la nuova password utente JBoss, quindi inserirla nuovamente per conferma.
+
Tieni presente che la password deve essere compresa tra 8 e 16 caratteri e deve contenere almeno una cifra, una lettera maiuscola e una minuscola e almeno uno di questi caratteri speciali:

+
`+!@%^*-_+=[]:<>.?/~+`

. Al termine dello script, avviare i servizi Unified Manager utilizzando la console Servizi Windows:
+
** Servizio NetApp Active IQ Management Server (Oncommandsvc)
** Servizio di acquisizione NetApp Active IQ (Ocie-au)


. Dopo aver avviato tutti i servizi, è possibile accedere all'interfaccia utente di Unified Manager.

