---
permalink: install-windows/task_upgrade_to_unified_manager_on_microsoft_windows.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: È possibile aggiornare Unified Manager scaricando ed eseguendo il file di installazione sulla piattaforma Windows. 
---
= Aggiorna Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare Unified Manager 9.13 o 9.14 alla versione 9.16 scaricando ed eseguendo il file di installazione sulla piattaforma Windows.

.Prima di iniziare
* Il sistema su cui si sta aggiornando Unified Manager deve soddisfare i requisiti di sistema e software.
+
Vederelink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisiti di sistema hardware"] .

+
Vederelink:reference_windows_software_and_installation_requirements.html["Requisiti di installazione e software Windows"] .

+
[NOTE]
====
A partire da Unified Manager 9.5, OpenJDK è fornito nel pacchetto di installazione e installato automaticamente.  Oracle Java non è supportato a partire da Unified Manager 9.5.

====
+
[NOTE]
====
Prima di avviare l'aggiornamento, assicurarsi che sul sistema sia installato Microsoft .NET 4.5.2 o versione successiva.

====
* MySQL Community Edition viene aggiornato automaticamente durante l'aggiornamento di Unified Manager.  Se la versione di MySQL installata sul sistema è precedente alla 8.4.4, il processo di aggiornamento di Unified Manager aggiorna automaticamente MySQL alla versione 8.4.4.  Non è consentito eseguire un aggiornamento autonomo di una versione precedente di MySQL alla versione 8.4.4.
* Sono supportati tutti i cluster, ad eccezione dei sistemi ASA r2.
* Dovresti avere privilegi di amministratore di Windows.  Assicurati che il tuo nome utente non inizi con un punto esclamativo "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "` !`".
* Per accedere al sito di supporto NetApp è necessario disporre di credenziali valide.
* Per evitare la perdita di dati, è opportuno creare un backup della macchina Unified Manager nel caso in cui si verifichi un problema durante l'aggiornamento.
* Per eseguire l'aggiornamento è necessario disporre di spazio su disco sufficiente.
+
Lo spazio disponibile sull'unità di installazione deve essere 2,5 GB più grande della dimensione della directory dei dati.  L'aggiornamento si interrompe e viene visualizzato un messaggio di errore che indica la quantità di spazio da aggiungere se non c'è abbastanza spazio libero.

* Durante l'aggiornamento, potrebbe esserti richiesto di confermare se desideri mantenere le impostazioni predefinite precedenti per la conservazione dei dati sulle prestazioni per 13 mesi o modificarle in 6 mesi.  Dopo la conferma, i dati storici sulle prestazioni dopo 6 mesi vengono eliminati.
* Prima di eseguire l'aggiornamento, chiudere tutti i file o le cartelle aperti in _<InstallDir>\JDK_ e _MySQL Data Directory_.
* Se sul sistema Windows è installato un software antivirus attivo, l'aggiornamento di Unified Manager potrebbe non riuscire.  Prima di aggiornare Unified Manager, dovresti disattivare tutti i software antivirus presenti sul tuo sistema.


Durante il processo di aggiornamento, Unified Manager non è disponibile.  Prima di aggiornare Unified Manager, è necessario completare tutte le operazioni in esecuzione.

Se Unified Manager è associato a un'istanza di OnCommand Workflow Automation e sono disponibili nuove versioni del software per entrambi i prodotti, è necessario disconnettere i due prodotti e quindi configurare una nuova connessione Workflow Automation dopo aver eseguito gli aggiornamenti.  Se si esegue l'aggiornamento solo a uno dei prodotti, è necessario accedere a Workflow Automation dopo l'aggiornamento e verificare che stia ancora acquisendo dati da Unified Manager.

.Passi
. Accedi al sito di supporto NetApp e vai alla pagina di download per Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Sito di supporto NetApp"^].

. Selezionare la versione richiesta di Unified Manager e accettare il contratto di licenza con l'utente finale (EULA).
. Scaricare il file di installazione di Unified Manager per Windows o il file zip in una directory di destinazione sul sistema Windows.  Se necessario, estrarre il file zip e andare alla directory in cui si trova il file di installazione.  Fare clic con il pulsante destro del mouse ed eseguire il file eseguibile (.exe) del programma di installazione di Unified Manager come amministratore.
+
Unified Manager visualizza il seguente messaggio:

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. Fare clic su *Sì*, quindi su *Avanti*.
. Immettere la password di root di MySQL84 impostata durante l'installazione, quindi fare clic su *Avanti*.
. Avvia l'interfaccia utente Web in una nuova finestra su un browser Web supportato ed effettua l'accesso per utilizzare la versione aggiornata di Unified Manager.
. Se sul sistema Windows è installato un software antivirus attivo, assicurarsi di escludere manualmente i seguenti percorsi dalla scansione antivirus una volta completato l'aggiornamento:
+
** Directory dati di Unified Manager
** Directory di installazione di Unified Manager
** Directory dei dati MySQL




[NOTE]
====
Per eseguire un aggiornamento silenzioso di Unified Manager, eseguire il seguente comando:
`ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=<password> /qn /l*v <system_drive>:\install.log"`

====