---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 'È possibile rilevare se i registri di controllo sono stati compromessi utilizzando i registri di controllo.  Tutte le attività svolte da un utente vengono monitorate e registrate nei registri di controllo.  Gli audit vengono eseguiti per tutte le funzionalità dell"interfaccia utente e delle API esposte pubblicamente di Active IQ Unified Manager.' 
---
= Registrazione di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rilevare se i registri di controllo sono stati compromessi utilizzando i registri di controllo.  Tutte le attività svolte da un utente vengono monitorate e registrate nei registri di controllo.  Gli audit vengono eseguiti per tutte le funzionalità dell'interfaccia utente e delle API esposte pubblicamente di Active IQ Unified Manager.

È possibile utilizzare *Registro di controllo: Visualizzazione file* per visualizzare e accedere a tutti i file del registro di controllo disponibili in Active IQ Unified Manager.  I file nel Registro di controllo: Visualizzazione file sono elencati in base alla data di creazione.  Questa vista mostra le informazioni di tutti i registri di controllo acquisiti dall'installazione o dall'aggiornamento fino al momento presente nel sistema.  Ogni volta che si esegue un'azione in Unified Manager, le informazioni vengono aggiornate e sono disponibili nei registri.  Lo stato di ciascun file di registro viene acquisito tramite l'attributo "`File Integrity Status`", che viene monitorato attivamente per rilevare manomissioni o eliminazioni del file di registro.  Quando sono disponibili nel sistema, i registri di controllo possono avere uno dei seguenti stati:

[cols="2*"]
|===
| Stato | Descrizione 


 a| 
ATTIVO
 a| 
File in cui vengono attualmente registrati i log.



 a| 
NORMALE
 a| 
File inattivo, compresso e memorizzato nel sistema.



 a| 
MANOMESTRI
 a| 
File compromesso da un utente che lo ha modificato manualmente.



 a| 
ELIMINA_MANUALE
 a| 
File eliminato da un utente autorizzato.



 a| 
ROLLOVER_ELIMINA
 a| 
File eliminato a causa del roll-off basato sulla politica di configurazione rolling.



 a| 
ELIMINAZIONE_INATTESA
 a| 
File eliminato per motivi sconosciuti.

|===
La pagina Registro di controllo include i seguenti pulsanti di comando:

* Configurare
* Eliminare
* Scaricamento


Il pulsante *ELIMINA* consente di eliminare uno qualsiasi dei registri di controllo elencati nella vista Registri di controllo.  È possibile eliminare un registro di controllo e, facoltativamente, specificare un motivo per eliminare il file, che aiuterà in futuro a determinare un'eliminazione valida.  Nella colonna MOTIVO è elencato il motivo insieme al nome dell'utente che ha eseguito l'operazione di eliminazione.

[NOTE]
====
L'eliminazione di un file di registro comporterà l'eliminazione del file dal sistema, ma la voce nella tabella del database non verrà eliminata.

====
È possibile scaricare i registri di controllo da Active IQ Unified Manager utilizzando il pulsante *DOWNLOAD* nella sezione Registri di controllo ed esportare i file di registro di controllo.  I file contrassegnati come "`NORMALI`" o "`MANOMESSI`" vengono scaricati in un formato compresso `.gzip` formato.

I file di registro di controllo vengono archiviati periodicamente e salvati nel database per riferimento.  Prima dell'archiviazione, i registri di controllo vengono firmati digitalmente per garantirne la sicurezza e l'integrità.

Quando viene generato un bundle AutoSupport completo, il bundle di supporto include sia i file di registro di controllo archiviati che quelli attivi.  Tuttavia, quando viene generato un pacchetto di supporto leggero, include solo i log di controllo attivi.  I registri di controllo archiviati non sono inclusi.
