---
permalink: config/concept_policy_based_storage_management.html 
sidebar: sidebar 
keywords: slo, storage efficiency policy, storage workloads 
summary: 'L"opzione di gestione dell"archiviazione basata su policy consente la gestione dell"archiviazione in base agli obiettivi del livello di servizio (SLO). Questa opzione è abilitata per impostazione predefinita.' 
---
= Abilita la gestione dell'archiviazione basata su policy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'opzione *Gestione dell'archiviazione basata su policy* consente la gestione dell'archiviazione in base agli obiettivi del livello di servizio (SLO). Questa opzione è abilitata per impostazione predefinita.

Attivando questa funzionalità, è possibile eseguire il provisioning dei carichi di lavoro di archiviazione sui cluster ONTAP aggiunti all'istanza di Active IQ Unified Manager e gestire tali carichi di lavoro in base ai livelli di servizio delle prestazioni assegnati e ai criteri di efficienza dell'archiviazione.

Puoi scegliere di attivare o disattivare questa funzionalità da *Generale* > *Impostazioni funzionalità* > *Gestione dell'archiviazione basata su criteri*.  Attivando questa funzione, sono disponibili le seguenti pagine per il funzionamento e il monitoraggio:

* Provisioning (provisioning del carico di lavoro di archiviazione)
* *Politiche* > *Livelli di servizio prestazionali*
* *Politiche* > *Efficienza di archiviazione*
* Colonna Carichi di lavoro gestiti dal livello di servizio delle prestazioni nella pagina Configurazione cluster
* Pannello Prestazioni del carico di lavoro nella *Dashboard*


È possibile utilizzare le schermate per creare livelli di servizio delle prestazioni e policy di efficienza dell'archiviazione, nonché per eseguire il provisioning dei carichi di lavoro di archiviazione.  È inoltre possibile monitorare i carichi di lavoro di archiviazione conformi ai livelli di servizio delle prestazioni assegnati, nonché quelli non conformi.  Il pannello Prestazioni del carico di lavoro e IOPS del carico di lavoro consente inoltre di valutare la capacità e le prestazioni (IOPS) totali, disponibili e utilizzate dei cluster nel data center in base ai carichi di lavoro di storage in essi forniti.

Dopo aver attivato questa funzionalità, è possibile eseguire le API REST di Unified Manager per svolgere alcune di queste funzioni dalla categoria *Barra dei menu* > *Pulsante Guida* > *Documentazione API* > *provider di archiviazione*.  In alternativa, puoi immettere il nome host o l'indirizzo IP e l'URL per accedere alla pagina REST API nel formato +https://<hostname>/docs/api/+

Per ulteriori informazioni sulle API, vederelink:../api-automation/concept_get_started_with_um_apis.html["Introduzione alle API REST Active IQ Unified Manager"] .
