---
permalink: config/concept_api_gateway.html 
sidebar: sidebar 
keywords: api gateway 
summary: La funzionalità API Gateway consente ad Active IQ Unified Manager di essere un unico piano di controllo da cui è possibile gestire più cluster ONTAP , senza doverli accedere singolarmente. 
---
= Abilita API Gateway
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzionalità API Gateway consente ad Active IQ Unified Manager di essere un unico piano di controllo da cui è possibile gestire più cluster ONTAP , senza doverli accedere singolarmente.

È possibile abilitare questa funzionalità dalle pagine di configurazione che vengono visualizzate al primo accesso a Unified Manager.  In alternativa, puoi abilitare o disabilitare questa funzione da *Generale* > *Impostazioni funzione* > *API Gateway*.

Le API REST di Unified Manager sono diverse dalle API REST ONTAP e non tutte le funzionalità delle API REST ONTAP possono essere sfruttate utilizzando le API REST di Unified Manager.  Tuttavia, se si ha un requisito aziendale specifico di accesso alle API ONTAP per la gestione di funzionalità specifiche non esposte a Unified Manager, è possibile abilitare la funzionalità API Gateway ed eseguire le API ONTAP .  Il gateway funge da proxy per incanalare le richieste API mantenendo l'intestazione e il corpo delle richieste nello stesso formato delle API ONTAP .  È possibile utilizzare le credenziali di Unified Manager ed eseguire le API specifiche per accedere e gestire i cluster ONTAP senza dover passare le credenziali individuali del cluster.  Unified Manager funge da singolo punto di gestione per l'esecuzione delle API sui cluster ONTAP gestiti dall'istanza di Unified Manager.  La risposta restituita dalle API è la stessa della risposta restituita dalle rispettive API REST ONTAP eseguite direttamente da ONTAP.

Dopo aver abilitato questa funzionalità, è possibile eseguire le API REST di Unified Manager dalla *Barra dei menu* > *Pulsante Guida* > *Documentazione API* > categoria *gateway*.  In alternativa, puoi immettere il nome host o l'indirizzo IP e l'URL per accedere alla pagina REST API nel formato `https://<hostname>/docs/api/`

Per ulteriori informazioni sulle API, vederelink:../api-automation/concept_get_started_with_um_apis.html["Introduzione alle API REST Active IQ Unified Manager"] .
