---
permalink: config/concept_maintenance_console_menu.html 
sidebar: sidebar 
keywords: maintenance, console, menus 
summary: La console di manutenzione è composta da diversi menu che consentono di gestire e gestire funzionalità speciali e impostazioni di configurazione del server Unified Manager. 
---
= Menu della console di manutenzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La console di manutenzione è composta da diversi menu che consentono di gestire e gestire funzionalità speciali e impostazioni di configurazione del server Unified Manager.

A seconda del sistema operativo su cui è installato Unified Manager, la console di manutenzione è composta dai seguenti menu:

* Aggiorna Unified Manager (solo VMware)
* Configurazione di rete (solo VMware)
* Configurazione del sistema (solo VMware)
+
.. Supporto/Diagnostica
.. Reimposta il certificato del server
.. Fornitore di dati esterno
.. Backup Ripristino
.. Configurazione dell'intervallo di polling delle prestazioni
.. Disabilitare l'autenticazione SAML
.. Visualizza/modifica le porte dell'applicazione
.. Configurazione del registro di debug
.. Controlla l'accesso alla porta MySQL 3306
.. Uscita




Per accedere all'opzione di menu specifica, selezionare il numero dall'elenco.  Ad esempio, per il backup e il ripristino, selezionare _4_.
