---
permalink: config/reference_identity_provider_requirements_um.html 
sidebar: sidebar 
keywords: identity, provider, requirements 
summary: 'Quando si configura Unified Manager per utilizzare un provider di identità (IdP) per eseguire l"autenticazione SAML per tutti gli utenti remoti, è necessario conoscere alcune impostazioni di configurazione richieste affinché la connessione a Unified Manager abbia successo.' 
---
= Requisiti del fornitore di identità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura Unified Manager per utilizzare un provider di identità (IdP) per eseguire l'autenticazione SAML per tutti gli utenti remoti, è necessario conoscere alcune impostazioni di configurazione richieste affinché la connessione a Unified Manager abbia successo.

È necessario immettere l'URI e i metadati di Unified Manager nel server IdP.  È possibile copiare queste informazioni dalla pagina Autenticazione SAML di Unified Manager.  Unified Manager è considerato il fornitore di servizi (SP) nello standard Security Assertion Markup Language (SAML).



== Standard di crittografia supportati

* Standard di crittografia avanzata (AES): AES-128 e AES-256
* Algoritmo hash sicuro (SHA): SHA-1 e SHA-256




== Fornitori di identità convalidati

* Shibboleth
* Servizi federativi di Active Directory (ADFS)




== Requisiti di configurazione ADFS

* È necessario definire tre regole di attestazione nel seguente ordine, necessarie affinché Unified Manager analizzi le risposte SAML di ADFS per questa voce di trust della relying party.
+
[cols="2*"]
|===
| Regola di rivendicazione | Valore 


 a| 
Nome account SAM
 a| 
ID nome



 a| 
Nome account SAM
 a| 
urna:oid:0.9.2342.19200300.100.1.1



 a| 
Gruppi di token -- Nome non qualificato
 a| 
urna:oid:1.3.6.1.4.1.5923.1.5.1.1

|===
* È necessario impostare il metodo di autenticazione su "`Autenticazione tramite moduli`" altrimenti gli utenti potrebbero ricevere un errore quando escono da Unified Manager. Segui questi passaggi:
+
.. Aprire la console di gestione ADFS.
.. Fare clic sulla cartella Criteri di autenticazione nella vista ad albero a sinistra.
.. In Azioni sulla destra, fare clic su Modifica criterio di autenticazione primaria globale.
.. Impostare il metodo di autenticazione Intranet su "`Autenticazione basata su moduli`" anziché sul valore predefinito "`Autenticazione Windows`".


* In alcuni casi l'accesso tramite IdP viene rifiutato quando il certificato di sicurezza di Unified Manager è firmato da una CA.  Esistono due soluzioni alternative per risolvere questo problema:
+
** Seguire le istruzioni identificate nel collegamento per disattivare il controllo di revoca sul server ADFS per la parte affidabile associata al certificato CA concatenato:
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/["Disabilita il controllo di revoca per trust della parte affidabile"]

** Fare in modo che il server CA risieda all'interno del server ADFS per firmare la richiesta di certificato del server Unified Manager.






== Altri requisiti di configurazione

* Lo sfasamento dell'orologio di Unified Manager è impostato su 5 minuti, quindi la differenza di orario tra il server IdP e il server Unified Manager non può essere superiore a 5 minuti, altrimenti l'autenticazione fallirà.

