---
permalink: config/reference_additional_menu_options.html 
sidebar: sidebar 
keywords: additional menu, options 
summary: Le seguenti opzioni di menu consentono di eseguire varie attività amministrative sul server Unified Manager. 
---
= Opzioni di menu aggiuntive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le seguenti opzioni di menu consentono di eseguire varie attività amministrative sul server Unified Manager.

Sono disponibili le seguenti opzioni di menu:

* *Reimposta certificato server*
+
Rigenera il certificato del server HTTPS.

+
È possibile rigenerare il certificato del server nell'interfaccia utente grafica di Unified Manager facendo clic su *Generale* > *Certificati HTTPS* > *Rigenera certificato HTTPS*.

* *Disabilita l'autenticazione SAML*
+
Disabilita l'autenticazione SAML in modo che il provider di identità (IdP) non fornisca più l'autenticazione di accesso per gli utenti che accedono alla GUI di Unified Manager.  Questa opzione della console viene in genere utilizzata quando un problema con il server IdP o la configurazione SAML impedisce agli utenti di accedere all'interfaccia utente grafica di Unified Manager.

* *Fornitore di dati esterno*
+
Fornisce opzioni per connettere Unified Manager a un fornitore di dati esterno.  Dopo aver stabilito la connessione, i dati sulle prestazioni vengono inviati a un server esterno in modo che gli esperti delle prestazioni di archiviazione possano tracciare le metriche delle prestazioni utilizzando software di terze parti. Vengono visualizzate le seguenti opzioni:

+
** *Visualizza configurazione server*: visualizza le impostazioni di connessione e configurazione correnti per un fornitore di dati esterno.
** *Aggiungi/Modifica connessione server*: consente di immettere nuove impostazioni di connessione per un fornitore di dati esterno o di modificare le impostazioni esistenti.
** *Modifica configurazione server*: consente di immettere nuove impostazioni di configurazione per un fornitore di dati esterno o di modificare le impostazioni esistenti.
** *Elimina connessione al server*: elimina la connessione a un fornitore di dati esterno.
+
Dopo l'eliminazione della connessione, Unified Manager perde la connessione al server esterno.



* *Backup e ripristino*
+
Per informazioni, vedere gli argomenti sottolink:../health-checker/concept_manage_backup_and_restore_operations.html["Gestione delle operazioni di backup e ripristino"] .

* *Configurazione dell'intervallo di polling delle prestazioni*
+
Fornisce un'opzione per configurare la frequenza con cui Unified Manager raccoglie i dati statistici sulle prestazioni dai cluster.  L'intervallo di raccolta predefinito è di 5 minuti.

+
È possibile modificare questo intervallo a 10 o 15 minuti se si nota che le raccolte di cluster di grandi dimensioni non vengono completate in tempo.

* *Visualizza/Modifica porte applicazione*
+
Fornisce un'opzione per modificare le porte predefinite utilizzate da Unified Manager per i protocolli HTTP e HTTPS, se necessario per motivi di sicurezza.  Le porte predefinite sono 80 per HTTP e 443 per HTTPS.

* *Controlla l'accesso alla porta MySQL 3306*
+
Controlla l'accesso dell'host alla porta MySQL predefinita 3306.  Per motivi di sicurezza, l'accesso tramite questa porta è limitato solo a localhost durante una nuova installazione di Unified Manager su sistemi Linux, Windows e VMware vSphere.  Questa opzione consente di alternare la visibilità di questa porta tra localhost e host remoti, ovvero, se è abilitata solo per localhost nel tuo ambiente, puoi rendere questa porta disponibile anche per gli host remoti.  In alternativa, se abilitata per tutti gli host, è possibile limitare l'accesso a questa porta solo a localhost.  Se in precedenza l'accesso era abilitato sugli host remoti, la configurazione viene mantenuta in uno scenario di aggiornamento.  Dopo aver attivato la visibilità della porta, è necessario controllare le impostazioni del firewall sui sistemi Windows e disattivare le impostazioni del firewall se sono configurate per limitare l'accesso alla porta MySQL 3306.

* *Uscita*
+
Esce dal menu della console di manutenzione.


