---
permalink: config/reference_definitions_of_user_roles.html 
sidebar: sidebar 
keywords: definitions, user roles 
summary: 'L"utente addetto alla manutenzione o l"amministratore dell"applicazione assegna un ruolo a ogni utente.  Ogni ruolo contiene determinati privilegi.  L"ambito delle attività che puoi svolgere in Unified Manager dipende dal ruolo che ti è stato assegnato e dai privilegi che il ruolo contiene.' 
---
= Definizioni dei ruoli utente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'utente addetto alla manutenzione o l'amministratore dell'applicazione assegna un ruolo a ogni utente.  Ogni ruolo contiene determinati privilegi.  L'ambito delle attività che puoi svolgere in Unified Manager dipende dal ruolo che ti è stato assegnato e dai privilegi che il ruolo contiene.

Unified Manager include i seguenti ruoli utente predefiniti:

* *Operatore*
+
Visualizza le informazioni sul sistema di archiviazione e altri dati raccolti da Unified Manager, tra cui cronologie e tendenze della capacità.  Questo ruolo consente all'operatore di archiviazione di visualizzare, assegnare, riconoscere, risolvere e aggiungere note per gli eventi.

* *Amministratore di archiviazione*
+
Configura le operazioni di gestione dell'archiviazione all'interno di Unified Manager.  Questo ruolo consente all'amministratore dell'archiviazione di configurare soglie e di creare avvisi e altre opzioni e policy specifiche per la gestione dell'archiviazione.

* *Amministratore dell'applicazione*
+
Configura le impostazioni non correlate alla gestione dell'archiviazione.  Questo ruolo consente la gestione degli utenti, dei certificati di sicurezza, dell'accesso al database e delle opzioni amministrative, tra cui autenticazione, SMTP, networking e AutoSupport.

+
[NOTE]
====
Quando Unified Manager viene installato sui sistemi Linux, l'utente iniziale con il ruolo di amministratore dell'applicazione viene automaticamente denominato "`umadmin`".

====
* *Schema di integrazione*
+
Questo ruolo consente l'accesso in sola lettura alle viste del database di Unified Manager per l'integrazione di Unified Manager con OnCommand Workflow Automation (WFA).

* *Schema del report*
+
Questo ruolo consente l'accesso in sola lettura ai report e ad altre visualizzazioni del database direttamente dal database Unified Manager.  I database che possono essere consultati includono:

+
** netapp_model_view
** prestazioni netapp
** ocum
** ocum_report
** ocum_report_birt
** opm
** monitor di scala



