---
permalink: config/reference_https_dialog_box_ocf.html 
sidebar: sidebar 
keywords: https certificate page 
summary: La pagina Certificato HTTPS consente di visualizzare il certificato di sicurezza corrente, scaricare una richiesta di firma del certificato, generare un nuovo certificato HTTPS o installare un nuovo certificato HTTPS. 
---
= Pagina del certificato HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Certificato HTTPS consente di visualizzare il certificato di sicurezza corrente, scaricare una richiesta di firma del certificato, generare un nuovo certificato HTTPS autofirmato o installare un nuovo certificato HTTPS.

Se non hai generato un nuovo certificato HTTPS autofirmato, il certificato visualizzato in questa pagina è quello generato durante l'installazione.



== Pulsanti di comando

I pulsanti di comando consentono di eseguire le seguenti operazioni:

* *Scarica la richiesta di firma del certificato HTTPS*
+
Scarica una richiesta di certificazione per il certificato HTTPS attualmente installato.  Il browser ti chiede di salvare il file <hostname>.csr in modo da poterlo fornire a un'autorità di certificazione per la firma.

* *Installa il certificato HTTPS*
+
Consente di caricare e installare un certificato di sicurezza dopo che un'autorità di certificazione lo ha firmato e restituito.  Il nuovo certificato sarà effettivo dopo il riavvio del server di gestione.

* *Rigenera il certificato HTTPS*
+
Consente di generare un nuovo certificato HTTPS autofirmato, che sostituisce l'attuale certificato di sicurezza.  Il nuovo certificato sarà effettivo dopo il riavvio di Unified Manager.


