---
permalink: config/reference_saml_authentication_page_um.html 
sidebar: sidebar 
keywords: saml authentication page 
summary: 'È possibile utilizzare la pagina Autenticazione SAML per configurare Unified Manager in modo che autentichi gli utenti remoti tramite SAML tramite un provider di identità sicuro (IdP) prima che possano accedere all"interfaccia utente Web di Unified Manager.' 
---
= Pagina di autenticazione SAML
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la pagina Autenticazione SAML per configurare Unified Manager in modo che autentichi gli utenti remoti tramite SAML tramite un provider di identità sicuro (IdP) prima che possano accedere all'interfaccia utente Web di Unified Manager.

* Per creare o modificare la configurazione SAML è necessario disporre del ruolo di amministratore dell'applicazione.
* È necessario aver configurato l'autenticazione remota.
* È necessario aver configurato almeno un utente remoto o un gruppo remoto.


Dopo aver configurato l'autenticazione remota e gli utenti remoti, è possibile selezionare la casella di controllo Abilita autenticazione SAML per abilitare l'autenticazione tramite un provider di identità sicuro.

* *URI IdP*
+
L'URI per accedere all'IdP dal server Unified Manager.  Di seguito sono elencati alcuni esempi di URI.

+
URI di esempio ADFS:

+
`+https://win2016-dc.ntap2016.local/federationmetadata/2007-06/federationmetadata.xml+`

+
Esempio di URI di Shibboleth:

+
`+https://centos7.ntap2016.local/idp/shibboleth+`

* *Metadati IdP*
+
Metadati IdP in formato XML.

+
Se l'URL dell'IdP è accessibile dal server Unified Manager, è possibile fare clic sul pulsante *Recupera metadati IdP* per popolare questo campo.

* *Sistema host (FQDN)*
+
FQDN del sistema host Unified Manager come definito durante l'installazione.  Se necessario, è possibile modificare questo valore.

* *URI host*
+
L'URI per accedere al sistema host Unified Manager dall'IdP.

* *Metadati host*
+
Metadati del sistema host in formato XML.


