---
permalink: config/reference_remote_authentication_page.html 
sidebar: sidebar 
keywords: remote authentication, page 
summary: 'È possibile utilizzare la pagina Autenticazione remota per configurare Unified Manager in modo che comunichi con il server di autenticazione per autenticare gli utenti remoti che tentano di accedere all"interfaccia utente Web di Unified Manager.' 
---
= Pagina di autenticazione remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la pagina Autenticazione remota per configurare Unified Manager in modo che comunichi con il server di autenticazione per autenticare gli utenti remoti che tentano di accedere all'interfaccia utente Web di Unified Manager.

È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Dopo aver selezionato la casella di controllo Abilita autenticazione remota, è possibile abilitare l'autenticazione remota tramite un server di autenticazione.

* *Servizio di autenticazione*
+
Consente di configurare il server di gestione per autenticare gli utenti nei provider di servizi di directory, come Active Directory, OpenLDAP, oppure di specificare un proprio meccanismo di autenticazione.  È possibile specificare un servizio di autenticazione solo se è stata abilitata l'autenticazione remota.

+
** *Directory attiva*
+
*** Nome dell'amministratore
+
Specifica il nome dell'amministratore del server di autenticazione.

*** Password
+
Specifica la password per accedere al server di autenticazione.

*** Nome distinto di base
+
Specifica la posizione degli utenti remoti nel server di autenticazione.  Ad esempio, se il nome di dominio del server di autenticazione è +ou@domain.com+, il nome distinto di base è *cn=ou,dc=domain,dc=com*.

*** Disabilita la ricerca di gruppi nidificati
+
Specifica se abilitare o disabilitare l'opzione di ricerca dei gruppi annidati.  Per impostazione predefinita questa opzione è disabilitata.  Se si utilizza Active Directory, è possibile velocizzare l'autenticazione disabilitando il supporto per i gruppi nidificati.

*** Utilizza una connessione sicura
+
Specifica il servizio di autenticazione utilizzato per comunicare con i server di autenticazione.



** *OpenLDAP*
+
*** Associa nome distinto
+
Specifica il nome distinto di associazione utilizzato insieme al nome distinto di base per trovare gli utenti remoti nel server di autenticazione.

*** Password di associazione
+
Specifica la password per accedere al server di autenticazione.

*** Nome distinto di base
+
Specifica la posizione degli utenti remoti nel server di autenticazione.  Ad esempio, se il nome di dominio del server di autenticazione è +ou@domain.com+, il nome distinto di base è *cn=ou,dc=domain,dc=com*.

*** Utilizza una connessione sicura
+
Specifica che Secure LDAP viene utilizzato per comunicare con i server di autenticazione LDAP.



** *Altri*
+
*** Associa nome distinto
+
Specifica il nome distinto di associazione utilizzato insieme al nome distinto di base per trovare gli utenti remoti nel server di autenticazione configurato.

*** Password di associazione
+
Specifica la password per accedere al server di autenticazione.

*** Nome distinto di base
+
Specifica la posizione degli utenti remoti nel server di autenticazione.  Ad esempio, se il nome di dominio del server di autenticazione è +ou@domain.com+, il nome distinto di base è *cn=ou,dc=domain,dc=com*.

*** Versione del protocollo
+
Specifica la versione del protocollo LDAP (Lightweight Directory Access Protocol) supportata dal server di autenticazione.  È possibile specificare se la versione del protocollo deve essere rilevata automaticamente oppure impostare la versione su 2 o 3.

*** Attributo nome utente
+
Specifica il nome dell'attributo nel server di autenticazione che contiene i nomi di accesso utente da autenticare tramite il server di gestione.

*** Attributo di appartenenza al gruppo
+
Specifica un valore che assegna l'appartenenza al gruppo del server di gestione agli utenti remoti in base a un attributo e a un valore specificati nel server di autenticazione dell'utente.

*** UGID
+
Se gli utenti remoti sono inclusi come membri di un oggetto GroupOfUniqueNames nel server di autenticazione, questa opzione consente di assegnare l'appartenenza al gruppo del server di gestione agli utenti remoti in base a un attributo specificato in tale oggetto GroupOfUniqueNames.

*** Disabilita la ricerca di gruppi nidificati
+
Specifica se abilitare o disabilitare l'opzione di ricerca dei gruppi annidati.  Per impostazione predefinita questa opzione è disabilitata.  Se si utilizza Active Directory, è possibile velocizzare l'autenticazione disabilitando il supporto per i gruppi nidificati.

*** Membro
+
Specifica il nome dell'attributo utilizzato dal server di autenticazione per memorizzare le informazioni sui singoli membri di un gruppo.

*** Classe oggetto utente
+
Specifica la classe di oggetti di un utente nel server di autenticazione remoto.

*** Classe di oggetti di gruppo
+
Specifica la classe di oggetti di tutti i gruppi nel server di autenticazione remoto.

+

NOTE: I valori immessi per gli attributi _Member_, _User Object Class_ e _Group Object Class_ devono essere gli stessi aggiunti nelle configurazioni di Active Directory, OpenLDAP e LDAP.  In caso contrario, l'autenticazione potrebbe fallire.

*** Utilizza una connessione sicura
+
Specifica il servizio di autenticazione utilizzato per comunicare con i server di autenticazione.





+
[NOTE]
====
Se si desidera modificare il servizio di autenticazione, assicurarsi di eliminare tutti i server di autenticazione esistenti e di aggiungerne di nuovi.

====




== Area server di autenticazione

L'area Server di autenticazione visualizza i server di autenticazione con cui il server di gestione comunica per trovare e autenticare gli utenti remoti.  Le credenziali per gli utenti o i gruppi remoti sono gestite dal server di autenticazione.

* *Pulsanti di comando*
+
Consente di aggiungere, modificare o eliminare server di autenticazione.

+
** Aggiungere
+
Consente di aggiungere un server di autenticazione.

+
Se il server di autenticazione che si sta aggiungendo fa parte di una coppia ad alta disponibilità (che utilizza lo stesso database), è possibile aggiungere anche il server di autenticazione partner.  Ciò consente al server di gestione di comunicare con il partner quando uno dei server di autenticazione non è raggiungibile.

** Modificare
+
Consente di modificare le impostazioni per un server di autenticazione selezionato.

** Eliminare
+
Elimina i server di autenticazione selezionati.



* *Nome o indirizzo IP*
+
Visualizza il nome host o l'indirizzo IP del server di autenticazione utilizzato per autenticare l'utente sul server di gestione.

* *Porta*
+
Visualizza il numero di porta del server di autenticazione.

* *Test di autenticazione*
+
Questo pulsante convalida la configurazione del server di autenticazione autenticando un utente o un gruppo remoto.

+
Durante il test, se si specifica solo il nome utente, il server di gestione cerca l'utente remoto nel server di autenticazione, ma non lo autentica.  Se si specificano sia il nome utente che la password, il server di gestione cerca e autentica l'utente remoto.

+
Non è possibile testare l'autenticazione se l'autenticazione remota è disabilitata.


