---
permalink: config/reference_system_configuration_menu.html 
sidebar: sidebar 
keywords: system, configuration, menu 
summary: 'Il menu Configurazione di sistema consente di gestire l"appliance virtuale fornendo varie opzioni, come la visualizzazione dello stato del server e il riavvio e l"arresto della macchina virtuale.' 
---
= Menu di configurazione del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il menu Configurazione di sistema consente di gestire l'appliance virtuale fornendo varie opzioni, come la visualizzazione dello stato del server e il riavvio e l'arresto della macchina virtuale.

[NOTE]
====
Quando Unified Manager è installato su un sistema Linux o Microsoft Windows, da questo menu è disponibile solo l'opzione "`Ripristina da un backup di Unified Manager`".

====
Sono disponibili le seguenti opzioni di menu:

* *Visualizza lo stato del server*
+
Visualizza lo stato attuale del server.  Le opzioni di stato includono In esecuzione e Non in esecuzione.

+
Se il server non è in esecuzione, potrebbe essere necessario contattare l'assistenza tecnica.

* *Riavvia la macchina virtuale*
+
Riavvia la macchina virtuale, arrestando tutti i servizi.  Dopo il riavvio, la macchina virtuale e i servizi vengono riavviati.

* *Spegnimento della macchina virtuale*
+
Arresta la macchina virtuale, interrompendo tutti i servizi.

+
È possibile selezionare questa opzione solo dalla console della macchina virtuale.

* *Cambia la password dell'utente <utente registrato>*
+
Modifica la password dell'utente attualmente connesso, che può essere solo l'utente addetto alla manutenzione.

* *Aumenta la dimensione del disco dati*
+
Aumenta la dimensione del disco dati (disco 3) nella macchina virtuale.

* *Aumenta la dimensione del disco di swap*
+
Aumenta la dimensione del disco di swap (disco 2) nella macchina virtuale.

* *Cambia fuso orario*
+
Modifica il fuso orario in base alla tua posizione.

* *Cambia server NTP*
+
Modifica le impostazioni del server NTP, come l'indirizzo IP o il nome di dominio completo (FQDN).

* *Cambia servizio NTP*
+
Passa tra `ntp` E `systemd-timesyncd` servizi.

* *Ripristina da un backup di Unified Manager*
+
Ripristina il database e le impostazioni di configurazione di Unified Manager da una versione precedentemente sottoposta a backup.

* *Reimposta certificato server*
+
Reimposta il certificato di sicurezza del server.

* *Cambia nome host*
+
Modifica il nome dell'host su cui è installata l'appliance virtuale.

* *Indietro*
+
Esce dal menu Configurazione di sistema e torna al menu principale.

* *Uscita*
+
Esce dal menu della console di manutenzione.


