---
permalink: config/reference_regenerate_https_certificate_dialog_box.html 
sidebar: sidebar 
keywords: regenerate, https certificate, dialog, box 
summary: La finestra di dialogo Rigenera certificato HTTPS consente di personalizzare le informazioni di sicurezza e quindi di generare un nuovo certificato HTTPS con tali informazioni. 
---
= Finestra di dialogo Rigenera certificato HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Rigenera certificato HTTPS consente di personalizzare le informazioni di sicurezza e quindi di generare un nuovo certificato HTTPS con tali informazioni.

Le informazioni attuali sul certificato vengono visualizzate in questa pagina.

Le selezioni "`Rigenera utilizzando gli attributi del certificato corrente`" e "`Aggiorna gli attributi del certificato corrente`" consentono di rigenerare il certificato con le informazioni correnti o di generare un certificato con nuove informazioni.

* *Nome comune*
+
Necessario. Il nome di dominio completamente qualificato (FQDN) che desideri proteggere.

+
Nelle configurazioni ad alta disponibilità di Unified Manager, utilizzare l'indirizzo IP virtuale.

* *E-mail*
+
Opzionale. Un indirizzo email per contattare la tua organizzazione; in genere l'indirizzo email dell'amministratore del certificato o del reparto IT.

* *Azienda*
+
Opzionale. Solitamente è il nome della società.

* *Dipartimento*
+
Opzionale. Il nome del reparto della tua azienda.

* *Città*
+
Opzionale. La sede della tua azienda in città.

* *Stato*
+
Opzionale. La sede della tua azienda, non in forma abbreviata, nello stato o nella provincia.

* *Paese*
+
Opzionale. Il paese in cui ha sede la tua azienda.  In genere si tratta di un codice ISO di due lettere del Paese.

* *Nomi alternativi*
+
Necessario. Nomi di dominio aggiuntivi, non primari, che possono essere utilizzati per accedere a questo server oltre all'indirizzo localhost o ad altri indirizzi di rete esistenti.  Separare ogni nome alternativo con una virgola.

+
Selezionare la casella di controllo "Escludi informazioni di identificazione locali (ad esempio localhost)" se si desidera rimuovere le informazioni di identificazione locali dal campo Nomi alternativi nel certificato.  Quando questa casella di controllo è selezionata, nel campo Nomi alternativi verrà utilizzato solo ciò che inserisci nel campo.  Se lasciato vuoto, il certificato risultante non avrà alcun campo Nomi alternativi.

* *DIMENSIONE CHIAVE (ALGORITMO CHIAVE: RSA)*
+
L'algoritmo chiave è impostato su RSA.  È possibile selezionare una delle seguenti dimensioni della chiave: 2048, 3072 o 4096 bit.  La dimensione predefinita della chiave è impostata su 2048 bit.

* *PERIODO DI VALIDITÀ*
+
Il periodo di validità predefinito è 397 giorni.  Se hai effettuato l'aggiornamento da una versione precedente, potresti notare che la validità del certificato precedente è rimasta invariata.



Per maggiori informazioni, vedere link:../config/task_generate_an_https_security_certificate_ocf.html["Generazione di certificati HTTPS"].
