---
permalink: config/reference_unified_manager_roles_and_capabilities.html 
sidebar: sidebar 
keywords: unified manager, user, roles, capabilities 
summary: In base al ruolo utente assegnato, puoi determinare quali operazioni puoi eseguire in Unified Manager. 
---
= Ruoli e capacità degli utenti di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In base al ruolo utente assegnato, puoi determinare quali operazioni puoi eseguire in Unified Manager.

Nella tabella seguente sono riportate le funzioni che ciascun ruolo utente può svolgere:

[cols="6*"]
|===
| Funzione | Operatore | Amministratore di archiviazione | Amministratore dell'applicazione | Schema di integrazione | Schema del report 


 a| 
Visualizza le informazioni sul sistema di archiviazione
 a| 
•
 a| 
•
 a| 
•
 a| 
•
 a| 
•



 a| 
Visualizza altri dati, come cronologie e tendenze della capacità
 a| 
•
 a| 
•
 a| 
•
 a| 
•
 a| 
•



 a| 
Visualizza, assegna e risolvi gli eventi
 a| 
•
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Visualizza gli oggetti del servizio di archiviazione, come le associazioni SVM e i pool di risorse
 a| 
•
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Visualizza le policy di soglia
 a| 
•
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gestire gli oggetti del servizio di archiviazione, come le associazioni SVM e i pool di risorse
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Definisci avvisi
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gestisci le opzioni di gestione dell'archiviazione
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gestire le policy di gestione dell'archiviazione
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gestisci utenti
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Gestisci le opzioni amministrative
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Definire le politiche di soglia
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Gestire l'accesso al database
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Gestire l'integrazione con WFA e fornire l'accesso alle viste del database
 a| 
 a| 
 a| 
 a| 
•
 a| 



 a| 
Pianifica e salva i report
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Eseguire le operazioni "`Fix It`" dalle azioni di gestione
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Fornire accesso in sola lettura alle viste del database
 a| 
 a| 
 a| 
 a| 
 a| 
•

|===