---
permalink: config/task_add_additional_network_interfaces.html 
sidebar: sidebar 
keywords: add, network, interfaces 
summary: È possibile aggiungere nuove interfacce di rete se è necessario separare il traffico di rete. 
---
= Aggiungere interfacce di rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere nuove interfacce di rete se è necessario separare il traffico di rete.

.Prima di iniziare
È necessario aver aggiunto l'interfaccia di rete all'appliance virtuale tramite vSphere.

L'appliance virtuale deve essere accesa.

[NOTE]
====
Non è possibile eseguire questa operazione se Unified Manager è installato su Red Hat Enterprise Linux o su Microsoft Windows.

====
.Passi
. Nel menu principale della console vSphere, selezionare *Configurazione di sistema* > *Riavvia sistema operativo*.
+
Dopo il riavvio, la console di manutenzione è in grado di rilevare la nuova interfaccia di rete aggiunta.

. Accedere alla console di manutenzione.
. Selezionare *Configurazione di rete* > *Abilita interfaccia di rete*.
. Selezionare la nuova interfaccia di rete e premere *Invio*.
+
Selezionare *eth1* e premere *Invio*.

. Digitare *y* per abilitare l'interfaccia di rete.
. Inserisci le impostazioni di rete.
+
Se si utilizza un'interfaccia statica o se non viene rilevato DHCP, verrà richiesto di immettere le impostazioni di rete.

+
Dopo aver inserito le impostazioni di rete, si torna automaticamente al menu *Configurazione di rete*.

. Seleziona *Applica modifiche*.
+
È necessario confermare le modifiche per aggiungere l'interfaccia di rete.


