---
permalink: config/task_change_maintenance_user_password_on_windows.html 
sidebar: sidebar 
keywords: change, maintenance, user, password, windows 
summary: 'È possibile modificare la password dell"utente addetto alla manutenzione di Unified Manager quando necessario.' 
---
= Cambiare la password dell'utente di manutenzione su Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password dell'utente addetto alla manutenzione di Unified Manager quando necessario.

.Passi
. Dalla pagina di accesso dell'interfaccia utente Web di Unified Manager, fare clic su *Password dimenticata*.
+
Viene visualizzata una pagina in cui viene richiesto il nome dell'utente di cui si desidera reimpostare la password.

. Inserisci il nome utente e clicca su *Invia*.
+
Un'e-mail con un collegamento per reimpostare la password verrà inviata all'indirizzo e-mail definito per quel nome utente.

. Fare clic sul *link per reimpostare la password* nell'e-mail e definire la nuova password.
. Torna all'interfaccia utente Web e accedi a Unified Manager utilizzando la nuova password.

