---
permalink: config/task_access_maintenance_console.html 
sidebar: sidebar 
keywords: access, maintenance console 
summary: 'Se l"interfaccia utente di Unified Manager non è in funzione o se è necessario eseguire funzioni non disponibili nell"interfaccia utente, è possibile accedere alla console di manutenzione per gestire il sistema Unified Manager.' 
---
= Accedi alla console di manutenzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'interfaccia utente di Unified Manager non è in funzione o se è necessario eseguire funzioni non disponibili nell'interfaccia utente, è possibile accedere alla console di manutenzione per gestire il sistema Unified Manager.

.Prima di iniziare
È necessario aver installato e configurato Unified Manager.

Dopo 15 minuti di inattività, la console di manutenzione effettua la disconnessione.

[NOTE]
====
Se installato su VMware, se hai già effettuato l'accesso come utente di manutenzione tramite la console VMware, non puoi effettuare l'accesso contemporaneamente tramite Secure Shell.

====
.Fare un passo
. Per accedere alla console di manutenzione, seguire questi passaggi:
+
[cols="2*"]
|===
| Su questo sistema operativo... | Segui questi passaggi... 


 a| 
VMware
 a| 
.. Utilizzando Secure Shell, connettersi all'indirizzo IP o al nome di dominio completo dell'appliance virtuale Unified Manager.
.. Accedi alla console di manutenzione utilizzando il tuo nome utente e la tua password di manutenzione.




 a| 
Linux
 a| 
.. Utilizzando Secure Shell, connettersi all'indirizzo IP o al nome di dominio completo del sistema Unified Manager.
.. Accedi al sistema con il nome utente di manutenzione (umadmin) e la password.
.. Inserisci il comando `maintenance_console` e premere Invio.




 a| 
Finestre
 a| 
.. Accedi al sistema Unified Manager con le credenziali di amministratore.
.. Avvia PowerShell come amministratore di Windows.
.. Inserisci il comando `maintenance_console` e premere Invio.


|===
+
Viene visualizzato il menu della console di manutenzione di Unified Manager.


