---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: 'È possibile modificare la password di accesso dell"utente locale per prevenire potenziali rischi per la sicurezza.' 
---
= Cambia la password dell'utente locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password di accesso dell'utente locale per prevenire potenziali rischi per la sicurezza.

.Prima di iniziare
Devi aver effettuato l'accesso come utente locale.

Le password per l'utente addetto alla manutenzione e per gli utenti remoti non possono essere modificate seguendo questi passaggi.  Per modificare la password di un utente remoto, contattare l'amministratore delle password.  Per modificare la password dell'utente addetto alla manutenzione, vederelink:task_use_maintenance_console.html["Utilizzo della console di manutenzione"] .

.Passi
. Accedi a Unified Manager.
. Dalla barra dei menu in alto, fare clic sull'icona dell'utente e quindi su *Cambia password*.
+
L'opzione *Cambia password* non viene visualizzata se sei un utente remoto.

. Nella finestra di dialogo Cambia password, immettere la password corrente e quella nuova.
. Fare clic su *Salva*.


Se Unified Manager è configurato in una configurazione ad alta disponibilità, è necessario modificare la password sul secondo nodo dell'installazione.  Entrambe le istanze devono avere la stessa password.
