---
permalink: config/task_set_session_timeout_CLI.html 
sidebar: sidebar 
keywords: session timeout, CLI, maximum 
summary: È possibile impostare un valore massimo di timeout della sessione per Unified Manager tramite la CLI, in modo che la sessione venga terminata automaticamente dopo un determinato periodo di tempo. 
---
= Imposta il timeout della sessione tramite CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile impostare un valore massimo di timeout della sessione per Unified Manager tramite la CLI, in modo che la sessione venga terminata automaticamente dopo un determinato periodo di tempo.  Per impostazione predefinita, il timeout della sessione è impostato sul valore massimo, ovvero 4.320 minuti (72 ore).  Ciò significa che la sessione termina automaticamente dopo 72 ore, anche se hai effettuato l'accesso e stai utilizzando attivamente Unified Manager.

.Informazioni su questo compito
È necessario disporre del ruolo di amministratore dell'applicazione.

L'impostazione del timeout della sessione ha effetto su tutte le sessioni degli utenti registrati.

.Passi
. Accedi alla CLI di Unified Manager immettendo `um cli login` comando.  Utilizzare un nome utente e una password validi per l'autenticazione.
. Entra nel `um option set max.session.timeout.value=<in mins>` comando per modificare il valore di timeout della sessione.

