---
permalink: config/task_access_maintenance_console_using_vsphere.html 
sidebar: sidebar 
keywords: access, maintenance, console, using, vsphere, vm console 
summary: 'Se l"interfaccia utente di Unified Manager non è in funzione o se è necessario eseguire funzioni non disponibili nell"interfaccia utente, è possibile accedere alla console di manutenzione per riconfigurare l"appliance virtuale.' 
---
= Accedi alla console di manutenzione tramite la console vSphere VM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'interfaccia utente di Unified Manager non è in funzione o se è necessario eseguire funzioni non disponibili nell'interfaccia utente, è possibile accedere alla console di manutenzione per riconfigurare l'appliance virtuale.

.Prima di iniziare
* Devi essere l'utente addetto alla manutenzione.
* Per accedere alla console di manutenzione, l'appliance virtuale deve essere accesa.


.Passi
. In vSphere Client, individuare l'appliance virtuale Unified Manager.
. Fare clic sulla scheda *Console*.
. Fare clic all'interno della finestra della console per effettuare l'accesso.
. Accedi alla console di manutenzione utilizzando il tuo nome utente e la tua password.
+
Dopo 15 minuti di inattività, la console di manutenzione effettua la disconnessione.


