---
permalink: config/task_view_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: view, https, security, certificate 
summary: È possibile confrontare i dettagli del certificato HTTPS con il certificato recuperato nel browser per assicurarsi che la connessione crittografata del browser a Unified Manager non venga intercettata. 
---
= Visualizza il certificato di sicurezza HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile confrontare i dettagli del certificato HTTPS con il certificato recuperato nel browser per assicurarsi che la connessione crittografata del browser a Unified Manager non venga intercettata.

.Prima di iniziare
È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.

La visualizzazione del certificato consente di verificare il contenuto di un certificato rigenerato o di visualizzare i nomi alternativi del soggetto (SAN) da cui è possibile accedere a Unified Manager.

.Fare un passo
. Nel riquadro di navigazione a sinistra, fare clic su *Generale* > *Certificato HTTPS*.
+
Il certificato HTTPS viene visualizzato nella parte superiore della pagina



Se hai bisogno di visualizzare informazioni più dettagliate sul certificato di sicurezza rispetto a quelle visualizzate nella pagina Certificato HTTPS, puoi visualizzare il certificato di connessione nel tuo browser.
