---
permalink: config/task_access_unified_manager_web_ui.html 
sidebar: sidebar 
keywords: access, unified manager, web ui 
summary: 'Dopo aver installato Unified Manager, puoi accedere all"interfaccia utente Web per configurare Unified Manager e iniziare a monitorare i tuoi sistemi ONTAP .' 
---
= Accedi all'interfaccia utente web di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver installato Unified Manager, puoi accedere all'interfaccia utente Web per configurare Unified Manager e iniziare a monitorare i tuoi sistemi ONTAP .

.Prima di iniziare
* Se è la prima volta che accedi all'interfaccia utente Web, devi effettuare l'accesso come utente di manutenzione (o utente umadmin per le installazioni Linux).
* Se si prevede di consentire agli utenti di accedere a Unified Manager utilizzando il nome breve anziché il nome di dominio completo (FQDN) o l'indirizzo IP, la configurazione di rete deve risolvere questo nome breve in un FQDN valido.
* Se il server utilizza un certificato digitale autofirmato, il browser potrebbe visualizzare un avviso che indica che il certificato non è attendibile.  È possibile accettare il rischio di continuare l'accesso oppure installare un certificato digitale firmato da un'autorità di certificazione (CA) per l'autenticazione del server.


.Passi
. Avviare l'interfaccia utente Web di Unified Manager dal browser utilizzando l'URL visualizzato al termine dell'installazione.  L'URL è l'indirizzo IP o il nome di dominio completo (FQDN) del server Unified Manager.
+
Il collegamento è nel seguente formato: `\https://URL` .

. Accedi all'interfaccia utente Web di Unified Manager utilizzando le tue credenziali utente di manutenzione.



NOTE: Se effettui tre tentativi consecutivi di accesso all'interfaccia utente web senza successo nell'arco di un'ora, verrai bloccato fuori dal sistema e dovrai contattare l'amministratore di sistema.  Questa opzione è valida solo per gli utenti locali.
