---
permalink: config/task_add_users.html 
sidebar: sidebar 
keywords: add, users 
summary: È possibile aggiungere utenti locali o utenti del database utilizzando la pagina Utenti.  È anche possibile aggiungere utenti o gruppi remoti che appartengono a un server di autenticazione.  È possibile assegnare ruoli a questi utenti e, in base ai privilegi dei ruoli, gli utenti possono gestire gli oggetti di archiviazione e i dati con Unified Manager oppure visualizzare i dati in un database. 
---
= Aggiungi utenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere utenti locali o utenti del database utilizzando la pagina Utenti.  È anche possibile aggiungere utenti o gruppi remoti che appartengono a un server di autenticazione.  È possibile assegnare ruoli a questi utenti e, in base ai privilegi dei ruoli, gli utenti possono gestire gli oggetti di archiviazione e i dati con Unified Manager oppure visualizzare i dati in un database.

.Prima di iniziare
* È necessario disporre del ruolo di amministratore dell'applicazione.
* Per aggiungere un utente o un gruppo remoto, è necessario aver abilitato l'autenticazione remota e configurato il server di autenticazione.
* Se si intende configurare l'autenticazione SAML in modo che un provider di identità (IdP) autentichi gli utenti che accedono all'interfaccia grafica, assicurarsi che tali utenti siano definiti come utenti "remoti".
+
L'accesso all'interfaccia utente non è consentito agli utenti di tipo "`local`" o "`maintenance`" quando è abilitata l'autenticazione SAML.



Se si aggiunge un gruppo da Windows Active Directory, tutti i membri diretti e i sottogruppi nidificati possono autenticarsi in Unified Manager, a meno che i sottogruppi nidificati non siano disabilitati.  Se si aggiunge un gruppo da OpenLDAP o da altri servizi di autenticazione, solo i membri diretti di quel gruppo potranno autenticarsi in Unified Manager.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Generale* > *Utenti*.
. Nella pagina Utenti, fare clic su *Aggiungi*.
. Nella finestra di dialogo Aggiungi utente, seleziona il tipo di utente che desideri aggiungere e inserisci le informazioni richieste.
+
Quando si immettono le informazioni utente richieste, è necessario specificare un indirizzo e-mail univoco per quell'utente.  È necessario evitare di specificare indirizzi e-mail condivisi da più utenti.

. Fare clic su *Aggiungi*.

