---
permalink: config/task_enable_remote_logging_of_audit_logs.html 
sidebar: sidebar 
keywords: enable, remote, logging, audit, logs 
summary: È possibile selezionare la casella di controllo Abilita registrazione remota nella finestra di dialogo Configura registri di controllo per abilitare la registrazione di controllo remota.  È possibile utilizzare questa funzionalità per trasferire i registri di controllo a un server Syslog remoto.  Ciò ti consentirà di gestire i registri di controllo quando ci sono vincoli di spazio. 
---
= Abilita la registrazione remota dei log di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile selezionare la casella di controllo *Abilita registrazione remota* nella finestra di dialogo Configura registri di controllo per abilitare la registrazione di controllo remota.  È possibile utilizzare questa funzionalità per trasferire i registri di controllo a un server Syslog remoto.  Ciò ti consentirà di gestire i registri di controllo quando ci sono vincoli di spazio.

La registrazione remota dei registri di controllo fornisce un backup a prova di manomissione nel caso in cui i file del registro di controllo sul server Active IQ Unified Manager vengano manomessi.

.Passi
. Nella finestra di dialogo *Configura registri di controllo*, selezionare la casella di controllo *Abilita registrazione remota*.
+
Vengono visualizzati campi aggiuntivi per configurare la registrazione remota.

. Inserisci *HOSTNAME* e *PORT* del server remoto a cui vuoi connetterti.
. Nel campo *CERTIFICATO CA DEL SERVER*, fare clic su *SFOGLIA* per selezionare un certificato pubblico del server di destinazione.
+
Il certificato deve essere caricato in `.pem` formato.  Questo certificato deve essere ottenuto dal server Syslog di destinazione e non deve essere scaduto.  Il certificato dovrebbe contenere il ``nome host`` selezionato come parte del `SubjectAltName` attributo (SAN).

. Immettere i valori per i seguenti campi: *CHARSET*, *CONNECTION TIMEOUT*, *RECONNECTION DELAY*.
+
Per questi campi i valori devono essere espressi in millisecondi.

. Selezionare il formato Syslog e la versione del protocollo TLS richiesti nei campi *FORMATO* e *PROTOCOLLO*.
. Selezionare la casella di controllo *Abilita autenticazione client* se il server Syslog di destinazione richiede l'autenticazione basata su certificato.
+
Sarà necessario scaricare il certificato di autenticazione client e caricarlo sul server Syslog prima di salvare la configurazione del registro di controllo, altrimenti la connessione non riuscirà.  A seconda del tipo di server Syslog, potrebbe essere necessario creare un hash del certificato di autenticazione client.

+
Esempio: syslog-ng richiede che venga creato un <hash> del certificato utilizzando il comando `openssl x509 -noout -hash -in cert.pem` , quindi dovresti collegare simbolicamente il certificato di autenticazione client a un file denominato dopo <hash> .0.

. Fare clic su *Salva* per configurare la connessione con il server e abilitare la registrazione remota.
+
Verrai reindirizzato alla pagina Registri di controllo.

+
[NOTE]
====
Il valore *Timeout connessione* può influire sulla configurazione.  Se la configurazione impiega più tempo per rispondere rispetto al valore definito, potrebbe verificarsi un errore di configurazione a causa di un errore di connessione.  Per stabilire una connessione riuscita, aumentare il valore *Timeout connessione* e riprovare la configurazione.

====

