---
permalink: install-linux/concept_upgrade_unified_manager_on_rhel.html 
sidebar: sidebar 
keywords: upgrade, unified manager, red hat enterprise, linux 
summary: È possibile aggiornare Unified Manager quando è disponibile una nuova versione del software. 
---
= Aggiorna Unified Manager su Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare Unified Manager quando è disponibile una nuova versione.

Le patch release del software Unified Manager, quando fornite da NetApp, vengono installate utilizzando la stessa procedura delle nuove release.

Se Unified Manager è associato a un'istanza di OnCommand Workflow Automation e sono disponibili nuove versioni del software per entrambi i prodotti, è necessario disconnettere i due prodotti e quindi configurare una nuova connessione Workflow Automation dopo aver eseguito gli aggiornamenti.  Se si esegue l'aggiornamento solo a uno dei prodotti, è necessario accedere a Workflow Automation dopo l'aggiornamento e verificare che stia ancora acquisendo dati da Unified Manager.
