---
permalink: install-linux/task_manually_configure_mysql_repository.html 
sidebar: sidebar 
keywords: manually configure mysql repository, mysql key, keys update 
summary: 'Se il sistema su cui si sta installando Unified Manager non ha accesso al repository MySQL Community Edition, è necessario scaricare e configurare manualmente il repository per un"installazione corretta.' 
---
= Configurare manualmente il repository MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il sistema su cui si sta installando Unified Manager non ha accesso al repository MySQL Community Edition, è necessario scaricare e configurare manualmente il repository per un'installazione corretta.

Il repository MySQL fornisce l'accesso al software MySQL necessario che deve essere installato sul tuo sistema.

[NOTE]
====
Questa operazione potrebbe non riuscire se il sistema non dispone di connettività Internet.  Se il sistema su cui si sta installando Unified Manager non dispone di accesso a Internet, fare riferimento alla documentazione MySQL.

====
.Passi
. Scarica il repository MySQL appropriato per la tua installazione.  Per la versione 8, scaricala da:
+
`wget http://repo.mysql.com/yum/mysql-8.4-community/el/8/x86_64/mysql84-community-release-el8-1.noarch.rpm`

+
Per la versione 9, scaricala da:

+
`wget http://repo.mysql.com/yum/mysql-8.4-community/el/9/x86_64/mysql84-community-release-el9-1.noarch.rpm`

. Configurare il repository MySQL:
+
`yum install mysql84-community-release-.noarch.rpm`



Per il sistema Red Hat Enterprise Linux 8, se si dispone di repository interni con java-11-openjdk, p7zip e altri pacchetti software forniti dal repository AppStream, è necessario disabilitare il repository AppStream e installare MySQL Community Server. Esegui il seguente comando:

[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
Se ricevi un errore di chiave mancante o di mancata corrispondenza delle chiavi e l'installazione non riesce, prova questi passaggi:

* Su un sistema connesso, importare la chiave MySQL aggiornata eseguendo il seguente comando:


[listing]
----
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-<xxxx>

for example:

rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
----
* Su un sistema che non ha connettività Internet, aggiorna il file del repository MySQL e disabilita `gpgcheck` marcando `gpgcheck=0` .

