---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: 'È possibile reimpostare la password JBoss specifica dell"istanza impostata durante l"installazione.  È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l"impostazione di installazione di Unified Manager.  Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.' 
---
= Cambia la password di JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile reimpostare la password JBoss specifica dell'istanza impostata durante l'installazione.  È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l'impostazione di installazione di Unified Manager.  Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.

* È necessario disporre dell'accesso come utente root al sistema Red Hat Enterprise Linux su cui è installato Unified Manager.
* Devi essere in grado di accedere a NetApp fornito `password.sh` script nella directory `/opt/netapp/essentials/bin` .


.Passi
. Accedi come utente root al sistema.
. Arrestare i servizi Unified Manager immettendo i seguenti comandi nell'ordine indicato:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
Non arrestare il software MySQL associato.

. Immettere il seguente comando per avviare il processo di modifica della password:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Quando richiesto, immettere la nuova password JBoss, quindi inserirla una seconda volta per conferma.
+
Tieni presente che la password deve essere compresa tra 8 e 16 caratteri e deve contenere almeno una cifra, una lettera maiuscola e una minuscola e almeno uno di questi caratteri speciali:

+
`+!@%^*-_+=[]:<>.?/~+`

. Al termine dello script, avviare i servizi Unified Manager immettendo i seguenti comandi nell'ordine indicato:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Dopo aver avviato tutti i servizi, è possibile accedere all'interfaccia utente di Unified Manager.

