---
permalink: install-linux/task_install_unified_manager_linux.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: È possibile installare Unified Manager su una piattaforma Red Hat Enterprise Linux fisica o virtuale. 
---
= Installa Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare Unified Manager su una piattaforma Red Hat Enterprise Linux fisica o virtuale.

.Prima di iniziare
* Il sistema su cui si desidera installare Unified Manager deve soddisfare i requisiti di sistema e software.
+
Vederelink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisiti di sistema hardware"] .

+
Vederelink:reference_red_hat_software_and_installation_requirements.html["Requisiti di installazione e software Linux"] .

* Devi aver scaricato Unified Manager `.zip` file dal sito di supporto NetApp al sistema di destinazione.
* Avresti dovuto verificare l'integrità del file scaricato `.zip` file.
* È necessario disporre di un browser web supportato.
* Il software di emulazione del terminale deve avere lo scrollback abilitato.


Il sistema Red Hat Enterprise Linux potrebbe avere installate tutte le versioni richieste del software di supporto richiesto (Java, MySQL, utilità aggiuntive), solo una parte del software richiesto oppure potrebbe essere un sistema appena installato senza nessuno dei software richiesti.

.Passi
. Accedi al server su cui stai installando Unified Manager.
. Immettere i comandi appropriati per valutare quale software potrebbe richiedere l'installazione o l'aggiornamento sul sistema di destinazione per supportare l'installazione:
+
[cols="2*"]
|===
| Software richiesto e versione minima | Comando per verificare il software e la versione 


 a| 
OpenJDK versione 11.0.25
 a| 
`java -version`



 a| 
MySQL 8.4.4 Community Edition
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 16.02
 a| 
`rpm -qa | grep p7zip`

|===
. Se la versione installata di MySQL è precedente a MySQL 8.4.4 Community Edition, immettere il seguente comando per disinstallarla:
+
`rpm -e <mysql_package_name>`

+
Se si ricevono errori di dipendenza, è necessario aggiungere `--nodeps` opzione per disinstallare il componente.

. Passare alla directory in cui è stato scaricato il file di installazione `.zip` file ed espandere il bundle Unified Manager:
+
`unzip ActiveIQUnifiedManager-_<version>_.zip`

+
Il necessario `.rpm` i moduli per Unified Manager vengono decompressi nella directory di destinazione.

. Verificare che il seguente modulo sia disponibile nella directory:
+
`ls *.rpm`

+
`netapp-um<version>.x86_64.rpm`

. Eseguire lo script di preinstallazione per assicurarsi che non vi siano impostazioni di configurazione del sistema o software installati che potrebbero entrare in conflitto con l'installazione di Unified Manager:
+
`sudo ./pre_install_check.sh`

+
Lo script di preinstallazione verifica che il sistema disponga di un abbonamento Red Hat Enterprise Linux valido e che abbia accesso ai repository software richiesti.  Se lo script identifica dei problemi, è necessario risolverli prima di installare Unified Manager.

+
Per il sistema Red Hat Enterprise Linux 8, se si dispone di repository interni con JDK 11 - OpenJDK, p7zip e altri pacchetti software forniti dal repository AppStream, è necessario disabilitare il repository AppStream e installare MySQL Community Server. Esegui il seguente comando:

+
[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
. *Facoltativo:* è necessario eseguire il passaggio 7 solo se il sistema non è connesso a Internet e se è necessario scaricare manualmente i pacchetti necessari per l'installazione.  Se il tuo sistema ha accesso a Internet e tutti i pacchetti richiesti sono disponibili, vai al passaggio 8.  Per i sistemi che non sono connessi a Internet o che non utilizzano i repository di Red Hat Enterprise Linux, eseguire i seguenti passaggi per determinare se mancano pacchetti necessari, quindi scaricare tali pacchetti:
+
.. Sul sistema su cui stai installando Unified Manager, visualizza l'elenco dei pacchetti disponibili e non disponibili: +
`yum install netapp-um<version>.x86_64.rpm --assumeno`
+
Gli elementi nella sezione "`Installazione:`" sono i pacchetti disponibili nella directory corrente, mentre gli elementi nella sezione "`Installazione per dipendenze:`" sono i pacchetti mancanti nel sistema.

.. Su un sistema con accesso a Internet, scarica i pacchetti mancanti:
+
`yum install <package_name> --downloadonly --downloaddir=.`

+
[NOTE]
====
Poiché il plug-in "`yum-plugin-downloadonly`" non è sempre abilitato sui sistemi Red Hat Enterprise Linux, potrebbe essere necessario abilitare la funzionalità per scaricare un pacchetto senza installarlo:
`yum install yum-plugin-downloadonly`

====
.. Copia i pacchetti mancanti dal sistema connesso a Internet al tuo sistema di installazione.


. Come utente root, o utilizzando `sudo` , eseguire il seguente comando per installare il software:
+
`yum install netapp-um<version>.x86_64.rpm`

+
Questo comando installa i pacchetti .rpm, tutto l'altro software di supporto necessario e il software Unified Manager.

+
Se l'installazione fallisce con l'errore GPG NOKEY, utilizzare `rpm --import` per importare le chiavi da un URL:

+
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023[]

+
[NOTE]
====
Non tentare l'installazione utilizzando comandi alternativi (ad esempio `rpm -ivh` ).  Per un'installazione corretta di Unified Manager su un sistema Red Hat Enterprise Linux è necessario che tutti i file di Unified Manager e i file correlati vengano installati in un ordine specifico in una struttura di directory specifica che viene applicata automaticamente da `yum install netapp-um<version>.x86_64.rpm` comando.

====
. Ignorare la notifica e-mail visualizzata subito dopo i messaggi di installazione.
+
L'e-mail notifica all'utente root un errore iniziale del cron job, che non ha alcun effetto negativo sull'installazione.

. Una volta completati i messaggi di installazione, scorrere indietro tra i messaggi fino a visualizzare il messaggio in cui il sistema visualizza un indirizzo IP o un URL per l'interfaccia utente Web di Unified Manager, il nome utente di manutenzione (umadmin) e una password predefinita.
+
Il messaggio è simile al seguente:

+
[listing]
----
Active IQ Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. Registrare l'indirizzo IP o l'URL, il nome utente assegnato (umadmin) e la password corrente.
. Se hai creato un account utente umadmin con una directory home personalizzata prima di installare Unified Manager, devi specificare la shell di accesso utente umadmin:
+
`usermod -s /bin/maintenance-user-shell.sh umadmin`



Accedere all'interfaccia utente Web per modificare la password predefinita dell'utente umadmin ed eseguire la configurazione iniziale di Unified Manager, come descritto inlink:../config/concept_configure_unified_manager.html["Configurazione di Active IQ Unified Manager"] .  È obbligatorio modificare la password predefinita dell'utente umadmin.
