---
permalink: events/concept_what_active_iq_platform_events_are.html 
sidebar: sidebar 
keywords: active iq, platform, events 
summary: Unified Manager può visualizzare gli eventi rilevati dalla piattaforma Active IQ .  Questi eventi vengono creati eseguendo una serie di regole sui messaggi AutoSupport generati da tutti i sistemi di archiviazione monitorati da Unified Manager. 
---
= Cosa sono gli eventi della piattaforma Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager può visualizzare gli eventi rilevati dalla piattaforma Active IQ .  Questi eventi vengono creati eseguendo una serie di regole sui messaggi AutoSupport generati da tutti i sistemi di archiviazione monitorati da Unified Manager.

Per maggiori informazioni, vedere link:../events/concept_how_active_iq_platform_events_are_generated.html["Come vengono generati gli eventi della piattaforma Active IQ"].

Unified Manager verifica automaticamente la presenza di un nuovo file di regole e scarica un nuovo file solo quando sono presenti regole più recenti.  Nei siti senza accesso alla rete esterna, è necessario caricare manualmente le regole da *Gestione archiviazione* > *Configurazione evento* > *Carica regole*.

Questi eventi Active IQ non si sovrappongono agli eventi Unified Manager esistenti e identificano incidenti o rischi relativi alla configurazione del sistema, al cablaggio, alle best practice e ai problemi di disponibilità.

Per ulteriori informazioni sull'abilitazione degli eventi della piattaforma, vederelink:../config/concept_active_iq_platform_events.html["Abilitazione degli eventi del portale Active IQ"] .  Per ulteriori informazioni sul caricamento del file delle regole, vederelink:../events/task_upload_new_active_iq_rules_file.html["Caricamento di un nuovo file di regole Active IQ"] .

NetApp Active IQ è un servizio basato su cloud che fornisce analisi predittive e supporto proattivo per ottimizzare le operazioni del sistema di storage nel cloud ibrido NetApp .  Vedere https://www.netapp.com/us/products/data-infrastructure-management/active-iq.aspx["NetApp Active IQ"] per maggiori informazioni.
