---
permalink: events/reference_snapmirror_relationship_events.html 
sidebar: sidebar 
keywords: snapmirror, relationship, events, impact area, protection 
summary: 'Gli eventi di relazione SnapMirror forniscono informazioni sullo stato delle relazioni SnapMirror asincrone e sincrone, in modo da poter monitorare eventuali problemi.  Gli eventi di relazione SnapMirror asincroni vengono generati sia per le VM di archiviazione che per i volumi, mentre gli eventi di relazione SnapMirror sincroni vengono generati solo per le relazioni dei volumi.  Non vengono generati eventi per i volumi costituenti che fanno parte delle relazioni di ripristino di emergenza della VM di archiviazione.  Gli eventi sono raggruppati in base all"area di impatto e includono il nome dell"evento e della trappola, il livello di impatto, il tipo di origine e la gravità.' 
---
= Eventi di relazione SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi di relazione SnapMirror forniscono informazioni sullo stato delle relazioni SnapMirror asincrone e sincrone, in modo da poter monitorare eventuali problemi.  Gli eventi di relazione SnapMirror asincroni vengono generati sia per le VM di archiviazione che per i volumi, mentre gli eventi di relazione SnapMirror sincroni vengono generati solo per le relazioni dei volumi.  Non vengono generati eventi per i volumi costituenti che fanno parte delle relazioni di ripristino di emergenza della VM di archiviazione.  Gli eventi sono raggruppati in base all'area di impatto e includono il nome dell'evento e della trappola, il livello di impatto, il tipo di origine e la gravità.



== Area di impatto: protezione

Un asterisco (*) identifica gli eventi EMS che sono stati convertiti in eventi Unified Manager.

[NOTE]
====
Gli eventi delle relazioni SnapMirror vengono generati per le VM di archiviazione protette dal ripristino di emergenza delle VM di archiviazione, ma non per le relazioni tra oggetti costituenti.

====
|===
| Nome dell'evento (nome della trappola) | Livello di impatto | Tipo di fonte | Gravità 


 a| 
Replica dello specchio non funzionante (ocumEvtSnapmirrorRelationshipUnhealthy)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Avvertimento



 a| 
Replicazione speculare interrotta (ocumEvtSnapmirrorRelationshipStateBrokenoff)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Inizializzazione della replica mirror non riuscita (ocumEvtSnapmirrorRelationshipInitializeFailed)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Aggiornamento della replica mirror non riuscito (ocumEvtSnapmirrorRelationshipUpdateFailed)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Errore di ritardo della replica mirror (ocumEvtSnapMirrorRelationshipLagError)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Avviso di ritardo nella replica dello specchio (ocumEvtSnapMirrorRelationshipLagWarning)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Avvertimento



 a| 
Risincronizzazione della replica mirror non riuscita (ocumEvtSnapmirrorRelationshipResyncFailed)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Replica sincrona fuori sincrono *(syncSnapmirrorRelationshipOutofsync)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Avvertimento



 a| 
Replica sincrona ripristinata *(syncSnapmirrorRelationshipInSync)
 a| 
Evento
 a| 
Relazione SnapMirror
 a| 
Informazioni



 a| 
Replica sincrona: risincronizzazione automatica non riuscita *(syncSnapmirrorRelationshipAutoSyncRetryFailed)
 a| 
Rischio
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Ontap Mediator è stato aggiunto al cluster (snapmirrorMediatorAdded)
 a| 
Evento
 a| 
Grappolo
 a| 
Informazioni



 a| 
Ontap Mediator è stato rimosso dal cluster (snapmirrorMediatorRemoved)
 a| 
Evento
 a| 
Grappolo
 a| 
Informazioni



 a| 
Ontap Mediator non è raggiungibile dal cluster (snapmirrorMediatorUnreachable)
 a| 
Rischio
 a| 
Mediatore
 a| 
Avvertimento



 a| 
Ontap Mediator non è accessibile dal cluster (snapmirrorMediatorMisconfigured)
 a| 
Rischio
 a| 
Mediatore
 a| 
Errore



 a| 
La connettività di Ontap Mediator è stata ristabilita, è risincronizzata ed è pronta per la sincronizzazione attiva SnapMirror (snapmirrorMediatorInQuorum)
 a| 
Evento
 a| 
Mediatore
 a| 
Informazioni

|===