---
permalink: events/reference_volume_move_status_events.html 
sidebar: sidebar 
keywords: volume, move, status, events, impact area, capacity 
summary: 'Gli eventi sullo stato dello spostamento del volume ti informano sullo stato dello spostamento del volume, in modo da poter monitorare eventuali problemi.  Gli eventi sono raggruppati in base all"area di impatto e includono il nome dell"evento e della trappola, il livello di impatto, il tipo di origine e la gravità.' 
---
= Eventi di stato di spostamento del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi sullo stato dello spostamento del volume ti informano sullo stato dello spostamento del volume, in modo da poter monitorare eventuali problemi.  Gli eventi sono raggruppati in base all'area di impatto e includono il nome dell'evento e della trappola, il livello di impatto, il tipo di origine e la gravità.



== Area di impatto: capacità

|===
| Nome dell'evento (nome della trappola) | Livello di impatto | Tipo di fonte | Gravità 


 a| 
Stato dello spostamento del volume: in corso (non applicabile)
 a| 
Evento
 a| 
Volume
 a| 
Informazioni



 a| 
Stato spostamento volume - Fallito (ocumEvtVolumeMoveFailed)
 a| 
Rischio
 a| 
Volume
 a| 
Errore



 a| 
Stato del trasferimento del volume: completato (non applicabile)
 a| 
Evento
 a| 
Volume
 a| 
Informazioni



 a| 
Spostamento del volume - Cutover differito (ocumEvtVolumeMoveCutoverDeferred)
 a| 
Rischio
 a| 
Volume
 a| 
Avvertimento

|===