---
permalink: events/reference_nvme_namespace_events.html 
sidebar: sidebar 
keywords: nvme, namespace, events, impact area, availability, performance 
summary: 'Gli eventi dello spazio dei nomi NVMe forniscono informazioni sullo stato dei tuoi spazi dei nomi, in modo da poter monitorare eventuali problemi.  Gli eventi sono raggruppati in base all"area di impatto e includono il nome dell"evento e della trappola, il livello di impatto, il tipo di origine e la gravità.' 
---
= Eventi dello spazio dei nomi NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi dello spazio dei nomi NVMe forniscono informazioni sullo stato dei tuoi spazi dei nomi, in modo da poter monitorare eventuali problemi.  Gli eventi sono raggruppati in base all'area di impatto e includono il nome dell'evento e della trappola, il livello di impatto, il tipo di origine e la gravità.

Un asterisco (*) identifica gli eventi EMS che sono stati convertiti in eventi Unified Manager.



== Area di impatto: disponibilità

|===
| Nome dell'evento (nome della trappola) | Livello di impatto | Tipo di fonte | Gravità 


 a| 
NVMeNS offline *(nvmeNamespaceStatusOffline)
 a| 
Evento
 a| 
Spazio dei nomi
 a| 
Informazioni



 a| 
NVMeNS Online *(nvmeNamespaceStatusOnline)
 a| 
Evento
 a| 
Spazio dei nomi
 a| 
Informazioni



 a| 
NVMeNS Spazio esaurito *(nvmeNamespaceSpaceOutOfSpace)
 a| 
Rischio
 a| 
Spazio dei nomi
 a| 
Avvertimento



 a| 
NVMeNS Destroy *(nvmeNamespaceDestroy)
 a| 
Evento
 a| 
Spazio dei nomi
 a| 
Informazioni

|===


== Area di impatto: prestazioni

|===
| Nome dell'evento (nome della trappola) | Livello di impatto | Tipo di fonte | Gravità 


 a| 
Soglia critica IOPS dello spazio dei nomi NVMe violata (ocumNvmeNamespaceIopsIncident)
 a| 
Incidente
 a| 
Spazio dei nomi
 a| 
Critico



 a| 
Soglia di avviso IOPS dello spazio dei nomi NVMe violata (ocumNvmeNamespaceIopsWarning)
 a| 
Rischio
 a| 
Spazio dei nomi
 a| 
Avvertimento



 a| 
Soglia critica MB/s dello spazio dei nomi NVMe violata (ocumNvmeNamespaceMbpsIncident)
 a| 
Incidente
 a| 
Spazio dei nomi
 a| 
Critico



 a| 
Soglia di avviso MB/s dello spazio dei nomi NVMe violata (ocumNvmeNamespaceMbpsWarning)
 a| 
Rischio
 a| 
Spazio dei nomi
 a| 
Avvertimento



 a| 
Soglia critica di latenza dello spazio dei nomi NVMe ms/op violata (ocumNvmeNamespaceLatencyIncident)
 a| 
Incidente
 a| 
Spazio dei nomi
 a| 
Critico



 a| 
Soglia di avviso di latenza ms/op dello spazio dei nomi NVMe violata (ocumNvmeNamespaceLatencyWarning)
 a| 
Rischio
 a| 
Spazio dei nomi
 a| 
Avvertimento



 a| 
Soglia critica di latenza e IOPS dello spazio dei nomi NVMe violata (ocumNvmeNamespaceLatencyIopsIncident)
 a| 
Incidente
 a| 
Spazio dei nomi
 a| 
Critico



 a| 
Soglia di avviso di latenza e IOPS dello spazio dei nomi NVMe violata (ocumNvmeNamespaceLatencyIopsWarning)
 a| 
Rischio
 a| 
Spazio dei nomi
 a| 
Avvertimento



 a| 
Latenza dello spazio dei nomi NVMe e soglia critica MB/s violata (ocumNvmeNamespaceLatencyMbpsIncident)
 a| 
Incidente
 a| 
Spazio dei nomi
 a| 
Critico



 a| 
Soglia di avviso di latenza e MB/s dello spazio dei nomi NVMe violata (ocumNvmeNamespaceLatencyMbpsWarning)
 a| 
Rischio
 a| 
Spazio dei nomi
 a| 
Avvertimento

|===