---
permalink: events/reference_add_alert_dialog_box.html 
sidebar: sidebar 
keywords: add, alert, dialog, box, name, resources, events, actions, command buttons 
summary: 'È possibile creare avvisi per essere avvisati quando viene generato un evento specifico, in modo da poter risolvere il problema rapidamente e ridurre al minimo l"impatto sull"ambiente.  È possibile creare avvisi per una singola risorsa o per un insieme di risorse e per eventi di un tipo di gravità specifico.  È inoltre possibile specificare il metodo di notifica e la frequenza degli avvisi.' 
---
= Finestra di dialogo Aggiungi avviso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare avvisi per essere avvisati quando viene generato un evento specifico, in modo da poter risolvere il problema rapidamente e ridurre al minimo l'impatto sull'ambiente.  È possibile creare avvisi per una singola risorsa o per un insieme di risorse e per eventi di un tipo di gravità specifico.  È inoltre possibile specificare il metodo di notifica e la frequenza degli avvisi.

È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.



== Nome

Quest'area consente di specificare un nome e una descrizione per l'avviso:

* *Nome avviso*
+
Consente di specificare un nome per l'avviso.

* *Descrizione dell'avviso*
+
Consente di specificare una descrizione per l'avviso.





== Risorse

Quest'area consente di selezionare una singola risorsa o di raggruppare le risorse in base a una regola dinamica per la quale si desidera attivare l'avviso.  Una _regola dinamica_ è l'insieme di risorse filtrate in base alla stringa di testo specificata.  È possibile cercare risorse selezionando un tipo di risorsa dall'elenco a discesa oppure è possibile specificare il nome esatto della risorsa per visualizzarne una specifica.

Se si crea un avviso da una qualsiasi delle pagine dei dettagli dell'oggetto di archiviazione, l'oggetto di archiviazione viene automaticamente incluso nell'avviso.

* *Includere*
+
Consente di includere le risorse per le quali si desidera attivare gli avvisi.  È possibile specificare una stringa di testo per raggruppare le risorse che corrispondono alla stringa e selezionare questo gruppo da includere nell'avviso.  Ad esempio, è possibile raggruppare tutti i volumi il cui nome contiene la stringa "abc".

* *Escludere*
+
Consente di escludere le risorse per le quali non si desidera attivare avvisi.  Ad esempio, è possibile escludere tutti i volumi il cui nome contiene la stringa "xyz".

+
La scheda Escludi viene visualizzata solo quando selezioni tutte le risorse di un particolare tipo di risorsa: ad esempio, +<<All Volumes>> O<<All Volumes whose name contains 'xyz'>> +.

+
Se una risorsa è conforme sia alle regole di inclusione che a quelle di esclusione specificate, la regola di esclusione ha la precedenza sulla regola di inclusione e l'avviso non viene generato per l'evento.





== Eventi

In questa area è possibile selezionare gli eventi per i quali si desidera creare gli avvisi.  È possibile creare avvisi per eventi in base a una particolare gravità o per un insieme di eventi.

Per selezionare più di un evento, tieni premuto il tasto Ctrl mentre effettui le selezioni.

* *Gravità dell'evento*
+
Consente di selezionare gli eventi in base al tipo di gravità, che può essere Critico, Errore o Avviso.

* *Il nome dell'evento contiene*
+
Consente di selezionare gli eventi il cui nome contiene i caratteri specificati.





== Azioni

In questa area è possibile specificare gli utenti a cui inviare una notifica quando viene attivato un avviso.  È inoltre possibile specificare il metodo di notifica e la frequenza della notifica.

* *Avvisa questi utenti*
+
Consente di specificare l'indirizzo email o il nome utente dell'utente che riceverà le notifiche.

+
Se si modifica l'indirizzo email specificato per l'utente e si riapre l'avviso per modificarlo, il campo Nome appare vuoto perché l'indirizzo email modificato non è più associato all'utente precedentemente selezionato.  Inoltre, se hai modificato l'indirizzo email dell'utente selezionato dalla pagina Utenti, l'indirizzo email modificato non verrà aggiornato per l'utente selezionato.

* *Frequenza di notifica*
+
Consente di specificare la frequenza con cui il server di gestione invia notifiche finché l'evento non viene riconosciuto, risolto o spostato nello stato obsoleto.

+
Puoi scegliere i seguenti metodi di notifica:

+
** Notificare solo una volta
** Notificare con una frequenza specificata
** Notificare con una frequenza specificata entro l'intervallo di tempo specificato


* *Emetti trap SNMP*
+
Selezionando questa casella è possibile specificare se le trap SNMP devono essere inviate all'host SNMP configurato globalmente.

* *Esegui script*
+
Consente di aggiungere il proprio script personalizzato all'avviso.  Questo script viene eseguito quando viene generato un avviso.

+
[NOTE]
====
Se questa funzionalità non è disponibile nell'interfaccia utente, è perché è stata disabilitata dall'amministratore.  Se necessario, è possibile abilitare questa funzionalità da *Gestione archiviazione* > *Impostazioni funzionalità*.

====




== Pulsanti di comando

* *Salva*
+
Crea un avviso e chiude la finestra di dialogo.

* *Cancellare*
+
Annulla le modifiche e chiude la finestra di dialogo.


