---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: In qualità di amministratore di storage, puoi utilizzare i comandi CLI per eseguire query sugli oggetti di storage, ad esempio su cluster, aggregati, volumi, qtree e LUN. 
---
= Comandi CLI di Unified Manager supportati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In qualità di amministratore di storage, puoi utilizzare i comandi CLI per eseguire query sugli oggetti di storage, ad esempio su cluster, aggregati, volumi, qtree e LUN.  È possibile utilizzare i comandi CLI per interrogare il database interno di Unified Manager e il database ONTAP .  È anche possibile utilizzare i comandi CLI negli script che vengono eseguiti all'inizio o alla fine di un'operazione oppure quando viene attivato un avviso.

Tutti i comandi devono essere preceduti dal comando `um cli login` e un nome utente e una password validi per l'autenticazione.


NOTE: Per eseguire il comando _um run_, assicurati che il tuo account abbia accesso all'applicazione _console_.

|===
| comando CLI | Descrizione | Produzione 


 a| 
`um cli login -u <username> [-p <password>]`
 a| 
Accede alla CLI.  Per motivi di sicurezza, è opportuno immettere solo il nome utente dopo l'opzione "-u".  Se utilizzato in questo modo, verrà richiesta la password, che non verrà memorizzata nella cronologia o nella tabella dei processi.  La sessione scade dopo tre ore dal momento dell'accesso, dopodiché l'utente dovrà effettuare nuovamente l'accesso.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um cli logout`
 a| 
Esce dalla CLI.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um help`
 a| 
Visualizza tutti i sottocomandi di primo livello.
 a| 
Visualizza tutti i sottocomandi di primo livello.



 a| 
`um run cmd [ -t <timeout> ] <cluster> <command>`
 a| 
Il modo più semplice per eseguire un comando su uno o più host.  Utilizzato principalmente per gli script di avviso per ottenere o eseguire un'operazione su ONTAP.  L'argomento facoltativo timeout imposta un limite di tempo massimo (in secondi) per il completamento del comando sul client.  Il valore predefinito è 0 (attendi per sempre).
 a| 
Come ricevuto da ONTAP.



 a| 
`um run query <sql command>`
 a| 
Esegue una query SQL.  Sono consentite solo le query che leggono dal database.  Non sono supportate operazioni di aggiornamento, inserimento o eliminazione.
 a| 
I risultati vengono visualizzati in forma tabellare.  Se viene restituito un set vuoto, oppure se si verifica un errore di sintassi o una richiesta errata, viene visualizzato il messaggio di errore appropriato.



 a| 
`um datasource add -u <username> -P <password> [ -t <protocol> ] [ -p <port> ] <hostname-or-ip>`
 a| 
Aggiunge un'origine dati all'elenco dei sistemi di archiviazione gestiti.  Un'origine dati descrive come vengono effettuate le connessioni ai sistemi di archiviazione.  Quando si aggiunge un'origine dati, è necessario specificare le opzioni -u (nome utente) e -P (password).  L'opzione -t (protocollo) specifica il protocollo utilizzato per comunicare con il cluster (http o https).  Se il protocollo non è specificato, verranno tentati entrambi i protocolli. L'opzione -p (porta) specifica la porta utilizzata per comunicare con il cluster.  Se la porta non viene specificata, verrà tentato il valore predefinito del protocollo appropriato.  Questo comando può essere eseguito solo dall'amministratore dell'archiviazione.
 a| 
Richiede all'utente di accettare il certificato e stampa il messaggio corrispondente.



 a| 
`um datasource list [ <datasource-id>]`
 a| 
Visualizza le origini dati per i sistemi di archiviazione gestiti.
 a| 
Visualizza i seguenti valori in formato tabellare: `ID Address Port, Protocol Acquisition Status, Analysis Status, Communication status, Acquisition Message, and Analysis Message` .



 a| 
`um datasource modify [ -h <hostname-or-ip> ] [ -u <username> ] [ -P <password> ] [ -t <protocol> ] [ -p <port> ] <datasource-id>`
 a| 
Modifica una o più opzioni dell'origine dati.  Può essere eseguito solo dall'amministratore dell'archiviazione.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um datasource remove <datasource-id>`
 a| 
Rimuove l'origine dati (cluster) da Unified Manager.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um option list [ <option> .. ]`
 a| 
Elenca tutte le opzioni che è possibile configurare utilizzando il comando set.
 a| 
Visualizza i seguenti valori in formato tabellare: `Name, Value, Default Value, and Requires Restart.`



 a| 
`um option set <option-name>=<option-value> [ <option-name>=<option-value> ... ]`
 a| 
Imposta una o più opzioni.  Il comando può essere eseguito solo dall'amministratore dell'archiviazione.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um version`
 a| 
Visualizza la versione del software Unified Manager.
 a| 
`Version ("9.6")`



 a| 
`um lun list [-q] [ -ObjectType <object-id>]`
 a| 
Elenca i LUN dopo il filtraggio sull'oggetto specificato.  -q è applicabile a tutti i comandi per non mostrare alcuna intestazione.  ObjectType può essere lun, qtree, cluster, volume, quota o svm.

Per esempio:

*`um lun list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti i LUN all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare: `ID and LUN path.`



 a| 
`um svm list [-q] [ -ObjectType <object-id>]`
 a| 
Elenca le VM di archiviazione dopo aver filtrato l'oggetto specificato.  ObjectType può essere lun, qtree, cluster, volume, quota o svm.

Per esempio:

*`um svm list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutte le VM di archiviazione all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare: `Name and Cluster ID.`



 a| 
`um qtree list [-q] [ -ObjectType <object-id>]`
 a| 
Elenca i qtree dopo il filtraggio sull'oggetto specificato.  -q è applicabile a tutti i comandi per non mostrare alcuna intestazione.  ObjectType può essere lun, qtree, cluster, volume, quota o svm.

Per esempio:

*`um qtree list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti i qtree all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare: `Qtree ID and Qtree Name.`



 a| 
`um disk list [-q] [-ObjectType <object-id>]`
 a| 
Elenca i dischi dopo il filtraggio in base all'oggetto specificato.  ObjectType può essere disk, aggr, node o cluster.

Per esempio:

*`um disk list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti i dischi all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare `ObjectType and object-id` .



 a| 
`um cluster list [-q] [-ObjectType <object-id>]`
 a| 
Elenca i cluster dopo il filtraggio in base all'oggetto specificato.  ObjectType può essere disk, aggr, node, cluster, lun, qtree, volume, quota o svm.

Per esempio:

*`um cluster list -aggr 1`*

In questo esempio, "-aggr" è objectType e "1" è objectId.  Il comando elenca il cluster a cui appartiene l'aggregato con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare: `Name, Full Name, Serial Number, Datasource Id, Last Refresh Time, and Resource Key` .



 a| 
`um cluster node list [-q] [-ObjectType <object-id>]`
 a| 
Elenca i nodi del cluster dopo il filtraggio in base all'oggetto specificato.  ObjectType può essere disk, aggr, node o cluster.

Per esempio:

*`um cluster node list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti i nodi all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare `Name and Cluster ID` .



 a| 
`um volume list [-q] [-ObjectType <object-id>]`
 a| 
Elenca i volumi dopo il filtraggio in base all'oggetto specificato.  ObjectType può essere lun, qtree, cluster, volume, quota, svm o aggregate.

Per esempio:

*`um volume list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti i volumi all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare `Volume ID and Volume Name` .



 a| 
`um quota user list [-q] [-ObjectType <object-id>]`
 a| 
Elenca gli utenti con quota dopo aver filtrato l'oggetto specificato.  ObjectType può essere qtree, cluster, volume, quota o svm.

Per esempio:

*`um quota user list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti gli utenti quota all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare `ID, Name, SID and Email` .



 a| 
`um aggr list [-q] [-ObjectType <object-id>]`
 a| 
Elenca gli aggregati dopo il filtraggio in base all'oggetto specificato.  ObjectType può essere disk, aggr, node, cluster o volume.

Per esempio:

*`um aggr list -cluster 1`*

In questo esempio, "-cluster" è objectType e "1" è objectId.  Il comando elenca tutti gli aggregati all'interno del cluster con ID 1.
 a| 
Visualizza i seguenti valori in formato tabellare `Aggr ID, and Aggr Name` .



 a| 
`um event ack <event-ids>`
 a| 
Riconosce uno o più eventi.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um event resolve <event-ids>`
 a| 
Risolve uno o più eventi.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um event assign -u <username> <event-id>`
 a| 
Assegna un evento a un utente.
 a| 
Visualizza il messaggio corrispondente.



 a| 
`um event list [ -s <source> ] [ -S <event-state-filter-list>.. ] [ <event-id> .. ]`
 a| 
Elenca gli eventi generati dal sistema o dall'utente.  Filtra gli eventi in base a origine, stato e ID.
 a| 
Visualizza i seguenti valori in formato tabellare `Source, Source type, Name, Severity, State, User and Timestamp` .



 a| 
`um backup restore -f <backup_file_path_and_name>`
 a| 
Ripristina un backup del database MySQL utilizzando file .7z.
 a| 
Visualizza il messaggio corrispondente.

|===