---
permalink: events/reference_snapshot_events.html 
sidebar: sidebar 
keywords: snapshot, events, impact area, availability 
summary: 'Gli eventi snapshot forniscono informazioni sullo stato degli snapshot, consentendo di monitorarli per individuare potenziali problemi.  Gli eventi sono raggruppati in base all"area di impatto e includono il nome dell"evento, il nome della trappola, il livello di impatto, il tipo di origine e la gravità.' 
---
= Eventi snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi snapshot forniscono informazioni sullo stato degli snapshot, consentendo di monitorarli per individuare potenziali problemi.  Gli eventi sono raggruppati in base all'area di impatto e includono il nome dell'evento, il nome della trappola, il livello di impatto, il tipo di origine e la gravità.



== Area di impatto: disponibilità

|===
| Nome dell'evento (nome della trappola) | Livello di impatto | Tipo di fonte | Gravità 


 a| 
Eliminazione automatica snapshot disabilitata (non applicabile)
 a| 
Evento
 a| 
Volume
 a| 
Informazioni



 a| 
Eliminazione automatica snapshot abilitata (non applicabile)
 a| 
Evento
 a| 
Volume
 a| 
Informazioni



 a| 
Configurazione di eliminazione automatica snapshot modificata (non applicabile)
 a| 
Evento
 a| 
Volume
 a| 
Informazioni

|===