---
permalink: events/reference_user_and_group_quota_events.html 
sidebar: sidebar 
keywords: user, group, quota, events, impact area, capacity 
summary: 'Gli eventi relativi alle quote utente e gruppo forniscono informazioni sulla capacità della quota utente e gruppo utente, nonché sui limiti di file e disco, in modo da poter monitorare potenziali problemi.  Gli eventi sono raggruppati in base all"area di impatto e includono il nome dell"evento e della trappola, il livello di impatto, il tipo di origine e la gravità.' 
---
= Eventi di quota utente e gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi relativi alle quote utente e gruppo forniscono informazioni sulla capacità della quota utente e gruppo utente, nonché sui limiti di file e disco, in modo da poter monitorare potenziali problemi.  Gli eventi sono raggruppati in base all'area di impatto e includono il nome dell'evento e della trappola, il livello di impatto, il tipo di origine e la gravità.



== Area di impatto: capacità

|===
| Nome dell'evento (nome della trappola) | Livello di impatto | Tipo di fonte | Gravità 


 a| 
Limite flessibile dello spazio su disco della quota utente o gruppo violato (ocumEvtUserOrGroupQuotaDiskSpaceSoftLimitBreached)
 a| 
Rischio
 a| 
Quota utente o gruppo
 a| 
Avvertimento



 a| 
Limite massimo di spazio su disco per utente o gruppo raggiunto (ocumEvtUserOrGroupQuotaDiskSpaceHardLimitReached)
 a| 
Incidente
 a| 
Quota utente o gruppo
 a| 
Critico



 a| 
Limite flessibile del numero di file della quota utente o gruppo violato (ocumEvtUserOrGroupQuotaFileCountSoftLimitBreached)
 a| 
Rischio
 a| 
Quota utente o gruppo
 a| 
Avvertimento



 a| 
Limite massimo di conteggio file quota utente o gruppo raggiunto (ocumEvtUserOrGroupQuotaFileCountHardLimitReached)
 a| 
Incidente
 a| 
Quota utente o gruppo
 a| 
Critico

|===