---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 'Dalla pagina Dettagli evento è possibile visualizzare i dettagli di un evento selezionato, come la gravità dell"evento, il livello di impatto, l"area di impatto e l"origine dell"evento.  È inoltre possibile visualizzare informazioni aggiuntive sulle possibili soluzioni per risolvere il problema.' 
---
= Pagina dei dettagli dell'evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina Dettagli evento è possibile visualizzare i dettagli di un evento selezionato, come la gravità dell'evento, il livello di impatto, l'area di impatto e l'origine dell'evento.  È inoltre possibile visualizzare informazioni aggiuntive sulle possibili soluzioni per risolvere il problema.

* *Nome dell'evento*
+
Il nome dell'evento e l'ora in cui è stato visualizzato l'ultima volta.

+
Per gli eventi non performanti, mentre l'evento si trova nello stato Nuovo o Riconosciuto, le ultime informazioni visualizzate non sono note e pertanto sono nascoste.

* *Descrizione dell'evento*
+
Una breve descrizione dell'evento.

+
In alcuni casi, nella descrizione dell'evento viene specificato il motivo per cui l'evento è stato attivato.

* *Componente in lizza*
+
Per gli eventi di prestazioni dinamiche, questa sezione visualizza le icone che rappresentano i componenti logici e fisici del cluster.  Se un componente è in conflitto, la sua icona viene cerchiata ed evidenziata in rosso.

+
Per una descrizione dei componenti visualizzati qui, vedere _Componenti del cluster e perché possono essere in competizione_.



Le sezioni Informazioni sull'evento, Diagnosi di sistema e Azioni suggerite sono descritte in altri argomenti.



== Pulsanti di comando

I pulsanti di comando consentono di eseguire le seguenti attività:

* *Icona Note*
+
Consente di aggiungere o aggiornare una nota sull'evento e di rivedere tutte le note lasciate da altri utenti.



*Menu Azioni*

* *Assegna a me*
+
Ti assegna l'evento.

* *Assegna ad altri*
+
Apre la finestra di dialogo Assegna proprietario, che consente di assegnare o riassegnare l'evento ad altri utenti.

+
Quando si assegna un evento a un utente, il nome dell'utente e l'ora in cui l'evento è stato assegnato vengono aggiunti all'elenco degli eventi selezionati.

+
È anche possibile annullare l'assegnazione degli eventi lasciando vuoto il campo della proprietà.

* *Riconoscere*
+
Riconosce gli eventi selezionati in modo da non continuare a ricevere notifiche di avviso ripetute.

+
Quando si riconosce un evento, il nome utente e l'ora in cui si è riconosciuto l'evento vengono aggiunti all'elenco degli eventi (Riconosciuto da) per gli eventi selezionati.  Quando riconosci un evento, ti assumi la responsabilità di gestirlo.

* *Segna come risolto*
+
Consente di modificare lo stato dell'evento in Risolto.

+
Quando risolvi un evento, il tuo nome utente e l'ora in cui hai risolto l'evento vengono aggiunti all'elenco degli eventi (Risolto da) per gli eventi selezionati.  Dopo aver adottato misure correttive per l'evento, è necessario contrassegnare l'evento come risolto.

* *Aggiungi avviso*
+
Visualizza la finestra di dialogo Aggiungi avviso, che consente di aggiungere un avviso per l'evento selezionato.


