---
permalink: events/reference_ems_events_that_are_added_automatically_to_um.html 
sidebar: sidebar 
keywords: ems events, added, automatically, unified manager 
summary: I seguenti eventi ONTAP EMS vengono aggiunti automaticamente a Unified Manager.  Questi eventi verranno generati quando attivati ​​su qualsiasi cluster monitorato da Unified Manager. 
---
= Eventi EMS aggiunti automaticamente a Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I seguenti eventi ONTAP EMS vengono aggiunti automaticamente a Unified Manager.  Questi eventi verranno generati quando attivati ​​su qualsiasi cluster monitorato da Unified Manager.

I seguenti eventi EMS sono disponibili durante il monitoraggio di cluster che eseguono il software ONTAP 9.5 o versioni successive:

|===
| Nome evento Unified Manager | Nome dell'evento EMS | Risorsa interessata | Gravità di Unified Manager 


 a| 
Accesso al livello cloud negato per la rilocazione aggregata
 a| 
arl.netra.ca.check.failed
 a| 
Aggregato
 a| 
Errore



 a| 
Accesso al livello cloud negato per la rilocazione dell'aggregato durante il failover dello storage
 a| 
gb.netra.ca.check.failed
 a| 
Aggregato
 a| 
Errore



 a| 
Risincronizzazione della replica mirror FabricPool completata
 a| 
wafl.ca.resync.complete
 a| 
Grappolo
 a| 
Errore



 a| 
Spazio FabricPool quasi pieno
 a| 
fabricpool.quasi.pieno
 a| 
Grappolo
 a| 
Errore



 a| 
Periodo di grazia NVMe-oF iniziato
 a| 
nvmf.graceperiod.start
 a| 
Grappolo
 a| 
Avvertimento



 a| 
Periodo di grazia NVMe-oF attivo
 a| 
nvmf.graceperiod.active
 a| 
Grappolo
 a| 
Avvertimento



 a| 
Periodo di grazia NVMe-oF scaduto
 a| 
nvmf.graceperiod.expired
 a| 
Grappolo
 a| 
Avvertimento



 a| 
LUN distrutto
 a| 
lun.distruggere
 a| 
LUN
 a| 
Informazioni



 a| 
Cloud AWS MetaDataConnFail
 a| 
cloud.aws.metadataConnFail
 a| 
Nodo
 a| 
Errore



 a| 
Cloud AWS IAMCredsExpired
 a| 
cloud.aws.iamCredsExpired
 a| 
Nodo
 a| 
Errore



 a| 
Cloud AWS IAMCredsInvalid
 a| 
cloud.aws.iamCredsInvalid
 a| 
Nodo
 a| 
Errore



 a| 
Cloud AWS IAMCredsNotFound
 a| 
cloud.aws.iamCredsNotFound
 a| 
Nodo
 a| 
Errore



 a| 
Cloud AWS IAMCredsNotInitialized
 a| 
cloud.aws.iamNotInitialized
 a| 
Nodo
 a| 
Informazioni



 a| 
Cloud AWS IAMRoleInvalid
 a| 
cloud.aws.iamRoleInvalid
 a| 
Nodo
 a| 
Errore



 a| 
Cloud AWS IAMRoleNotFound
 a| 
cloud.aws.iamRoleNotFound
 a| 
Nodo
 a| 
Errore



 a| 
Cloud Tier Host non risolvibile
 a| 
objstore.host.irrisolvibile
 a| 
Nodo
 a| 
Errore



 a| 
Interfaccia di rete intercluster Cloud Tier inattiva
 a| 
objstore.interclusterlifDown
 a| 
Nodo
 a| 
Errore



 a| 
Richiesta di mancata corrispondenza della firma del livello cloud
 a| 
osc.signatureMismatch
 a| 
Nodo
 a| 
Errore



 a| 
Uno dei pool NFSv4 esaurito
 a| 
Nblade.nfsV4PoolExhaust
 a| 
Nodo
 a| 
Critico



 a| 
Memoria monitor QoS al massimo
 a| 
qos.monitor.memory.maxed
 a| 
Nodo
 a| 
Errore



 a| 
Memoria del monitor QoS ridotta
 a| 
qos.monitor.memory.abbated
 a| 
Nodo
 a| 
Informazioni



 a| 
NVMeNS Destroy
 a| 
NVMeNS.distruggi
 a| 
Spazio dei nomi
 a| 
Informazioni



 a| 
NVMeNS Online
 a| 
NVMeNS.offline
 a| 
Spazio dei nomi
 a| 
Informazioni



 a| 
NVMeNS offline
 a| 
NVMeNS.online
 a| 
Spazio dei nomi
 a| 
Informazioni



 a| 
NVMeNS senza spazio
 a| 
NVMeNS.spazio esaurito
 a| 
Spazio dei nomi
 a| 
Avvertimento



 a| 
Replica sincrona fuori sincrono
 a| 
sms.status.out.of.sync
 a| 
Relazione SnapMirror
 a| 
Avvertimento



 a| 
Replica sincrona ripristinata
 a| 
sms.status.in.sync
 a| 
Relazione SnapMirror
 a| 
Informazioni



 a| 
Risincronizzazione automatica della replica sincrona non riuscita
 a| 
tentativo di risincronizzazione sms fallito
 a| 
Relazione SnapMirror
 a| 
Errore



 a| 
Molte connessioni CIFS
 a| 
Nblade.cifsManyAuths
 a| 
SVM
 a| 
Errore



 a| 
Numero massimo di connessioni CIFS superato
 a| 
Nblade.cifsMaxOpenSameFile
 a| 
SVM
 a| 
Errore



 a| 
Numero massimo di connessioni CIFS per utente superato
 a| 
Nblade.cifsMaxSessPerUsrConn
 a| 
SVM
 a| 
Errore



 a| 
Conflitto di nomi NetBIOS CIFS
 a| 
Nblade.cifsNbNameConflict
 a| 
SVM
 a| 
Errore



 a| 
Tentativi di connettere una condivisione CIFS inesistente
 a| 
Nblade.cifsNoPrivShare
 a| 
SVM
 a| 
Critico



 a| 
Operazione di copia shadow CIFS non riuscita
 a| 
cifs.shadowcopy.fallimento
 a| 
SVM
 a| 
Errore



 a| 
Virus trovato dal server AV
 a| 
Nblade.vscanVirusDetected
 a| 
SVM
 a| 
Errore



 a| 
Nessuna connessione al server AV per la scansione virus
 a| 
Nblade.vscanNoScannerConn
 a| 
SVM
 a| 
Critico



 a| 
Nessun server AV registrato
 a| 
Nblade.vscanNoRegdScanner
 a| 
SVM
 a| 
Errore



 a| 
Nessuna connessione al server AV reattivo
 a| 
Nblade.vscanConnInattivo
 a| 
SVM
 a| 
Informazioni



 a| 
Il server AV è troppo occupato per accettare una nuova richiesta di scansione
 a| 
Nblade.vscanConnBackPressure
 a| 
SVM
 a| 
Errore



 a| 
Tentativo di accesso non autorizzato al server AV
 a| 
Nblade.vscanBadUserPrivAccess
 a| 
SVM
 a| 
Errore



 a| 
I componenti FlexGroup hanno problemi di spazio
 a| 
i costituenti del gruppo flessibile hanno problemi di spazio
 a| 
Volume
 a| 
Errore



 a| 
Costituenti FlexGroup Spazio Stato Tutto OK
 a| 
flexgroup.constituents.space.status.all.ok
 a| 
Volume
 a| 
Informazioni



 a| 
I componenti FlexGroup hanno problemi con gli inode
 a| 
i costituenti del gruppo flessibile hanno problemi con gli inodi
 a| 
Volume
 a| 
Errore



 a| 
Costituenti FlexGroup Inode Stato Tutto OK
 a| 
flexgroup.constituents.inodes.status.all.ok
 a| 
Volume
 a| 
Informazioni



 a| 
Spazio logico del volume quasi pieno
 a| 
monitor.vol.nearFull.inc.sav
 a| 
Volume
 a| 
Avvertimento



 a| 
Volume Spazio Logico Pieno
 a| 
monitor.vol.full.inc.sav
 a| 
Volume
 a| 
Errore



 a| 
Volume Spazio Logico Normale
 a| 
monitor.vol.one.ok.inc.sav
 a| 
Volume
 a| 
Informazioni



 a| 
Errore di ridimensionamento automatico del volume WAFL
 a| 
wafl.vol.autoSize.fail
 a| 
Volume
 a| 
Errore



 a| 
WAFL Volume AutoSize Fatto
 a| 
wafl.vol.autoSize.done
 a| 
Volume
 a| 
Informazioni



 a| 
Timeout dell'operazione file WAFL READDIR
 a| 
wafl.readdir.expired
 a| 
Volume
 a| 
Errore

|===