---
permalink: events/task_assign_events_to_specific_users.html 
sidebar: sidebar 
keywords: assign, events, specific, users 
summary: 'È possibile assegnare eventi non assegnati a se stessi o ad altri utenti, compresi gli utenti remoti.  Se necessario, è possibile riassegnare gli eventi assegnati a un altro utente.  Ad esempio, quando si verificano problemi frequenti su un oggetto di archiviazione, è possibile assegnare gli eventi per questi problemi all"utente che gestisce tale oggetto.' 
---
= Assegna eventi a utenti specifici
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile assegnare eventi non assegnati a se stessi o ad altri utenti, compresi gli utenti remoti.  Se necessario, è possibile riassegnare gli eventi assegnati a un altro utente.  Ad esempio, quando si verificano problemi frequenti su un oggetto di archiviazione, è possibile assegnare gli eventi per questi problemi all'utente che gestisce tale oggetto.

.Prima di iniziare
* Il nome utente e l'ID e-mail devono essere configurati correttamente.
* È necessario disporre del ruolo di Operatore, Amministratore dell'applicazione o Amministratore dell'archiviazione.


.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione eventi*.
. Nella pagina dell'inventario *Gestione eventi*, seleziona uno o più eventi che desideri assegnare.
. Assegna l'evento scegliendo una delle seguenti opzioni:
+
|===
| Se vuoi assegnare l'evento a... | Allora fai così... 


 a| 
Te stesso
 a| 
Fare clic su *Assegna a* > *Io*.



 a| 
Un altro utente
 a| 
.. Fare clic su *Assegna a* > *Un altro utente*.
.. Nella finestra di dialogo Assegna proprietario, immettere il nome utente oppure selezionare un utente dall'elenco a discesa.
.. Fare clic su *Assegna*.
+
All'utente viene inviata una notifica via e-mail.

+
[NOTE]
====
Se non si immette un nome utente o non si seleziona un utente dall'elenco a discesa e si fa clic su *Assegna*, l'evento rimane non assegnato.

====


|===

