---
permalink: events/task_view_events_that_occurred_during_maintenance_window.html 
sidebar: sidebar 
keywords: view, events, occurred, maintenance, window 
summary: Se necessario, è possibile visualizzare gli eventi generati per tutti gli oggetti di archiviazione durante una finestra di manutenzione di Unified Manager.  La maggior parte degli eventi apparirà nello stato Obsoleto una volta completata la finestra di manutenzione e quando tutte le risorse di sistema saranno di nuovo operative. 
---
= Visualizza gli eventi che si sono verificati durante una finestra di manutenzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necessario, è possibile visualizzare gli eventi generati per tutti gli oggetti di archiviazione durante una finestra di manutenzione di Unified Manager.  La maggior parte degli eventi apparirà nello stato Obsoleto una volta completata la finestra di manutenzione e quando tutte le risorse di sistema saranno di nuovo operative.

.Prima di iniziare
È necessario che sia stata completata almeno una finestra di manutenzione prima che qualsiasi evento sia disponibile.

Per impostazione predefinita, gli eventi verificatisi durante una finestra di manutenzione non vengono visualizzati nella pagina dell'inventario di Gestione eventi.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Eventi*.
+
Per impostazione predefinita, tutti gli eventi attivi (nuovi e riconosciuti) vengono visualizzati nella pagina dell'inventario Gestione eventi.

. Dal riquadro Visualizza, seleziona l'opzione *Tutti gli eventi generati durante la manutenzione*.
+
Viene visualizzato l'elenco degli eventi attivati negli ultimi 7 giorni da tutte le sessioni della finestra di manutenzione e da tutti i cluster.

. Se sono state attivate più finestre di manutenzione per un singolo cluster, è possibile fare clic sull'icona del calendario *Ora di attivazione* e selezionare il periodo di tempo per gli eventi della finestra di manutenzione che si desidera visualizzare.

