---
permalink: events/task_upload_new_active_iq_rules_file.html 
sidebar: sidebar 
keywords: upload, new, active iq AIQ rules, rules file, CA secure rules, config advisor rules 
summary: Unified Manager verifica automaticamente la presenza di un nuovo file di regole Active IQ e scarica un nuovo file quando sono disponibili regole più recenti.  Tuttavia, nei siti senza accesso alla rete esterna, è necessario caricare manualmente il file delle regole. 
---
= Carica un nuovo file di regole Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager verifica automaticamente la presenza di nuovi file di eventi (regole) Active IQ e scarica un nuovo file quando sono presenti nuove regole.  Tuttavia, nei siti senza accesso alla rete esterna, è necessario caricare manualmente il file delle regole.


NOTE: Le regole Active IQ sono anche chiamate regole sicure Config Advisor (CA).

Quando si installa o si aggiorna Unified Manager a una versione specifica in un sito senza connettività di rete, le regole Active IQ in bundle sono automaticamente disponibili per il caricamento.  Tuttavia, si consiglia di scaricare un nuovo file di regole circa una volta al mese dal sito di supporto NetApp per assicurarsi che vengano generati eventi aggiornati e che i sistemi di storage continuino a funzionare in modo ottimale.

.Prima di iniziare
* È necessario abilitare la segnalazione degli eventi del portale Active IQ .  Questa funzione è abilitata per impostazione predefinita.  Per informazioni, vederelink:../config/concept_active_iq_platform_events.html["Abilitazione degli eventi del portale Active IQ"] .
* È necessario scaricare il file delle regole dal sito di supporto NetApp .
+
Il file delle regole si trova in: https://mysupport.netapp.com/api/content-service/staticcontents/content/public/tools/unifiedmanager/ca/secure_rules.zip[]



.Passi
. Su un computer con accesso alla rete, vai al sito di supporto NetApp e scarica le regole correnti `.zip` file.
+
Il pacchetto di regole in bundle include il repository delle regole, le origini dati e un articolo della Knowledge Base di NetApp .

+

NOTE: Nei sistemi Windows, in un sito senza connettività di rete, l'articolo della Knowledge Base di NetApp non è incluso per impostazione predefinita nel programma di installazione.  Puoi scaricare il file _secure_rules.zip_ dal sito di supporto e caricarlo per visualizzare l'articolo della Knowledge Base per tutte le regole.

. Trasferisci il file delle regole su un supporto che puoi portare nell'area protetta e poi copialo su un sistema nell'area protetta.
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Configurazione evento*.
. Nella pagina *Impostazione evento*, fare clic sul pulsante *Carica regole*.
. Nella finestra di dialogo *Regole di caricamento*, vai alle regole e selezionale `.zip` file scaricato e clicca su *Carica*.
+
Questo processo può richiedere alcuni minuti.



Il file delle regole viene decompresso sul server Unified Manager.  Dopo che i cluster gestiti generano un file AutoSupport dopo mezzanotte, Unified Manager verifica i cluster rispetto al file delle regole e genera nuovi eventi di rischio e incidente secondo necessità.

Per ulteriori informazioni, consultare questo articolo della Knowledge Base (KB): https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/How_to_update_AIQCASecure_rules_manually_in_Active_IQ_Unified_Manager["Come aggiornare manualmente le regole AIQCASecure in Active IQ Unified Manager"] .
