---
permalink: events/task_disable_alerts_for_resolved_and_obsolete_events.html 
sidebar: sidebar 
keywords: enable, disable, alerts, resolved, obsolete, events 
summary: 'Per tutti gli eventi configurati per l"invio di avvisi, viene inviato un messaggio di avviso quando tali eventi passano attraverso tutti gli stati disponibili: Nuovo, Riconosciuto, Risolto e Obsoleto.  Se non si desidera ricevere avvisi per gli eventi che passano agli stati Risolto e Obsoleto, è possibile configurare un"impostazione globale per sopprimere tali avvisi.' 
---
= Abilita e disabilita gli avvisi per gli eventi Risolti e Obsoleti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per tutti gli eventi configurati per l'invio di avvisi, viene inviato un messaggio di avviso quando tali eventi passano attraverso tutti gli stati disponibili: Nuovo, Riconosciuto, Risolto e Obsoleto.  Se non si desidera ricevere avvisi per gli eventi che passano agli stati Risolto e Obsoleto, è possibile configurare un'impostazione globale per sopprimere tali avvisi.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Per impostazione predefinita, gli avvisi non vengono inviati per gli eventi quando passano agli stati Risolto e Obsoleto.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Configurazione avvisi*.
. Nella pagina *Impostazione avvisi*, eseguire una delle seguenti azioni utilizzando il controllo cursore accanto alla voce *Avvisi per eventi risolti e obsoleti*:
+
|===
| A... | Fai questo... 


 a| 
Interrompere l'invio di avvisi quando gli eventi vengono risolti o diventano obsoleti
 a| 
Spostare il controllo del cursore verso sinistra



 a| 
Inizia a inviare avvisi quando gli eventi vengono risolti o diventano obsoleti
 a| 
Spostare il controllo del cursore verso destra

|===

