---
permalink: events/task_schedule_maintenance_window_to_disable_cluster_notifications.html 
sidebar: sidebar 
keywords: schedule, maintenance, window, disable, cluster, event, notifications 
summary: Se è previsto un periodo di inattività per un cluster, ad esempio per aggiornare il cluster o spostare uno dei nodi, è possibile sopprimere gli eventi e gli avvisi che normalmente verrebbero generati durante tale intervallo di tempo pianificando una finestra di manutenzione di Unified Manager. 
---
= Pianifica una finestra di manutenzione per disabilitare le notifiche degli eventi del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è previsto un periodo di inattività per un cluster, ad esempio per aggiornare il cluster o spostare uno dei nodi, è possibile sopprimere gli eventi e gli avvisi che normalmente verrebbero generati durante tale intervallo di tempo pianificando una finestra di manutenzione di Unified Manager.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Durante una finestra di manutenzione, gli eventi relativi a tutti gli oggetti su quel cluster vengono comunque generati, ma non vengono visualizzati nella pagina degli eventi e non vengono inviati avvisi o altri tipi di notifiche per questi eventi.

L'orario immesso per la finestra di manutenzione si basa sull'orario del server Unified Manager.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Gestione archiviazione* > *Configurazione cluster*.
. Nella colonna *Modalità di manutenzione* del cluster, seleziona il pulsante del cursore e spostalo verso destra.
+
Viene visualizzata la finestra del calendario.

. Selezionare la data e l'ora di inizio e fine della finestra di manutenzione e fare clic su *Applica*.
+
Accanto al pulsante del cursore viene visualizzato il messaggio "Programmato".



Una volta raggiunta l'ora di inizio, il cluster entra in modalità di manutenzione e viene generato un evento "Finestra di manutenzione oggetto avviata".
