---
permalink: data-protection/concept_manage_and_monitor_protection_relationships.html 
sidebar: sidebar 
keywords: manage, monitor, protection, relationships 
summary: Active IQ Unified Manager consente di creare relazioni di protezione, di monitorare e risolvere i problemi delle relazioni SnapMirror e SnapVault sui cluster gestiti e di ripristinare i dati quando vengono sovrascritti o persi. 
---
= Gestire e monitorare le relazioni di protezione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager consente di creare relazioni di protezione, di monitorare e risolvere i problemi delle relazioni SnapMirror e SnapVault sui cluster gestiti e di ripristinare i dati quando vengono sovrascritti o persi.

Per le operazioni SnapMirror esistono due tipi di replica:

* Asincrono
+
La replicazione dal volume primario a quello secondario è determinata da un programma.

* Sincrono
+
La replicazione viene eseguita simultaneamente sul volume primario e secondario.



È possibile eseguire fino a 10 attività di protezione contemporaneamente senza alcun impatto sulle prestazioni.  Potresti riscontrare un impatto sulle prestazioni quando esegui contemporaneamente da 11 a 30 processi.  Non è consigliabile eseguire più di 30 processi contemporaneamente.
