---
permalink: data-protection/concept_storage_virtual_machine_and_resource_pool_requirements.html 
sidebar: sidebar 
keywords: svm, resource pool requirements, support, storage services 
summary: 'È possibile garantire meglio la conformità nelle applicazioni partner se si osservano alcuni requisiti di associazione SVM e pool di risorse specifici dei servizi di archiviazione: ad esempio, quando si associa SVM e si creano pool di risorse in Unified Manager per supportare una topologia di protezione in un servizio di archiviazione fornito da un"applicazione partner.' 
---
= Requisiti SVM e pool di risorse per supportare i servizi di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile garantire meglio la conformità nelle applicazioni partner se si osservano alcuni requisiti di associazione SVM e pool di risorse specifici dei servizi di archiviazione: ad esempio, quando si associa SVM e si creano pool di risorse in Unified Manager per supportare una topologia di protezione in un servizio di archiviazione fornito da un'applicazione partner.

Alcune applicazioni collaborano con il server Unified Manager per fornire servizi che configurano ed eseguono automaticamente la protezione di backup SnapMirror o SnapVault tra volumi di origine e volumi di protezione in posizioni secondarie o terziarie.  Per supportare questi servizi di archiviazione della protezione, è necessario utilizzare Unified Manager per configurare le associazioni SVM e i pool di risorse necessari.

Per supportare la protezione single-hop o a cascata del servizio di archiviazione, inclusa la replica da un volume di origine SnapMirror o primario SnapVault a SnapMirror di destinazione o a volumi di backup SnapVault che risiedono in posizioni secondarie o terziarie, osservare i seguenti requisiti:

* Le associazioni SVM devono essere configurate tra l'SVM contenente il volume sorgente SnapMirror o il volume primario SnapVault e qualsiasi SVM su cui risiede un volume secondario o un volume terziario.
+
** Ad esempio, per supportare una topologia di protezione in cui il volume di origine Vol_A risiede su SVM_1, il volume di destinazione secondario SnapMirror Vol_B risiede su SVM_2 e il volume di backup terziario SnapVault Vol_C risiede su SVM_3, è necessario utilizzare l'interfaccia utente Web di Unified Manager per configurare un'associazione SnapMirror tra SVM_1 e SVM_2 e un'associazione di backup SnapVault tra SVM_1 e SVM_3.
+
In questo esempio, qualsiasi associazione SnapMirror o associazione di backup SnapVault tra SVM_2 e SVM_3 non è necessaria e non viene utilizzata.

** Per supportare una topologia di protezione in cui sia il volume di origine Vol_A sia il volume di destinazione SnapMirror Vol_B risiedono su SVM_1, è necessario configurare un'associazione SnapMirror tra SVM_1 e SVM_1.


* I pool di risorse devono includere risorse aggregate del cluster disponibili per le SVM associate.
+
È possibile configurare i pool di risorse tramite l'interfaccia utente Web di Unified Manager e quindi assegnare tramite l'applicazione partner i nodi di destinazione secondaria e terziaria del servizio di archiviazione.


