---
permalink: data-protection/concept_what_resource_pools_are.html 
sidebar: sidebar 
keywords: resource pools 
summary: I pool di risorse sono gruppi di aggregati creati da un amministratore di storage tramite Unified Manager per fornire il provisioning alle applicazioni partner per la gestione del backup. 
---
= Quali sono i pool di risorse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I pool di risorse sono gruppi di aggregati creati da un amministratore di storage tramite Unified Manager per fornire il provisioning alle applicazioni partner per la gestione del backup.

È possibile raggruppare le risorse in base ad attributi quali prestazioni, costi, ubicazione fisica o disponibilità.  Raggruppando le risorse correlate in un pool, è possibile trattare il pool come un'unica unità per il monitoraggio e il provisioning.  Ciò semplifica la gestione di queste risorse e consente un utilizzo più flessibile ed efficiente dello storage.

Durante il provisioning dell'archiviazione secondaria, Unified Manager determina l'aggregato più adatto nel pool di risorse per la protezione utilizzando i seguenti criteri:

* L'aggregato è un aggregato di dati (non un aggregato radice) ed è ONLINE.
* L'aggregato si trova su un nodo del cluster di destinazione la cui versione ONTAP è uguale o superiore alla versione principale del cluster di origine.
* L'aggregato ha lo spazio disponibile più grande tra tutti gli aggregati nel pool di risorse.
* Dopo aver effettuato il provisioning del volume di destinazione, lo spazio aggregato rientra nella soglia quasi piena e quasi sovraimpegnata definita per l'aggregato (soglia globale o locale, a seconda dei casi).
* Il numero di volumi FlexVol sul nodo di destinazione non deve superare il limite della piattaforma.

