---
permalink: data-protection/reference_relationship_last_1_month_transfer_rate_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer rate, view 
summary: 'La vista Relazione: Velocità di trasferimento dell"ultimo mese consente di analizzare la quantità di volume di dati trasferito quotidianamente per i volumi in relazioni asincrone.  Questa pagina fornisce anche dettagli sui trasferimenti giornalieri e sul tempo necessario per completare l"operazione di trasferimento per volumi e VM di archiviazione.' 
---
= Relazione: Visualizzazione del tasso di trasferimento dell'ultimo mese
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Relazione: Velocità di trasferimento dell'ultimo mese consente di analizzare la quantità di volume di dati trasferito quotidianamente per i volumi in relazioni asincrone.  Questa pagina fornisce anche dettagli sui trasferimenti giornalieri e sul tempo necessario per completare l'operazione di trasferimento per volumi e VM di archiviazione.

I controlli nella parte superiore della pagina consentono di eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare colonne nella pagina ed esportare i dati nella pagina in un file .csv, .pdf o .xlsx.  Dopo aver personalizzato la pagina, puoi salvare i risultati come visualizzazione personalizzata e quindi programmare la generazione e l'invio periodico tramite e-mail di un report di questi dati.  Ad esempio, se si desidera visualizzare le relazioni tra volumi, è possibile accedere al menu *Archiviazione* > *Volumi* > *Relazione: Velocità di trasferimento ultimo mese* oppure accedere al menu *Protezione* > *Relazioni* > *Relazioni: Velocità di trasferimento ultimo mese* e utilizzare il *Filtro* per visualizzare solo i dati dei volumi.

* *Dimensione totale del trasferimento*
+
Visualizza la dimensione totale del volume trasferito in gigabyte.

* *Giorno*
+
Visualizza il giorno in cui è stato avviato il trasferimento del volume.

* *Ora di fine*
+
Visualizza l'ora di fine del trasferimento del volume con la data.



*Informazioni correlate*

* Per informazioni sulla visualizzazione *Relazione: MetroCluster*, vederelink:../storage-mgmt/task_monitor_metrocluster_configurations.html["Monitoraggio delle configurazioni MetroCluster"] .
* Per informazioni sulla visualizzazione *Relazione: Stato del trasferimento dell'ultimo mese*, vederelink:../data-protection/reference_relationship_last_1_month_transfer_status_view.html["Relazione: Visualizzazione dello stato del trasferimento dell'ultimo mese"] .
* Per informazioni sulla visualizzazione *Relazione: Tutte le relazioni*, vederelink:../data-protection/reference_relationship_last_1_month_transfer_rate_view.html["Relazione: Visualizzazione del tasso di trasferimento dell'ultimo mese"]

