---
permalink: data-protection/reference_create_resource_pool_dialog_box.html 
sidebar: sidebar 
keywords: create, resource pool, dialog box 
summary: È possibile utilizzare la finestra di dialogo Crea pool di risorse per assegnare un nome e descrivere un nuovo pool di risorse e per aggiungere ed eliminare aggregati da tale pool di risorse. 
---
= Finestra di dialogo Crea pool di risorse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di dialogo Crea pool di risorse per assegnare un nome e descrivere un nuovo pool di risorse e per aggiungere ed eliminare aggregati da tale pool di risorse.



== Nome del pool di risorse

Le caselle di testo consentono di aggiungere le seguenti informazioni per creare un pool di risorse:

Consente di specificare un nome per il pool di risorse.



== Descrizione

Consente di descrivere un pool di risorse.



== Membri

Visualizza i membri del pool di risorse.  Puoi anche aggiungere ed eliminare membri.



== Pulsanti di comando

I pulsanti di comando consentono di eseguire le seguenti attività:

* *Aggiungere*
+
Apre la finestra di dialogo Aggregati in modo da poter aggiungere aggregati da un cluster specifico al pool di risorse.  È possibile aggiungere aggregati da cluster diversi, ma gli stessi aggregati non possono essere aggiunti a più di un pool di risorse.

* *Rimuovere*
+
Consente di rimuovere gli aggregati selezionati dal pool di risorse.

* *Creare*
+
Crea il pool di risorse.  Questo pulsante non è abilitato finché non vengono inserite informazioni nei campi Nome pool di risorse o Descrizione.

* *Cancellare*
+
Annulla le modifiche e chiude la finestra di dialogo Crea pool di risorse.


