---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: La pagina Associazione VM di archiviazione consente di visualizzare le associazioni VM di archiviazione esistenti tra VM di archiviazione di origine e di destinazione. 
---
= Informazioni sulle associazioni delle VM di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le associazioni di macchine virtuali di archiviazione (VM di archiviazione) sono mappature da una VM di archiviazione di origine a una VM di archiviazione di destinazione, utilizzate dalle applicazioni partner per la selezione delle risorse e il provisioning dei volumi secondari.

Le associazioni vengono create tra una VM di archiviazione di origine e una VM di archiviazione di destinazione, indipendentemente dal fatto che la VM di archiviazione di destinazione sia una destinazione secondaria o terziaria.  Non è possibile utilizzare una VM di archiviazione di destinazione secondaria come origine per creare un'associazione con una VM di archiviazione di destinazione terziaria.

In qualità di amministratore dell'applicazione o amministratore dell'archiviazione, puoi visualizzare le associazioni delle VM di archiviazione nel tuo ambiente nella pagina *Protezione* > *Associazioni VM di archiviazione*.

È possibile associare le SVM in tre modi:

* *Associa qualsiasi VM di archiviazione*: puoi creare un'associazione tra qualsiasi VM di archiviazione di origine primaria e una o più SVM di destinazione.  Ciò significa che tutte le SVM esistenti che attualmente necessitano di protezione, nonché tutte le SVM che verranno create in futuro, sono associate alle SVM di destinazione specificate.  Ad esempio, potresti voler eseguire il backup di applicazioni provenienti da diverse origini in posizioni diverse su una o più SVM di destinazione in un'unica posizione.
* *Associa una VM di archiviazione specifica*: puoi creare un'associazione tra una VM di archiviazione di origine specifica e una o più SVM di destinazione specifiche.  Ad esempio, se si forniscono servizi di archiviazione a molti client i cui dati devono essere separati l'uno dall'altro, è possibile scegliere questa opzione per associare una specifica VM di archiviazione di origine a una specifica VM di archiviazione di destinazione assegnata solo a quel client.
* *Associa a una VM di archiviazione esterna*: puoi creare un'associazione tra una VM di archiviazione di origine e un volume flessibile esterno di una VM di archiviazione di destinazione.




== Creare associazioni di VM di archiviazione

La procedura guidata Crea associazioni di macchine virtuali di archiviazione consente alle applicazioni di protezione dei partner di associare una VM di archiviazione di origine a una VM di archiviazione di destinazione per l'utilizzo con relazioni SnapMirror e SnapVault .  Le applicazioni partner utilizzano queste associazioni al momento del provisioning iniziale dei volumi di destinazione per determinare quali risorse selezionare.dd

.Prima di iniziare
* La VM di archiviazione che stai associando deve già esistere.
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.


Per qualsiasi VM di archiviazione di origine e tipo di relazione, è possibile scegliere una sola VM di archiviazione di destinazione su ciascun cluster di destinazione.

La modifica delle associazioni tramite le funzioni di eliminazione e creazione influisce solo sulle future operazioni di provisioning.  Non sposta i volumi di destinazione esistenti.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Protezione* > *Associazioni VM di archiviazione*.
. Nella pagina *Associazioni VM di archiviazione*, fare clic su *Crea*.
+
Viene avviata la procedura guidata *Crea associazioni macchine virtuali di archiviazione*.

. Seleziona una delle seguenti fonti:
+
** *Qualunque*
+
Selezionare questa opzione quando si desidera creare un'associazione tra una qualsiasi VM di archiviazione primaria di origine e una o più VM di archiviazione di destinazione.  Ciò significa che tutte le VM di archiviazione esistenti che attualmente necessitano di protezione, nonché tutte le VM di archiviazione che verranno create in futuro, sono associate alla VM di archiviazione di destinazione specificata.  Ad esempio, potresti voler eseguire il backup di applicazioni provenienti da diverse origini in posizioni diverse su una o più VM di archiviazione di destinazione in un'unica posizione.

** *Separare*
+
Selezionare questa opzione quando si desidera selezionare una specifica VM di archiviazione di origine associata a una o più VM di archiviazione di destinazione.  Ad esempio, se si forniscono servizi di archiviazione a molti client i cui dati devono essere separati l'uno dall'altro, scegliere questa opzione per associare una specifica origine VM di archiviazione a una specifica destinazione VM di archiviazione assegnata solo a quel client.

** *Nessuno (esterno)*
+
Selezionare questa opzione quando si desidera creare un'associazione tra una VM di archiviazione di origine e un volume flessibile esterno di una VM di archiviazione di destinazione.



. Seleziona uno o entrambi i tipi di relazione di protezione che desideri creare:
+
** * SnapMirror*
** * SnapVault*


. Fare clic su *Avanti*.
. Selezionare una o più destinazioni di protezione delle VM di archiviazione.
. Fare clic su *Fine*.




== Elimina le associazioni delle VM di archiviazione

È possibile eliminare le associazioni delle VM di archiviazione per le applicazioni partner per rimuovere la relazione di provisioning secondaria tra la VM di archiviazione di origine e quella di destinazione; ad esempio, è possibile eseguire questa operazione quando la VM di archiviazione di destinazione è piena e si desidera creare nuove associazioni di protezione per la VM di archiviazione.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Il pulsante *Elimina* è disabilitato finché non viene selezionata almeno un'associazione VM di archiviazione.  La modifica delle associazioni tramite le funzioni di eliminazione e creazione influisce solo sulle future operazioni di provisioning; non sposta i volumi di destinazione esistenti.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Protezione* > *Associazioni VM di archiviazione*.
. Selezionare almeno un'associazione VM di archiviazione.
+
Il pulsante *Elimina* è abilitato.

. Fai clic su *Elimina.*
+
Viene visualizzata una finestra di dialogo di avviso.

. Fare clic su *Sì* per continuare.
+
L'associazione VM di archiviazione selezionata viene rimossa dall'elenco.


