---
permalink: data-protection/reference_create_snapvault_policy_dialog_box.html 
sidebar: sidebar 
keywords: create, snapvault, policy, dialog box 
summary: 'La finestra di dialogo Crea criterio SnapVault consente di creare un criterio per impostare la priorità per i trasferimenti SnapVault .  Si utilizzano policy per massimizzare l"efficienza dei trasferimenti dal volume primario a quello secondario.' 
---
= Finestra di dialogo Crea criterio SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Crea criterio SnapVault consente di creare un criterio per impostare la priorità per i trasferimenti SnapVault .  Si utilizzano policy per massimizzare l'efficienza dei trasferimenti dal volume primario a quello secondario.

* *Cluster di destinazione*
+
Il nome del cluster selezionato nella scheda SnapVault della finestra di dialogo Configura protezione.

* *Destinazione SVM*
+
Il nome dell'SVM selezionato nella scheda SnapVault della finestra di dialogo Configura protezione.

* *Nome della polizza*
+
Il nome che fornisci per la nuova polizza.  I nomi delle policy possono essere composti dai caratteri dalla A alla Z, dalla a alla z, dallo 0 al 9, dal punto (.), dal trattino (-) e dal carattere di sottolineatura (_).

* *Priorità di trasferimento*
+
La priorità con cui viene eseguito il trasferimento.  È possibile selezionare Normale o Basso.  Le relazioni di trasferimento con policy che specificano una priorità di trasferimento normale vengono eseguite prima di quelle con policy che specificano una priorità di trasferimento bassa.  L'impostazione predefinita è Normale.

* *Commento*
+
Un campo facoltativo in cui puoi aggiungere un commento di massimo 255 caratteri sulla policy SnapVault .

* *Ignora tempo di accesso*
+
Specifica se i trasferimenti incrementali vengono ignorati per i file di cui è stato modificato solo l'orario di accesso.

* *Etichetta di replicazione*
+
Elenca in una tabella le regole associate alle copie Snapshot selezionate da ONTAP che hanno un'etichetta di replica specifica in una policy.  Sono inoltre disponibili le seguenti informazioni e azioni:

+
** Pulsanti di comando
+
I pulsanti di comando consentono di eseguire le seguenti azioni:

+
*** Aggiungere
+
Consente di creare un'etichetta di copia Snapshot e un conteggio di conservazione.

*** Modifica conteggio conservazione
+
Consente di modificare il conteggio di conservazione per un'etichetta di copia Snapshot esistente.  Il conteggio della conservazione deve essere un numero compreso tra 1 e 251.  La somma di tutti i conteggi di conservazione per tutte le regole non può superare 251.

*** Eliminare
+
Consente di eliminare un'etichetta di copia Snapshot esistente.



** Etichetta copia snapshot
+
Visualizza l'etichetta della copia Snapshot.  Se si seleziona uno o più volumi con la stessa policy di copia Snapshot locale, viene visualizzata una voce per ciascuna etichetta nella policy.  Se selezioni più volumi che hanno due o più criteri di copia Snapshot locali, la tabella visualizza tutte le etichette di tutti i criteri

** Programma
+
Visualizza la pianificazione associata a ciascuna etichetta di copia Snapshot.  Se a un'etichetta sono associate più pianificazioni, le pianificazioni per quell'etichetta vengono visualizzate in un elenco separato da virgole.  Se si selezionano più volumi con la stessa etichetta ma con pianificazioni diverse, nella pianificazione viene visualizzato "`Varie`" per indicare che ai volumi selezionati è associata più di una pianificazione.

** Conteggio della conservazione della destinazione
+
Visualizza il numero di copie Snapshot con l'etichetta specificata conservate sullo SnapVault secondario.  I conteggi di conservazione per le etichette con più pianificazioni visualizzano la somma dei conteggi di conservazione di ciascuna coppia etichetta-pianificazione.  Se si selezionano più volumi con due o più criteri di copia Snapshot locali, il conteggio della conservazione è vuoto.




