---
permalink: data-protection/reference_edit_resource_pool_dialog_box.html 
sidebar: sidebar 
keywords: edit, resource pool, dialog box 
summary: È possibile utilizzare la finestra di dialogo Modifica pool di risorse per modificare il nome e la descrizione di un pool di risorse esistente.  Ad esempio, se il nome e la descrizione originali sono imprecisi o errati, puoi modificarli per renderli più precisi. 
---
= Finestra di dialogo Modifica pool di risorse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di dialogo Modifica pool di risorse per modificare il nome e la descrizione di un pool di risorse esistente.  Ad esempio, se il nome e la descrizione originali sono imprecisi o errati, puoi modificarli per renderli più precisi.



== Caselle di testo

Le caselle di testo consentono di modificare le seguenti informazioni per il pool di risorse selezionato:

* *Nome del pool di risorse*
+
Consente di immettere un nuovo nome.

* *Descrizione*
+
Consente di immettere una nuova descrizione.





== Pulsanti di comando

I pulsanti di comando consentono di eseguire le seguenti attività:

* *Salva*
+
Salva le modifiche apportate al nome e alla descrizione del pool di risorse.

* *Cancellare*
+
Annulla le modifiche e chiude la finestra di dialogo Modifica pool di risorse.


