---
permalink: data-protection/task_view_volume_protection_relationships.html 
sidebar: sidebar 
keywords: view, volume, protection relationships 
summary: 'Dalla vista Relazione: Tutte le relazioni e dalla pagina Relazioni volume, è possibile visualizzare lo stato delle relazioni SnapMirror e SnapVault dei volumi esistenti.  È inoltre possibile esaminare i dettagli sulle relazioni di protezione, tra cui lo stato di trasferimento e ritardo, i dettagli di origine e destinazione, le informazioni sulla pianificazione e sulla policy e così via.' 
---
= Visualizza le relazioni di protezione del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla vista Relazione: Tutte le relazioni e dalla pagina Relazioni volume, è possibile visualizzare lo stato delle relazioni SnapMirror e SnapVault dei volumi esistenti.  È inoltre possibile esaminare i dettagli sulle relazioni di protezione, tra cui lo stato di trasferimento e ritardo, i dettagli di origine e destinazione, le informazioni sulla pianificazione e sulla policy e così via.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

Da questa pagina puoi anche avviare comandi di relazione.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Archiviazione* > *Volumi*.
. Dal menu Visualizza, seleziona *Relazione* > *Tutte le relazioni*.
+
Viene visualizzata la vista Relazione: Tutte le relazioni.

. Per visualizzare i dettagli sulla protezione del volume, scegliere uno dei seguenti metodi:
+
** Per visualizzare le informazioni correnti su tutte le relazioni di volume, rimanere sulla pagina predefinita *Tutte le relazioni*.
** Per visualizzare informazioni dettagliate sulle tendenze del trasferimento del volume in un determinato periodo di tempo, nel menu Visualizza, selezionare Relazione: visualizzazione Stato trasferimento ultimo mese.
** Per visualizzare informazioni dettagliate sull'attività di trasferimento del volume su base giornaliera, nel menu Visualizza, selezionare Relazione: visualizzazione Velocità di trasferimento ultimo mese.


+
[NOTE]
====
Le viste di trasferimento del volume mostrano solo le informazioni sui volumi nelle relazioni asincrone; i volumi nelle relazioni sincrone non vengono mostrati.

====

