---
permalink: data-protection/task_create_cascade_or_fanout_relationships_to_extend_protection.html 
sidebar: sidebar 
keywords: create, cascade fanout, relationships, extend protection, existing protection relationship 
summary: È possibile estendere la protezione da una relazione esistente creando un fanout dal volume di origine o una cascata dal volume di destinazione di una relazione esistente.  Questa operazione può essere eseguita quando è necessario copiare dati da un sito a più siti o per fornire una protezione aggiuntiva creando più backup. 
---
= Creare relazioni a cascata o a fanout per estendere la protezione da una relazione di protezione esistente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile estendere la protezione da una relazione esistente creando un fanout dal volume di origine o una cascata dal volume di destinazione di una relazione esistente.  Questa operazione può essere eseguita quando è necessario copiare dati da un sito a più siti o per fornire una protezione aggiuntiva creando più backup.

È possibile estendere la protezione ai volumi utilizzando un gruppo di coerenza, ovvero un contenitore che contiene più volumi, in modo da poterli gestire tutti come un'unica entità.  È possibile visualizzare il gruppo di coerenza di sincronizzazione attiva SnapMirror e la relazione del gruppo di coerenza sincrona nella pagina Relazioni di Unified Manager.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.


.Passi
. Fare clic su *Protezione* > *Relazioni*.  In alternativa, è possibile visualizzare le relazioni dalla pagina Dettagli volume.
. Dalla pagina *Relazioni volume*, seleziona la relazione SnapMirror da cui desideri estendere la protezione.
. Sulla barra delle azioni, fare clic su *Estendi protezione*.
. Nel menu, seleziona *Da origine* o *Da destinazione*, a seconda che tu stia creando una relazione fanout dall'origine o una relazione a cascata dalla destinazione.
. Selezionare *Con SnapMirror* o *Con SnapVault* a seconda del tipo di relazione di protezione che si sta creando.
+
Viene visualizzata la finestra di dialogo *Configura protezione*.

+
[NOTE]
====
Ciò può essere ottenuto dalla pagina Relazione unificata/Relazione volume e Dettagli volume/Salute.

====
. Completare le informazioni come indicato nella finestra di dialogo *Configura protezione*.

