---
permalink: data-protection/task_abort_an_active_data_protection_transfer.html 
sidebar: sidebar 
keywords: abort, active data protection, transfer, volume relationships page, SnapMirror active sync 
summary: 'È possibile annullare un trasferimento di protezione dati attivo quando si desidera interrompere una replica SnapMirror in corso.  È anche possibile cancellare il checkpoint di riavvio per i trasferimenti successivi al trasferimento di base.  È possibile annullare un trasferimento quando entra in conflitto con un"altra operazione, ad esempio uno spostamento di volume.' 
---
= Annulla un trasferimento di protezione dati attivo dalla pagina Relazioni volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile annullare un trasferimento di protezione dati attivo quando si desidera interrompere una replica SnapMirror in corso.  È anche possibile cancellare il checkpoint di riavvio per i trasferimenti successivi al trasferimento di base.  È possibile annullare un trasferimento quando entra in conflitto con un'altra operazione, ad esempio uno spostamento di volume.


NOTE: Non è possibile interrompere le relazioni tra volumi protette dal Gruppo di coerenza.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.


L'azione di interruzione non viene visualizzata nei seguenti casi:

* Se le impostazioni RBAC non consentono questa azione: ad esempio, se si dispone solo dei privilegi di operatore
* Quando l'ID del volume è sconosciuto: ad esempio, quando si ha una relazione intercluster e il cluster di destinazione non è ancora stato scoperto


Non è possibile cancellare il checkpoint di riavvio per un trasferimento di base.

.Passi
. Per annullare i trasferimenti per una o più relazioni di protezione, dalla pagina *Relazioni volume*, selezionare uno o più volumi e, sulla barra degli strumenti, fare clic su *Annulla*.
+
Viene visualizzata la finestra di dialogo Interrompi trasferimento.

. Se si desidera cancellare il checkpoint di riavvio per un trasferimento che non è un trasferimento di base, selezionare *Cancella checkpoint*.
. Fare clic su *Continua*.
+
La finestra di dialogo Interrompi trasferimento viene chiusa e lo stato del processo di interruzione viene visualizzato nella parte superiore della pagina Relazioni volume, insieme a un collegamento ai dettagli del processo.

. *Facoltativo:* fare clic sul collegamento *Visualizza dettagli* per andare alla pagina dei dettagli del *Lavoro* per ulteriori dettagli e per visualizzare l'avanzamento del lavoro.

