---
permalink: data-protection/task_create_snapmirror_policy_to_maximize_transfer_efficiency.html 
sidebar: sidebar 
keywords: create, snapmirror, policy, maximize, transfer, efficiency 
summary: 'È possibile creare un criterio SnapMirror per specificare la priorità di trasferimento SnapMirror per le relazioni di protezione.  I criteri SnapMirror consentono di massimizzare l"efficienza del trasferimento dall"origine alla destinazione assegnando priorità in modo che i trasferimenti con priorità inferiore vengano pianificati per essere eseguiti dopo i trasferimenti con priorità normale.' 
---
= Creare una policy SnapMirror per massimizzare l'efficienza del trasferimento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un criterio SnapMirror per specificare la priorità di trasferimento SnapMirror per le relazioni di protezione.  I criteri SnapMirror consentono di massimizzare l'efficienza del trasferimento dall'origine alla destinazione assegnando priorità in modo che i trasferimenti con priorità inferiore vengano pianificati per essere eseguiti dopo i trasferimenti con priorità normale.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.
* Questa attività presuppone che sia già stata completata l'area Informazioni sulla destinazione nella finestra di dialogo Configura protezione.


.Passi
. Dalla scheda * SnapMirror* della finestra di dialogo *Configura protezione*, fare clic sul collegamento *Crea criterio* nell'area *Impostazioni relazione*.
+
Viene visualizzata la finestra di dialogo Crea criterio SnapMirror .

. Nel campo *Nome policy*, digitare il nome che si desidera assegnare alla policy.
. Nel campo *Priorità di trasferimento*, seleziona la priorità di trasferimento che desideri assegnare alla policy.
. Nel campo *Commento*, inserisci un commento facoltativo per la policy.
. Fare clic su *Crea*.
+
La nuova policy viene visualizzata nell'elenco a discesa Policy SnapMirror .


