---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: È possibile utilizzare la pagina Dettagli volume/integrità per creare una relazione SnapMirror in modo che la replica dei dati sia abilitata per scopi di protezione.  La replica SnapMirror consente di ripristinare i dati dal volume di destinazione in caso di perdita di dati sul volume di origine. 
---
= Crea una relazione di protezione SnapMirror dalla pagina dei dettagli Volume/Stato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la pagina Dettagli volume/integrità per creare una relazione SnapMirror in modo che la replica dei dati sia abilitata per scopi di protezione.  La replica SnapMirror consente di ripristinare i dati dal volume di destinazione in caso di perdita di dati sul volume di origine.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.


Il menu *Proteggi* non viene visualizzato nei seguenti casi:

* Se le impostazioni RBAC non consentono questa azione: ad esempio, se si dispone solo dei privilegi di operatore
* Quando l'ID del volume è sconosciuto: ad esempio, quando si ha una relazione intercluster e il cluster di destinazione non è ancora stato scoperto


È possibile eseguire fino a 10 attività di protezione contemporaneamente senza alcun impatto sulle prestazioni.  Potresti riscontrare un impatto sulle prestazioni quando esegui contemporaneamente da 11 a 30 processi.  Non è consigliabile eseguire più di 30 processi contemporaneamente.

.Passi
. Nella scheda *Protezione* della pagina dei dettagli *Volume/Integrità*, fare clic con il pulsante destro del mouse nella vista topologia sul nome del volume che si desidera proteggere.
. Selezionare *Proteggi* > * SnapMirror* dal menu.
+
Viene visualizzata la finestra di dialogo Configura protezione.

. Fare clic su * SnapMirror* per visualizzare la scheda * SnapMirror* e configurare le informazioni sulla destinazione.
. Fare clic su *Avanzate* per impostare la garanzia di spazio, se necessario, quindi fare clic su *Applica*.
. Completare l'area *Informazioni sulla destinazione* e l'area *Impostazioni relazione* nella finestra di dialogo *Configura protezione*.
. Fare clic su *Applica*.
+
Verrai reindirizzato alla pagina dei dettagli Volume/Salute.

. Fare clic sul collegamento al processo di configurazione della protezione nella parte superiore della pagina dei dettagli *Volume / Integrità*.
+
Le attività e i dettagli del lavoro vengono visualizzati nella pagina Dettagli lavoro.

. Nella pagina dei dettagli *Job*, fare clic su *Aggiorna* per aggiornare l'elenco delle attività e i dettagli delle attività associati al job di configurazione della protezione e per determinare quando il job è completato.
. Una volta completate le attività lavorative, fare clic su *Indietro* nel browser per tornare alla pagina dei dettagli *Volume / Salute*.
+
La nuova relazione viene visualizzata nella vista topologica della pagina Dettagli volume/stato.



A seconda della SVM di destinazione specificata durante la configurazione o delle opzioni abilitate nelle impostazioni avanzate, la relazione SnapMirror risultante potrebbe essere una delle seguenti possibili varianti:

* Se è stata specificata una SVM di destinazione eseguita con la stessa versione di ONTAP o con una versione più recente rispetto a quella del volume di origine, il risultato predefinito è una relazione SnapMirror basata sulla replicazione a blocchi.
* Se è stata specificata una SVM di destinazione eseguita con la stessa versione di ONTAP o con una versione più recente rispetto a quella del volume di origine, ma è stata abilitata la replica flessibile in base alla versione nelle impostazioni avanzate, il risultato sarà una relazione SnapMirror con replica flessibile in base alla versione.
* Se è stata specificata una SVM di destinazione eseguita con una versione precedente di ONTAP o una versione superiore a quella del volume di origine e la versione precedente supporta la replica flessibile in base alla versione, il risultato automatico sarà una relazione SnapMirror con replica flessibile in base alla versione.

