---
permalink: data-protection/task_edit_protection_relationships_from_health_volume.html 
sidebar: sidebar 
keywords: edit, protection, relationships, volume, health details page 
summary: È possibile modificare le relazioni di protezione esistenti per cambiare la velocità di trasferimento massima corrente, la politica di protezione o la pianificazione della protezione.  È possibile modificare una relazione per ridurre la larghezza di banda utilizzata per i trasferimenti o per aumentare la frequenza dei trasferimenti pianificati, poiché i dati cambiano spesso. 
---
= Modificare le relazioni di protezione dalla pagina Dettagli volume/salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le relazioni di protezione esistenti per cambiare la velocità di trasferimento massima corrente, la politica di protezione o la pianificazione della protezione.  È possibile modificare una relazione per ridurre la larghezza di banda utilizzata per i trasferimenti o per aumentare la frequenza dei trasferimenti pianificati, poiché i dati cambiano spesso.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver installato e configurato Workflow Automation.


I volumi selezionati devono essere destinazioni di relazioni di protezione.  Non è possibile modificare le relazioni quando sono selezionati volumi di origine, volumi di condivisione del carico o volumi che non sono la destinazione di una relazione SnapMirror o SnapVault .

.Passi
. Dalla scheda *Protezione* della pagina dei dettagli *Volume/Integrità*, individuare nella topologia la relazione di protezione che si desidera modificare e fare clic con il pulsante destro del mouse.
. Selezionare *Modifica* dal menu.
+
In alternativa, dal menu *Azioni*, seleziona *Relazione* > *Modifica* per modificare la relazione di cui stai visualizzando i dettagli.

+
Viene visualizzata la finestra di dialogo *Modifica relazione*.

. Nella finestra di dialogo Modifica relazione, modificare la velocità di trasferimento massima, la politica di protezione o la pianificazione della protezione, in base alle esigenze.
. Fare clic su *Applica*.
+
Le modifiche vengono applicate alle relazioni selezionate.


