---
permalink: data-protection/task_remove_protection_relationship_voldtls.html 
sidebar: sidebar 
keywords: remove, protection, relationship,  volume, health details page 
summary: 'È possibile rimuovere una relazione di protezione per eliminare definitivamente una relazione esistente tra l"origine e la destinazione selezionate: ad esempio, quando si desidera creare una relazione utilizzando una destinazione diversa.  Questa operazione rimuove tutti i metadati e non può essere annullata.' 
---
= Rimuovere una relazione di protezione dalla pagina dei dettagli Volume/Salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere una relazione di protezione per eliminare definitivamente una relazione esistente tra l'origine e la destinazione selezionate: ad esempio, quando si desidera creare una relazione utilizzando una destinazione diversa.  Questa operazione rimuove tutti i metadati e non può essere annullata.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.


.Passi
. Nella scheda *Protezione* della pagina dei dettagli *Volume/Integrità*, seleziona dalla topologia la relazione SnapMirror che desideri rimuovere.
. Fare clic con il pulsante destro del mouse sul nome della destinazione e selezionare *Rimuovi* dal menu.
+
Viene visualizzata la finestra di dialogo Rimuovi relazione.

. Fare clic su *Continua* per rimuovere la relazione.
+
La relazione viene rimossa dalla pagina dei dettagli Volume/Salute.


