---
permalink: data-protection/task_initialize_or_update_protection_relationships.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, page 
summary: Dalla pagina Relazioni volume è possibile eseguire un primo trasferimento di base su una nuova relazione di protezione oppure aggiornare una relazione se è già inizializzata e si desidera eseguire un aggiornamento incrementale manuale e non pianificato per effettuare il trasferimento immediato. 
---
= Inizializzare o aggiornare le relazioni di protezione dalla pagina Relazioni volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina Relazioni volume è possibile eseguire un primo trasferimento di base su una nuova relazione di protezione oppure aggiornare una relazione se è già inizializzata e si desidera eseguire un aggiornamento incrementale manuale e non pianificato per effettuare il trasferimento immediato.


NOTE: Non è possibile inizializzare o aggiornare i volumi protetti dai gruppi di coerenza.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato OnCommand Workflow Automation.


.Passi
. Dalla pagina *Relazioni volume*, fare clic con il pulsante destro del mouse su un volume e selezionare uno o più volumi con le relazioni che si desidera aggiornare o inizializzare, quindi, sulla barra degli strumenti, fare clic su *Inizializza/Aggiorna*.
+
Viene visualizzata la finestra di dialogo *Inizializza/Aggiorna*.

. Nella scheda *Opzioni di trasferimento*, seleziona una priorità di trasferimento e la velocità di trasferimento massima.
. Fare clic su *Copie snapshot di origine*; quindi, nella colonna *Copia snapshot*, fare clic su *Predefinito*.
+
Viene visualizzata la finestra di dialogo Seleziona copia snapshot di origine.

. Se si desidera specificare una copia Snapshot esistente anziché trasferire la copia Snapshot predefinita, fare clic su *Copia Snapshot esistente* e selezionare una copia Snapshot dall'elenco.
. Fare clic su *Invia*.
+
Verrà visualizzata nuovamente la finestra di dialogo *Inizializza/Aggiorna*.

. Se hai selezionato più di una sorgente da inizializzare o aggiornare, fai clic su *Predefinito* per la sorgente successiva per la quale desideri specificare una copia Snapshot esistente.
. Fare clic su *Invia* per avviare il processo di inizializzazione o aggiornamento.
+
Viene avviato il processo di inizializzazione o aggiornamento, si torna alla pagina Relazioni volume e nella parte superiore della pagina viene visualizzato un collegamento ai processi.

. *Facoltativo:* fare clic su *Visualizza processi* nella vista *Integrità: tutti i volumi* per monitorare lo stato di ciascun processo di inizializzazione o aggiornamento.
+
Viene visualizzato un elenco filtrato di lavori.

. *Facoltativo:* clicca su ogni lavoro per visualizzarne i dettagli.
. *Facoltativo:* fare clic sulla freccia *Indietro* del browser per tornare alla pagina *Relazioni di volume*.
+
L'operazione di inizializzazione o aggiornamento è terminata quando tutte le attività sono state completate correttamente.


