---
permalink: data-protection/task_create_snapvault_policy_to_maximize_transfer_efficiency.html 
sidebar: sidebar 
keywords: create, snapvault, policy,  maximize, transfer, efficiency 
summary: 'È possibile creare un nuovo criterio SnapVault per impostare la priorità per un trasferimento SnapVault .  Si utilizzano policy per massimizzare l"efficienza dei trasferimenti dal primario al secondario in una relazione di protezione.' 
---
= Crea una policy SnapVault per massimizzare l'efficienza del trasferimento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un nuovo criterio SnapVault per impostare la priorità per un trasferimento SnapVault .  Si utilizzano policy per massimizzare l'efficienza dei trasferimenti dal primario al secondario in una relazione di protezione.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.
* È necessario aver già completato l'area Informazioni sulla destinazione nella finestra di dialogo Configura protezione.


.Passi
. Dalla scheda * SnapVault* della finestra di dialogo *Configura protezione*, fare clic sul collegamento *Crea criterio* nell'area *Impostazioni relazione*.
+
Viene visualizzata la scheda SnapVault .

. Nel campo *Nome policy*, digitare il nome che si desidera assegnare alla policy.
. Nel campo *Priorità di trasferimento*, seleziona la priorità di trasferimento che desideri assegnare alla policy.
. *Facoltativo:* nel campo *Commento*, inserisci un commento per la policy.
. Nell'area *Etichetta di replica*, aggiungere o modificare un'etichetta di replica, se necessario.
. Fare clic su *Crea*.
+
La nuova policy viene visualizzata nell'elenco a discesa Crea policy.


