---
permalink: data-protection/task_resynchronize_protection_relationships_voldtls.html 
sidebar: sidebar 
keywords: resynchronize, protection, relationships, volume, health details page 
summary: 'È possibile risincronizzare i dati su una relazione SnapMirror o SnapVault che è stata interrotta e in seguito la destinazione è stata resa di lettura/scrittura in modo che i dati sull"origine corrispondano ai dati sulla destinazione.  È anche possibile risincronizzare quando una copia Snapshot comune richiesta sul volume di origine viene eliminata, causando il fallimento degli aggiornamenti di SnapMirror o SnapVault .' 
---
= Risincronizzare le relazioni di protezione dalla pagina dei dettagli Volume/Stato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile risincronizzare i dati su una relazione SnapMirror o SnapVault che è stata interrotta e in seguito la destinazione è stata resa di lettura/scrittura in modo che i dati sull'origine corrispondano ai dati sulla destinazione.  È anche possibile risincronizzare quando una copia Snapshot comune richiesta sul volume di origine viene eliminata, causando il fallimento degli aggiornamenti di SnapMirror o SnapVault .

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato OnCommand Workflow Automation.


.Passi
. Dalla scheda *Protezione* della pagina dei dettagli *Volume/Integrità*, individuare nella topologia la relazione di protezione che si desidera risincronizzare e fare clic con il pulsante destro del mouse.
. Selezionare *Risincronizza* dal menu.
+
In alternativa, dal menu *Azioni*, seleziona *Relazione* > *Risincronizza* per risincronizzare la relazione di cui stai visualizzando i dettagli.

+
Viene visualizzata la finestra di dialogo Risincronizza.

. Nella scheda *Opzioni di risincronizzazione*, selezionare una priorità di trasferimento e la velocità di trasferimento massima.
. Fare clic su *Copie snapshot di origine*; quindi, nella colonna *Copia snapshot*, fare clic su *Predefinito*.
+
Viene visualizzata la finestra di dialogo Seleziona copia snapshot di origine.

. Se si desidera specificare una copia Snapshot esistente anziché trasferire la copia Snapshot predefinita, fare clic su *Copia Snapshot esistente* e selezionare una copia Snapshot dall'elenco.
. Fare clic su *Invia*.
+
Verrà visualizzata nuovamente la finestra di dialogo Risincronizza.

. Se hai selezionato più di una sorgente da risincronizzare, fai clic su *Predefinito* per la sorgente successiva per la quale desideri specificare una copia Snapshot esistente.
. Fare clic su *Invia* per avviare il processo di risincronizzazione.
+
Il processo di risincronizzazione viene avviato, si torna alla pagina dei dettagli Volume/Stato e nella parte superiore della pagina viene visualizzato un collegamento ai processi.

. *Facoltativo:* fare clic su *Visualizza processi* nella pagina *Dettagli volume/stato* per monitorare lo stato di ciascun processo di risincronizzazione.
+
Viene visualizzato un elenco filtrato di lavori.

. *Facoltativo:* fai clic sulla freccia *Indietro* del browser per tornare alla pagina dei dettagli *Volume / Salute*.
+
Il processo di risincronizzazione è terminato quando tutte le attività vengono completate correttamente.


