---
permalink: data-protection/task_create_resource_pools.html 
sidebar: sidebar 
keywords: creating, resource, pools 
summary: È possibile utilizzare la finestra di dialogo Crea pool di risorse per raggruppare gli aggregati a scopo di provisioning. 
---
= Creare pool di risorse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di dialogo Crea pool di risorse per raggruppare gli aggregati a scopo di provisioning.

.Prima di iniziare
È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.

.Passi
I pool di risorse possono contenere aggregati provenienti da cluster diversi, ma lo stesso aggregato non può appartenere a pool di risorse diversi.

. Nel riquadro di navigazione a sinistra, fare clic su *Protezione* > *Pool di risorse*.
. Nella pagina *Pool di risorse*, fare clic su *Crea*.
. Seguire le istruzioni nella finestra di dialogo *Crea pool di risorse* per fornire un nome e una descrizione e per aggiungere aggregati come membri al pool di risorse che si desidera creare.

