---
permalink: data-protection/task_reverse_protection_relationships_from_health_volume_details.html 
sidebar: sidebar 
keywords: reverse, protection, relationships volume, health details page 
summary: 'Quando un disastro disabilita il volume di origine nella relazione di protezione, è possibile utilizzare il volume di destinazione per gestire i dati convertendoli in lettura/scrittura mentre si ripara o si sostituisce l"origine.  Quando la sorgente è nuovamente disponibile per ricevere dati, è possibile utilizzare l"operazione di risincronizzazione inversa per stabilire la relazione nella direzione inversa, sincronizzando i dati sulla sorgente con i dati sulla destinazione di lettura/scrittura.' 
---
= Relazioni di protezione inversa dalla pagina dei dettagli Volume/Salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un disastro disabilita il volume di origine nella relazione di protezione, è possibile utilizzare il volume di destinazione per gestire i dati convertendoli in lettura/scrittura mentre si ripara o si sostituisce l'origine.  Quando la sorgente è nuovamente disponibile per ricevere dati, è possibile utilizzare l'operazione di risincronizzazione inversa per stabilire la relazione nella direzione inversa, sincronizzando i dati sulla sorgente con i dati sulla destinazione di lettura/scrittura.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.
* La relazione non deve essere una relazione SnapVault .
* Deve già esistere un rapporto di protezione.
* Il rapporto di protezione deve essere interrotto.
* Sia la sorgente che la destinazione devono essere online.
* La sorgente non deve essere la destinazione di un altro volume di protezione dei dati.
* Quando si esegue questa attività, i dati sulla fonte più recenti rispetto ai dati sulla copia Snapshot comune vengono eliminati.
* Le policy e le pianificazioni create sulla relazione di risincronizzazione inversa sono le stesse di quelle sulla relazione di protezione originale.
+
Se non esistono policy e pianificazioni, vengono create.



.Passi
. Dalla scheda *Protezione* della pagina dei dettagli *Volume/Integrità*, individuare nella topologia la relazione SnapMirror su cui si desidera invertire l'origine e la destinazione e fare clic con il pulsante destro del mouse.
. Selezionare *Risincronizzazione inversa* dal menu.
+
Viene visualizzata la finestra di dialogo Risincronizzazione inversa.

. Verificare che la relazione visualizzata nella finestra di dialogo *Risincronizzazione inversa* sia quella per cui si desidera eseguire l'operazione di risincronizzazione inversa, quindi fare clic su *Invia*.
+
La finestra di dialogo Risincronizzazione inversa viene chiusa e nella parte superiore della pagina Dettagli volume/integrità viene visualizzato un collegamento al processo.

. *Facoltativo:* fare clic su *Visualizza processi* nella pagina dei dettagli *Volume/Stato* per monitorare lo stato di ciascun processo di risincronizzazione inversa.
+
Viene visualizzato un elenco filtrato di lavori.

. *Facoltativo:* fai clic sulla freccia *Indietro* del browser per tornare alla pagina dei dettagli *Volume / Salute*.
+
L'operazione di risincronizzazione inversa termina quando tutte le attività di lavoro sono state completate correttamente.


