---
permalink: data-protection/task_quiesce_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: quiesce, protection, relationship, volume, health details page 
summary: È possibile sospendere una relazione di protezione per impedire temporaneamente il trasferimento dei dati.  È possibile disattivare una relazione quando si desidera creare una copia Snapshot di un volume di destinazione SnapMirror contenente un database e si desidera garantire che il suo contenuto sia stabile durante la copia Snapshot. 
---
= Disattiva una relazione di protezione dalla pagina dei dettagli Volume/Salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sospendere una relazione di protezione per impedire temporaneamente il trasferimento dei dati.  È possibile disattivare una relazione quando si desidera creare una copia Snapshot di un volume di destinazione SnapMirror contenente un database e si desidera garantire che il suo contenuto sia stabile durante la copia Snapshot.

.Prima di iniziare
* È necessario disporre del ruolo di Amministratore dell'applicazione o Amministratore dell'archiviazione.
* È necessario aver configurato l'automazione del flusso di lavoro.


L'azione di quiescenza non viene visualizzata nei seguenti casi:

* Se le impostazioni RBAC non consentono questa azione, ad esempio se si dispone solo dei privilegi di operatore
* Quando l'ID del volume è sconosciuto, ad esempio quando si ha una relazione intercluster e il cluster di destinazione non è ancora stato scoperto
* Quando non hai associato Workflow Automation e Unified Manager


.Passi
. Nella scheda *Protezione* della pagina dei dettagli *Volume/Integrità*, fare clic con il pulsante destro del mouse sulla relazione nella vista topologia per la relazione di protezione che si desidera disattivare.
. Selezionare *Quiesce* dal menu.
. Fare clic su *Sì* per continuare.
+
Lo stato del processo di quiesce viene visualizzato nella parte superiore della pagina dei dettagli Volume/Integrità, insieme a un collegamento ai dettagli del processo.

. Fare clic sul collegamento *Visualizza dettagli* per andare alla pagina dei dettagli del *Lavoro* per ulteriori dettagli e per conoscere lo stato di avanzamento del lavoro.
. *Facoltativo:* fai clic sulla freccia Indietro del browser per tornare alla pagina dei dettagli *Volume / Salute*.
+
Il processo di quiesce termina quando tutte le attività sono state completate con successo.


